### ISSUE TITLE
Enhancement: GAMA brochure

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1044]
```
Describe which enhancement/addition to GAMA you would like to see:

Hi


This summer (14-18 July), I will be going to a summer school on ABM, each participant
will be talking about their software tools. I was wondering if you have any ready one-or-two
page brochure that I can distribute or use in my discussion. Please let me know,

best regards,
Srirama



```

Original issue reported on code.google.com by `b.srirama` on 2014-06-02 09:57:49

**Comment by AlexisDrogoul** [comment]
The new website will contain a lot of material — might be a good idea to have a leaflet-like page that can be printed. I've assigned @mazarsju to this issue.

**Comment by mazarsju** [comment]
Here is a first proposal. What do you think ? Feel free to make remarks / suggestions.
![brochure](https://cloud.githubusercontent.com/assets/12977635/13530029/da965668-e251-11e5-944a-e4dd2b56f1c2.png)

**Comment by AlexisDrogoul** [comment]
Quickly: can you share the original (in PowerPoint ?) on GitHub ?
- some texts need to be revised
- I think it's lacking a concrete visualization of displays/code

I'm ok to handle the first task

**Comment by sriramab** [comment]
Hi,

I think it is too cluttered and lacks clarity, all the blue scrambled text is more prominent than GAMA text in orange. What is important should be dark coloured, what is background should be light coloured. Also the order of quadrants and groupings do not send a clear message about the strengths of the software. Currently if four quadrants are 

1 2
3 4

It would be better in my opinion to be 

2 3
4 1

In words:
What is GAMA (2) Why it is different (3)
How it helps (4) Whats included (1)

As of now, the orange titles are not for any body, they already assume the user is a computer scientist or very active in simulations. For example, social scientist may have no clue what it means by 'declarative user interface' ; 'high level and intuitive language' . And the orange titles don't capture the theme of the bullets under them.

In my humble opinion, these terms will be discouraging to a new user. 

For example, in 'whats included' section, you could have:
1. Model library
2. Tutorials
3. Active support and user group
4. General and customised training sessions from developers

For example in ' what is GAMA' you could have:
1. Open source
2. multi agent
3. intuitive language, 
4. declarative ui

For example in ' why it is different':
1. GIS based, OSM support
2. large-scale models
3. extensible by plugins
4. R, database  and other connections

Just some suggestions because I care :) 

regards,
Srirama

**Comment by AlexisDrogoul** [comment]
Now moved to: https://github.com/mazarsju/gama_doc_17/issues/10
