### ISSUE TITLE
Barabasi with Yifan Hu not fixed to a seed value

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#1149]
```
What steps will reproduce the problem?
1. Please see link in additional information below
2. I have attached the model from the discussion to this issue.
3. run the mode with and without seed value in experiment block.

What is the expected output? What do you see instead?
I expect that for a given (fixed seed ) barabasi network, the force-directed graph
(Yifan Hu implementation) should always be the same as its input graph is the same
and all the parameters are the same.

Please use labels and text to provide additional information.
Please see this discussion:
https://groups.google.com/forum/#!topic/gama-platform/SC25awlpLyY
```

Original issue reported on code.google.com by `b.srirama` on 2015-01-08 12:16:16
<hr>
 * *Attachment: [Classic Graph Layout (2).gaml](https://storage.googleapis.com/google-code-attachments/gama-platform/issue-1146/comment-0/Classic Graph Layout (2).gaml)*

**Comment by AlexisDrogoul** [comment]
AFAK, Gephi has not evolved in that respect. There is currently nothing we can do to force the library to use our RNG. I prefer to close this issue, then, instead of keeping it floating around, knowing that nothing can be done by us. I have filed an issue in the Gephi bug tracker (https://github.com/gephi/gephi/issues/1402) — in case it is answered, I will reopen it.
