### ISSUE TITLE
Package a file containing base information on the release to help debugging

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#115]
**Describe the improvement you'd like**
To help debugging we often need to know precisely the version of gama and some other basic information. We could package a file with every release (including alphas) containing them. The file should contain:

- version number/compilation date
- latest commit
- branch
- jdk version if packaged with the release

**Comment by AlexisDrogoul** [comment]
Instead of adding a new file, I would be in favour of completing the `config.ini` file (see https://stackoverflow.com/questions/20739927/eclipse-rcp-config-ini) with, for instance, `gama.version`, `gama.commit`, `gama.branch`, `gama.date`, `gama.jdk`keys. So that these keys become easily and automatically accessible through the `System.getProperty(key)` method.
