### ISSUE TITLE
Building workspace blocked after having modified and saved a model from the library

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1245]
From a new and clean GAMA workspace, I open any model from the library, I modify it to have a compilation error and save the file.

The building workspace appears to be blocked at 0% and a pop up message appears, stays and blocks the use of GAMA.

Note that I have the same issue with any model in the library and any other model that I have not written myself and that are not allowed to be written by someone but the owner.

Benoit

**Comment by AlexisDrogoul** [comment]
Well, the issue is probably the same as the one reported in #1240. However, between the changes in the management of the workspace in Luna (vs. Juno) and the changes introduced by XText regarding threaded builds, I'm not completely sure where to look … One thing is sure, however: the workaround, albeit unpractical, is to cancel the last task ("Waiting for User Operation", I think).

**Comment by benoitgaudou** [comment]
You re right, I have the same screenshot.
But I do not have this issue on my own models, created in a GAMA 1.7 workspace, or when I allowed write right to everybody on the file.

**Comment by AlexisDrogoul** [comment]
I have committed a change that should — normally — fix this issue. Is it the case ?

**Comment by benoitgaudou** [comment]
Hi,
Yes it seems to be the case.
I just tried this morning to modify models from library and no error popup appears.
Thanks a lot

Benoit
