### ISSUE TITLE
create species from: number;   GAMA behavior has changed from 1.6.1 to 1.7

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1246]
In a model, I have: 
		create people from: 1;

I am aware this is a missuse of the create statement.
Nevertheless, in GAMA 1.6.1, this statement created a people agent.
In GAMA 1.7.1, this does not create anything.

A warning or exception should be used to warn the modeler of this behavior.

Benoit

**Comment by AlexisDrogoul** [comment]
Hmmm… Since the infrastructure has changed a little bit regarding the "create" statement (devs can now declare their own implementation of ICreateDelegate in their plugins), there is no way to know in advance what kind of data will be passed to the 'from:' facet. The only solution would be to change a bit the ICreateDelegate implementation by making it return the type expected for the 'from' facet and checking these types at compile time. I will see what I can do…
