### ISSUE TITLE
improve reading of geotiff

### ISSUE THREAD

**Issue by ElCep** [gama-platform/gama#1253]
It could be nice to read geoTiff or other raster files directly in Gama. 
thank you in advance
E.

**Comment by ptaillandier** [comment]
Hi,

I have just committed a fix for this issue: GAMA can now load geotiff data as asc data: 
model geotiffloading
global {
	file grid_file1 <- file('../includes/cea.tif') ;
	geometry shape <- envelope(grid_file1);	
}
grid cell file: grid_file1;	
experiment gridloading type: gui {
	output {
               display test type: opengl {
			grid cell grayscale: true;
		}
	} 
}

However, there is for the moment one limitation: only one band of data are taken into account. If your geotiff relies on several bands (color), GAMA will compute the mean value for the grid_value attribute of each cell.

**Comment by AlexisDrogoul** [comment]
One thing that could be done would be to load all the information (like we do for shape files), for each cell, in a list (`bands`), in order to allow the user to, either load the list for each cell in a species attribute or decide which one will be the `grid_value` (i.e. `… with: [grid_value::bands[0]]`)
