### ISSUE TITLE
datetime/calendar integration

### ISSUE THREAD

**Issue by annalisapg** [gama-platform/gama#1258]
Hi all,
I suppose it could be useful to integrate "datetime" in GAMA as a cycle variable.
I mean, giving a starting and (optionally) an ending date to the simulation, fixing a datetime formatted step and use it instead of the cycle variable. 
In my opinion this could facilitate each simulation which requires a calendar integration e. g.:
* fishing calendars for simulation of fishing activities;
* vineyard treatement calendar to simulate a vineyard production;
.. and many other more situations.

What's your opinion about it?
do you think, devs, that should be useful to create a sort of datetime-based "branch" which works like that?

**Comment by AlexisDrogoul** [comment]
This enhancement can probably be added with a minimum effort.

- [ ] Add `starting_date` and `current_date` attributes to simulation agents. If the former is initialized, as well as the `step` attribute (for instance, `step <- 1 #month;`), then a "regular" (Ie. western) calendar is used, otherwise the current calendar (where months have 30 days, years 360 days) is used by default.
- [ ] Add a `date` type backed by the calendar already used internally for the fake calendar, which would give access to at least 3 fields: `day`, `month`, `year`.
- [ ] Add several operators: `date(int day, int month, int year)`, `date(int day, string month, int year)` for building dates; `+`, `-` for operations on durations (e.g., `date(20, 03, 1968) + 200 #days` -> a new date; `date(20, 03, 1968) - date(20, 04, 1920)` -> a duration expressed in the number of time steps). Maybe others will be necessary, like comparison (`=` & '!=' of course, but also '>', '>=', '<=', '<').

The treatment of the current #day, #month, #year units will also need to be modified (so as to correctly add 1 year when `date(20, 03, 1968) + 1 #year` is invoked, and not the 360 days it currently represents…).

Who is in among @gama-platform/committers  ?

**Comment by ptaillandier** [comment]
Ok, the date type is now operational and several operators are provided. I added as well a detailed feature model concerning date in the Model library
The two last things to do to close this issue: 
  - add a warning on \#month and \#year when using a starting_date
   - write a recipes page on Date (inspired by the feature model).
