### ISSUE TITLE
Weird behavior of containers (problem of local variables ?)

### ISSUE THREAD

**Issue by mathieuBourgais** [gama-platform/gama#1266]
Test this simple model:
global {
	list a;
	reflex tet {
	 	map mp <- ["testValue"::rnd(20)];
	 	a << mp;
	 	write a;
	}
}

I expected to get: 
[map(['testValue'::1])]
[map(['testValue'::1]),map(['testValue'::4])]
[map(['testValue'::1]),map(['testValue'::4]),map(['testValue'::7])]

and I get:
[map(['testValue'::1])]
[map(['testValue'::4]),map(['testValue'::4])]
[map(['testValue'::7]),map(['testValue'::7]),map(['testValue'::7])]

**Comment by benoitgaudou** [comment]
Hi,

I think we have an issue to be fixed for the next GAMA release.
In fact the behavior you are expected appears very intuitive to me. And it
was the behavior we had in GAMA 1.6.1.
But in the GAMA in development version, we have the one you get.
So I will submit an issue about this issue.

Thank you

Benoit Gaudou

2015-08-26 11:10 GMT+02:00 mathieuBourgais <notifications@github.com>:

**Comment by ptaillandier** [comment]
To add something that is very weird with this issue:
Test the following model:
model IssueContainerVar
global {
	list a;
	reflex test {
		map mp <- ["testValue_"+ cycle::rnd(20)];
		a << mp;
		write a;
	}
}
experiment IssueContainer type: gui {}

Run 3 steps of the simulation:
I get:
[map(['testValue_0'::4]),map(['testValue_0'::4,'testValue_1'::11]),map(['testValue_0'::4,'testValue_1'::11,'testValue_2'::15])]

Instead of:
[map(['testValue_0'::4]),map(['testValue_1'::11]),map(['testValue_2'::15])]

If I reload the model (reload button), I get at the first step:
[map(['testValue_0'::13,'testValue_1'::11,'testValue_2'::15])]
instead of:
[map(['testValue_0'::13])]

It is like if the local variable (the map) is still keep in memory even after a reload.
