### ISSUE TITLE
Sliders to control parameter values

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#1269]
Hi,

I would like to request a slider like control for increasing or decreasing parameter values. 

See like example here
http://www.telerik.com/kendo-ui/slider

thanks
Srirama

**Comment by AlexisDrogoul** [comment]
I have committed a first and preliminary version that automatically creates a slider if 

1) You are editing an int parameter
2) Max and min are defined

Note that it doesn't work, for the moment, for float parameters and that it doesn't respect the step (if any is defined).

Please comment on this first implementation ...

**Comment by AlexisDrogoul** [comment]
A second version has been committed. This time, float values are correctly handled, as well as the definition of a step if there is one. In the absence of step, `1` is used for int values and an arbitrary step that depends on the size of the slider (i.e. how much does one pixel represent ?) is used for float values. 
The conversion to a slider is automatic as soon as you have a max and a min. Otherwise, normal input boxes are used.

**Comment by AlexisDrogoul** [comment]
Third commit, this time with the possibility to revert to the original value. I consider the developments to be finished on this -- I close the issue, then, but feel free to reopen for more focused requests / problems.

**Comment by agrignard** [comment]
I like a lot the slider control. I have one tiny question... Why do you choose a green color ? I mean it could stay gray no? (Ok it's a very very little detail but to keep the GUI as simple as possible I found that a gray slider would be perfect and minimal)
