### ISSUE TITLE
Init block execution order(s)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1277]
I attach a model showing the order in which the various init blocks are called.
We can observe the following output:
GLOBAL INIT: in Create farmer0
GLOBAL INIT: in Create farmer1
GLOBAL INIT: in Create farmer2
Another Statement in GLOBAL INIT
init in human farmer0
init in Farmer farmer0
init in human farmer1
init in Farmer farmer1
init in human farmer2
init in Farmer farmer2
---- cyle 0
init in human farmer3
init in Farmer farmer3
GLOABAL REFLEX: in create farmer3

I have to concerns/questions about this order.
- First the order is not the same when the create is called in the global init or in a reflex.
- Second in the global init, the init block in species are  called only after all the statements in the global init have been executed.

Intuitively, the order should be in any case: 
- init of parent species
- init of species
- the create block

Cheers
Benoit

model TestInit

global {
	point p;
	
	init {	
		create farmer number: 3 {
			write "GLOBAL INIT: in Create " + self;
		}		
		write "Another Statement in GLOBAL INIT";
	}
	
	
	reflex p2 {
		write "---- cyle " + cycle;
		create farmer {
			write "GLOABAL REFLEX: in create " + self; 
		}		
	}
}

species human {
	init {
		write "init in human " + self;
	}
}

species farmer parent: human{
	init {
		write "init in Farmer " + self; 
	}
}

experiment TestInit type: gui { output {} }

**Comment by AlexisDrogoul** [comment]
You're right. There is a flaw in the init sequence. The statements inside `create` should be called after the init of the species have been made. However (I just tested it), this flaw exists also in 1.6.1, which means some models probably rely on it… I will push a commit to fix it, but it will need to be tested intensively...

**Comment by AlexisDrogoul** [comment]
I have just committed a fix.
The init sequence is modified so that the statements passed to a create are executed after the init of the agent has been executed (and not before). This behavior is now coherent whether the create is executed in an init or during the simulation.

I close this issue, but it needs to be tested quite extensively, at least on the models of the library.

**Comment by AlexisDrogoul** [comment]
I reopen the issue, because the behavior (with the same model) is now: 

Another Statement in GLOBAL INIT
init in human farmer0
init in Farmer farmer0
GLOBAL INIT: in Create farmer0
init in human farmer1
init in Farmer farmer1
GLOBAL INIT: in Create farmer1
init in human farmer2
init in Farmer farmer2
GLOBAL INIT: in Create farmer2
---- cyle 0
init in human farmer3
init in Farmer farmer3
GLOABAL REFLEX: in create farmer3
init in human farmer4
init in Farmer farmer4
GLOABAL REFLEX: in create farmer4
init in human farmer5
init in Farmer farmer5
GLOABAL REFLEX: in create farmer5

Which means that the init of the world is completely executed **before** the init of the agents are executed. Is it coherent ? Or should the init of the agents be executed before ?

**Comment by AlexisDrogoul** [comment]
Hi,

I've reverted the previous changes to allow for a complete initialization of agents (including the block in `create`) before their creator is initialized itself. 

This time, the sequence is:

init in human farmer0
init in Farmer farmer0
init in human farmer1
init in Farmer farmer1
init in human farmer2
init in Farmer farmer2
GLOBAL INIT: in Create farmer0
GLOBAL INIT: in Create farmer1
GLOBAL INIT: in Create farmer2
Another Statement in GLOBAL INIT
---- cyle 0
init in human farmer3
init in Farmer farmer3
init in human farmer4
init in Farmer farmer4
init in human farmer5
init in Farmer farmer5
GLOABAL REFLEX: in create farmer3
GLOABAL REFLEX: in create farmer4
GLOABAL REFLEX: in create farmer5

It is normally putting an end to this issue. Please reopen if something is wrong.
