### ISSUE TITLE
Remember the gama workspace after a crash of the application

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1294]
It should be nice to remember the workspace after a crash of the application. Maybe to save the workspace after each file closing/opening should be better than to save the workspace after a clean application closing...

**Comment by AlexisDrogoul** [comment]
When you say "remember the workspace", do you mean "remember the location of the workspace" or "remember the state in which the workbench was before the crash" ? Because the first should be automatic, but I wonder how to handle the second one: see issue #870 to see that it is more an annoyance than a feature to have the views restored automatically. Or maybe we should only apply it to the "Modeling" perspective ?

**Comment by AlexisDrogoul** [comment]
OK. I have gone through a long list of Eclipse bugs and advices, to finally discover that there is a preference (inherited by GAMA, go to "Preferences" and then "Advanced…") to save the workbench at regular states. Guess you were not the only one to request that feature (even in Eclipse). So it is not exactly what you meant, but you can set the interval to 1 minute and see if it changes something to your workflow. 


<img width="654" alt="capture 2015-12-02 a 18 29 22" src="https://cloud.githubusercontent.com/assets/579256/11530078/259a50a0-9924-11e5-9af5-3343cdb21a79.PNG">

**Comment by mazarsju** [comment]
Ok
