### ISSUE TITLE
Warning in the model GIS Visualization

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1299]
In the model library > Features > GIS data > GIS Visualization.gaml.
Run the model.
The following error appears:
"at cycle 0: Texture can only be applied on quad or rectangle".

Note : on GAMA Git under Eclipse Mars.1

**Comment by agrignard** [comment]
This problem is not related to Mars, it's also occuring in the gitversion with Luna and in 1.6.1 (but no error is raised)

It is because we took (well maybe I...) the decision to apply texture only on quad or rectangle (or a polygon with 4 points). In the model GIS Visualization.gaml there are some building whose shape is not a square, so when we try to map a texture on it, it raises an error saying that texture can only be applied on a quad or a square. 

The shortest and fastest solution to fix this issue is to not apply a texture on the roof in the model.

**Comment by ptaillandier** [comment]
So the question is: what are we going to do for GAMA 1.7?

**Comment by AlexisDrogoul** [comment]
Is there a technical reason to not apply textures on complex shapes ?

**Comment by agrignard** [comment]
It's not really a technical reason but a choice.

Now the syntax consist in saying: I want to map this texture (which is a
square or a rectangle) on this shape. If the shape is not a square or a
rectangle the results will be arbitrary (I mean we (GAMA) will have to
decide which part of the texture goes on the shape).

 if we want to allow people to map complex shape we should propose a way to
"map" any vertex of the geometry to the given pixel of the texture.

In Opengl this is done like that:

glBegin(GL_QUADS);
   glTexCoord2f(0, 0);
   glVertex3dv(a);
   glTexCoord2f(1, 0);
   glVertex3dv(b);
   glTexCoord2f(1, 1);
   glVertex3dv(c);
   glTexCoord2f(0, 1);
   glVertex3dv(d);
glEnd();

but it implies that the modellers has a good knowledge in mapping
techniques.

I think that the mapping of complex object can be solve with the issue #1318

**Comment by AlexisDrogoul** [comment]
One (arbitrary) way could be to map the texture to the envelope of the shape : it would work for rectangles and squares like now, and could be documented so that people understand what it could produce. How could this be done in OpenGL ? 


> Le 6 déc. 2015 à 23:15, agrignard <notifications@github.com> a écrit :
> 
> It's not really a technical reason but a choice.
> 
> Now the syntax consist in saying: I want to map this texture (which is a
> square or a rectangle) on this shape. If the shape is not a square or a
> rectangle the results will be arbitrary (I mean we (GAMA) will have to
> decide which part of the texture goes on the shape).
> 
> if we want to allow people to map complex shape we should propose a way to
> "map" any vertex of the geometry to the given pixel of the texture.
> 
> In Opengl this is done like that:
> 
> glBegin(GL_QUADS);
> glTexCoord2f(0, 0);
> glVertex3dv(a);
> glTexCoord2f(1, 0);
> glVertex3dv(b);
> glTexCoord2f(1, 1);
> glVertex3dv(c);
> glTexCoord2f(0, 1);
> glVertex3dv(d);
> glEnd();
> 
> but it implies that the modellers has a good knowledge in mapping
> techniques.
> 
> I think that the mapping of complex object can be solve with the issue #1318
> 
> 
> 
> 
> 
> On 5 December 2015 at 03:30, Alexis Drogoul <notifications@github.com>
> wrote:
> 
> > Is there a technical reason to not apply textures on complex shapes ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gama-platform/gama/issues/1299#issuecomment-162160904>
> > .
> >
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by agrignard** [comment]
I see the idea and it can be a good solution. So the idea would be to compute for each vertex of the shape it's relative position (between 0 and 1) compared to its envelope. The envelope would be seen as the texture. Not so hard to in Opengl I think

**Comment by agrignard** [comment]
The issue #1390 is more or less the same

**Comment by agrignard** [comment]
should be fixed. Maybe need to try on different model.
