### ISSUE TITLE
OpenGL display : colorless agents when displaying geometries with holes

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1302]
This issue can be related to #1301 .
Open and run the attached model (.zip.txt file, please remove the .txt extension to get a .zip archive file).
Whereas agents have a color, they are displayed colorless...

[Zombies.zip.txt](https://github.com/gama-platform/gama/files/33175/Zombies.zip.txt)

**Comment by AlexisDrogoul** [comment]
This issue is actually completely related to #1301. As soon as "correct" geometries are produced by the serialization/deserialization of geometries, they are displayed with their color... 

The question is now, of course, what to do: I am in favor of forcing this "correctness" in a way or another when we have holes, but I'm awaiting the advice of our geometry guru (@ptaillandier -- I"ve assigned this bug to him !) on two points: 

1) Should we use the explicit (and a bit heavy) mechanism of serialization/deserialization to do it or are there other ways to do it.

2) Should we return polygons instead of polylines for holes (that is maybe a key to the problem, and would probably improve the performances anyway).

**Comment by ptaillandier** [comment]
I think I fix this issue (by just fixing an error concerning polygons with Nan value for z).
Can you test it?
