### ISSUE TITLE
Display a grid in opengl

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1310]
Here is my code :

model my_model

global{
	float max_range <- 4.0;
	init {
		create my_species number:2;
	}
}

grid my_grid width:20 height:20 neighbours:4 {
	reflex update {
		color <- #green;
	}
}

species my_species skills:[moving] {
	float speed <- 2.0;
	reflex update {
		do wander amplitude:20;
		
		ask my_grid at_distance(max_range)
		{
			if(self overlaps myself)
			{
				self.color <- #red;
			}
			else
			{
				self.color <- #yellow;
			}
		}
		
	}
	aspect default {
		draw circle(1);
	}
}

experiment MyExperiment type: gui {
    output {
        display MyDisplay type: opengl {
            grid my_grid lines:#black;
            species my_species aspect:default; 
        }
    }
}

Before the simulation, all the cells have a pretty square shape : 
![simu2](https://cloud.githubusercontent.com/assets/12977635/11394424/7d50e74c-9397-11e5-9471-713dcba85ddc.png)

But once I launch the simulation, it is the total anarchy:
![simu](https://cloud.githubusercontent.com/assets/12977635/11394433/8ea3307c-9397-11e5-9827-39e6c546f6e6.png)

**Comment by agrignard** [comment]
Quickly. It's not a problem of built-in color (same with rgb) but a problem of the size of the cell which is not taken in account. With a 100x100 grid (the default one) everything is ok.

**Comment by ptaillandier** [comment]
Hi,

I am not sure to understand what you wanted to show in this example, but
the problem seems to be linked to the OpenGL display (test it with java2d
display and all seem ok).

Cheers,

Patrick

2015-11-25 11:43 GMT+01:00 agrignard <notifications@github.com>:

**Comment by agrignard** [comment]
Yes it's an Opengl problem. I guess I don't take correctly in account the size of the cell (in this example the grid has width:20 and height:20) or something like that as it works with a default grid. Not a big deal but a bug... I'll try to dig it ASAP.

**Comment by AlexisDrogoul** [comment]
Any update on this one ? Where should we dig to know where to take the grid dimensions into account ?

**Comment by agrignard** [comment]
It should be somewhere in DEMDrawer.java I guess

**Comment by AlexisDrogoul** [comment]
Actually, this particular drawing is handled by ImageDrawer and there is a problem here, as if one uses `agents "xx" value: my_grid; ` the model is correctly displayed. However, I can't really understand what is happening there. If you have any idea…

**Comment by AlexisDrogoul** [comment]
OK. I guess I found it. I think it is simply due to a bad scaling made by OpenGL when "projecting" the image. Keep in mind that, in a typical display, your example represents a 20x20 image, upscaled to a texture with a dimensions being a power of 2 (in that case, probably, 32x32), projected onto ~400x~400 pixels. No wonder it is distorted. 

To verify this, give your grid a dimension which is a power of 2 (32x32, 16x16). The result will be fine (as fine as it is in Java2D).

The distorsion is particularly visible here because the size of the grid is small. As you increase it, it will be less visible (but still present at 200x200, etc.).

`grid` is however just an optimization (directly drawing the Image data obtained from the color of each cell), which proves useful in Java2D,  but I'm not sure it makes any sense for OpenGL if we have these results. Either we have to turn it into a "normal" species drawing (cell by cell) transparently (if no DEM is present, of course, just the "normal" grid), or we have to find a way to create "non power of 2" textures (something that has systematically failed until now, I think).

What's your opinion on this ?

**Comment by agrignard** [comment]
Nice intuition!!

I don't remember if a 20x20 image is automaticaly turn to a power of 2 but
indeed it looks like this is the problem.

I think that we could consider in anycase a grid as a DEM or as a normal
species drawing that would avoid to deal with the "none power of 2"
textures.

But we have maybe to check in term of optimization how faster is it to draw
just the texture of the grid as a collection of cell.

**Comment by agrignard** [comment]
I don't know how to fix it excpet by displaying the grid as agent cells.

Indeed when using grid layer, if the size of the grid is not a power of 2 there is a problem.

here is a model to compare the two rendering:

model my_model

global schedules: my_grid + my_species{
float max_range <- 4.0;
init {
create my_species number:2;
}
}

grid my_grid width:20 height:20 neighbours:4 {
reflex update {
color <- #green;
}
}

species my_species skills:[moving] {
float speed <- 2.0;
reflex update {
do wander amplitude:20;

    ask my_grid at_distance(max_range)
    {
        if(self overlaps myself)
        {
            self.color <- #red;
        }
        else
        {
            self.color <- #yellow;
        }
    }

}
aspect default {
    draw circle(1);
}

}

experiment MyExperiment type: gui {
output {
display MyDisplayAsGrid type:opengl{
grid my_grid lines:#black;
species my_species aspect:default;
}

display MyDisplayAsCell type:opengl{
species my_grid ;
species my_species aspect:default;
}
}
}

**Comment by mazarsju** [comment]
Added in the documentation, in the new recipe "knownIssue". I close this issue
