### ISSUE TITLE
User control architecture, wrong focus

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1339]
In the model "Features/User Interaction/User Control Architecture", there are a lot of error of focus when trying to change the "Kill cells" number and the "create cells" number (Sorry I don't know how to explain better the problem, the behavior is so weird here…)

[EDIT] 4 tasks to handle:

- [x] Collision of variables of the same name in two different `user_command` in the same `user_panel`
- [x] Automatic focus can be an annoyance
- [x] Uncontrolled change of value of the input fields (-> `nil`)
- [x] Hovering state and number of clicks of buttons are incoherent

**Comment by AlexisDrogoul** [comment]
Difficult to understand what this issue is about. "Focus" on what ? In the dialogs ? In the text fields ? What are the consequences ? Can you try to explain it step by step (e.g.., "I click on … and then the focus is passed to … and I cannot enter text or whatever").

**Comment by mazarsju** [comment]
It's difficult to explain, the behaviour changes at each execution... Example of problem : 

- In advanced user control mode : 
I change the value "Kill cells" to 5, then the value "Create cells" to 1, when I click "Kill cells", only one cell will be destroyed instead of 5.
Then I relaunch the simulation, and the behaviour is totally different : 
I hover the 2 fields "Kill cells" and "Create cells", the two fields change their values to "nil".

The search field is focused with a simple mouse hover, that is not normal.

- In non advanced user control mode, I have to quit the mouse focus of the button "Kill one cell" and regain the focus for each click. A double / triple click on the button will activate the function only once.

**Comment by AlexisDrogoul** [comment]
OK. Regarding the different "problems":

1) There seems to be a bug with the scope/definition of variables in `user_panel`. Although the two variables `number` normally belong to two different `user_command`, there seem to be one and only one `number` shared between the two. I am able to replicate this, and will try to fix it soon.

2) All the input fiels in GAMA are focused when hovered. It is the case in the parameters, preferences, monitors, etc. There is no different behaviors here.

3) I cannot reproduce the change to `nil`. However, it looks like Issue #1248, which was supposedly only reproducible on MacOS X. If you have the possibility to make a test case or (better) a video showing it, it would be nice.

4) As for the last point, it's true that the focus remains on the button after it has been clicked and the mouse has left it. However, there is no need to leave the button to click again. And it's true that several clicks do not translate into several actions. I can reproduce it as well, and I will try to find a solution (probably launching the action within a thread rather than directly).

Alexis

**Comment by AlexisDrogoul** [comment]
Some updates:
1) Not yet fixed, but I will do it.
2) I removed (temporarily ?) the automatic keyboard focus when hovering. To validate a value, the user now has either to give the focus to another component (a bit annoying when you have only one…) or press enter (annoying when you have a button that captures this, like in the Preferences view). I vastly prefer the original solution, where just moving the mouse out of the component automatically validated it. However, maybe it's making things easier on Windows.
3) I have fixed Issue #1248. This may have eliminated your bug.
4) There seems to be an issue where (a) the hovering is lost when there is an AWT Java2D view open. It happens everywhere and not only in the user control panel. I've opened issue #1353 for this problem; (b) several clicks are not translated into several actions in the FlatButton event listener. I will try to change this immediately.
