### ISSUE TITLE
Network plugin

### ISSUE THREAD

**Issue by gnoubi** [gama-platform/gama#1343]
Communicator plugin don't serialize gama object (map, point, ...). Only string could be sent through the network with the current version of gama. New xstream converter should be developed.

**Comment by AlexisDrogoul** [comment]
Does it concern version 1.6.1 ? Version 1.7 ? Aside of this, have you tried to serialize the values in 1.7 using the new serialize() method ? It is the one used to display values in the UI as strings. 

And how is the XStream converter(s) supposed to be attached to GAMA ? In a plugin ? Or does it require some sort of intervention in the classes concerned ?

**Comment by gnoubi** [comment]
It concerns 1.7. Thanks for the advice, I may user this method. XStream converters must be associated to the plugin. No modification in core and application plugins is required.

nicolas
 
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by AlexisDrogoul** [comment]
What is the state of this development ? Does it work now ?

**Comment by gnoubi** [comment]
Hi, 

if serialize plugin is achieved, it should work. I can test today

nicolas
-- 
Nicolas Marilleau
UMI 209 UMMISCO Institut de Recherche pour le Développement
Chercheur invité DISC/ Femto-ST Université de Franche-Comté

32 rue Henri Varagnat
93143 Bondy Cedex
tel : 01.48.02.79.01
mobile : 06.88.33.49.06

**Comment by benoitgaudou** [comment]
Hi Nico,

The sérialization is about to work ...
It should work for simple agents only right now.

Benoit

2016-01-28 10:08 GMT+01:00 gnoubi <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Hi,

In the current codebase, we have two plugins (`ummisco.gama.communicator` & `dream.gama.opengis`) that, although they were targeted at different goals, now share a lot of things and enable simulations (and agents) to talk to each other  using sockets. The `socket` skill in the second one and the `network` skill in the first one are very close, and it is evidently our interest to merge them, or at lease to combine them. 

`socket` is more low-level (in that it does not include the possibility of serialization) and, from what I've seen, it works remarkably well for client-server setups. `network`on the other hand, relies on the serialization of objects using xstreams (which is at the base of the serialization plugin too) -- which can be a great benefit the day it will work for any GAML data structure. 

I propose to merge the two skills into one and only one, with a very simple syntax (and, if possible, a syntax compatible with the GAML way of handling composed words, not the Java way, with `sendMessage`, etc. !!) and procedure. 

Basically, we need:

- a `connect` action that allows to specify the IP number and port. 
- a non-blocking (i.e. threaded) `listen` action that fills a message box with all the messages received through the socket(s) it is listening to.
- a `message_box` (or `messages`) attributes that contain the list of messages and can be tested for emptiness, etc.
- a `send` action that can send messages over the connection. 
- plus various facets and/or attributes to specify things like timeout, the id of the agent on the net, protocol, maybe, etc.

One thing common to the two plugins is the absence of any structure for the messages. I find it problematic and my opinion is that we should (even if it implies to refactor it a bit) rely on the type `message` introduced by the FIPA plugin. The structure of these messages is really simple (and does not force agents to use FIPA, by the way),  and it would ensure a much better coherence between intra/inter simulation communications (and also allow, maybe, GAMA to become interoperable with other FIPA compliant platforms -- but it is not a goal for the moment).

@gnoubi , @hqnghi88 , @dphilippon : can you take the opportunity of the Coding Camp to build this "unified" plugin, so that we can make it a core plugin in the next release ? Can you also verify the libraries loaded (there seems to be tens of them, are they all necessary) ? And, most importantly, could you write examples that can be run on a network but also be demonstrated locally, for example between two simulations on the same GAMA instance or in 2 different instances ?

**Comment by AlexisDrogoul** [comment]
So, what is the state of the plugin ? Is it ready to be distributed along GAMA 1.7 ? And are the examples clean and sufficiently easy to run ?

**Comment by hqnghi88** [comment]
Dear Alexis,
At the end of CC, the structure had changed and now, I am working on my part. I'll push it in a few hours.

**Comment by agrignard** [comment]
Well I don't know what is the state of this. 

I know that at some point udp, tcp and mqtt were working (in the 5th day of the coding camp), then the big refactorisation to unify everything started on the last day of the coding camp and...???

**Comment by gnoubi** [comment]
Hi

Mqtt works, udp and tcp I don t know but at the end of of the week may I give you more information
Nicolas 


Envoyé de mon iPhone

**Comment by agrignard** [comment]
Hi all,

Some update on this. @gnoubi did a good work on the implementation and it seems that now everything is compiling. I mean all the .gaml model are green which is a first step.

But there is a but...

1.Many model crash at runtime or does not do the job.

So I was thinking in a generic way to test this but as I did not implemented those network I am not sure I am the right person to write the specification but this is the good place to start

The example in the library are basically UDP/TCP and MQQT folder example that should all do the same:

-one model is sending a message and another is recieving this message.

So what about having 2 models in each folder
one sender on reciever
- the sender.gaml wold be something like:
species NetworkingAgent skills:[network]{
reflex send
{
	  do send to: id contents: "message;
}


and 

the reciever.gaml
species NetworkingAgent skills:[network]{
	reflex recieve	{
	}
}

**Comment by agrignard** [comment]
Easy install:

add the 2 plugins (network and serialize) in the feature.xml
of ummisco.gama.feature.core.extensions

**Comment by AlexisDrogoul** [comment]
Some problems are still reported for this plugin. What is extacly the state ? It would be nice to have a clear view on whether it can be included or not in the release... In the meantime, I close this issue and merge it with #2041
