### ISSUE TITLE
Monitor view, parameters view [...] appear in the wrong place

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1368]
Monitor view appears as a tab of the gaml editor... cf image

![monitorview](https://cloud.githubusercontent.com/assets/12977635/12167722/69b3b17a-b560-11e5-896e-cc61f4e6f388.png)

**Comment by mazarsju** [comment]
(and monitor view does not appears by default when a monitor is defined in the model)

**Comment by mazarsju** [comment]
Same problem for "Parameters" view, and maybe other

**Comment by AlexisDrogoul** [comment]
In which context / use case does it manifest itself: immediately after opening GAMA, after a while, when running models from the Modeling perspective or the Simulation perspective, after a special event (crash, relaunch, force quit) ? If you can describe the process which leads to this strange situation (i.e. simulation views are apparently in the Modeling perspective — which is why their placement is messed up), I could try to reproduce it.

**Comment by mazarsju** [comment]
Ok my mistake, I had some compilation error in my project, had to do a "clean up".
