### ISSUE TITLE
Cannot reopen a project that has been closed

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1379]
When we close a project (by right clicking on the project / close project), the project disappear completely from the project navigation. And it is impossible to re-import it again, because it is seen as an already imported project.

**Comment by AlexisDrogoul** [comment]
I guess the solutions are either to :

- [ ] forbid the user to close projects (by removing the corresponding menu entries). The 'closed' status of a project is quite ambiguous in my opinion.
- [ ] let closed projects be visible (and accessible) in the UI, which probably means removing somewhere a test on whether the project is accessible or not (in the navigator content provider) — but, also, on the contrary, adding this test to other operations (like creating new models, etc.)

What's your opinion on this ?

**Comment by mazarsju** [comment]
In the 1.61, the second solution was working well, so I'm more up to stick into this solution.

**Comment by AlexisDrogoul** [comment]
Well, the situation of GAMA 1.6.1 was a bit more complex. It was possible to close projects everywhere, but this ended up in 2 different situations:

- in the Models library, the project would disappear from the list. This was actually normal, as we rely on a resource (metadata) *within* the project to classify it under this library. However, an update on the library would make it appear again (as all projects were 'forced' to reopen in order to read this property).
- On the contrary, in the User library, the project would still be there, accessible from the UI (and reopenable).

In GAMA 1.7, the situation will be more or less the same once we remove the checks on 'accessibility' on the projects. And it is a bit confusing, in my opinion. One thing I could try to do is to forbid (by directly handling the operation and explicitly warning the user about this interdiction) closing projects in the plugins/library models folders, while allowing it in the user models folder.

**Comment by mazarsju** [comment]
Let's forbid to close models from the model library / plugin models, and allowing to close models from the user models (but the model closed has to stay in the tree structure, so that we can re-open it !)

**Comment by AlexisDrogoul** [comment]
OK. I found a solution to keep the closed projects within our 3 libraries. A bit of a hack, but it works.
