### ISSUE TITLE
Questions about "inspect" statement

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1380]
About the "inspect" statement, I was wondering if the type value "display_population" and "species" were functional (and if yes, how to use them, because for me they do not work). The "table" type and the "agent" type work well, and I think that it may be enough, isn't it ?

**Comment by mazarsju** [comment]
About "inspect" statement again, I don't understand why the "value" facet is optional. For me, it must be mandatory.

**Comment by AlexisDrogoul** [comment]
I think we can effectively get rid of the `species` and `display_population` types. I just committed the change.

Regarding the `values:` facet, it is optional because the default facet (originally the name) can be used to indicate what to inspect or browse, without giving a title, e.g. 

`inspect one_of(species1);`
`browse species1`;
