### ISSUE TITLE
GAMA turns to non-usable state after trying to inspect a large number of agents

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1381]
In case of the user asks GAMA to inspect a large number of agents (by mistake), GAMA takes a long time to render what he wants, which can lead him to wildly close the application. In that case, the application turns to a non-usable state (at least in Windows, from the git version, from eclipse).

Here is how to proceed :

1) Run this simple model :

```
model new

global {
	
}

grid my_grid_species width: 10 height: 10 {
	
}

experiment my_experiment type:gui {
	output {
		inspect name:"my_inspector" value:my_grid_species; 
	}
}
```

2) Close the application before the end of the rendering (force it to stop)

3) Relaunch the application

==> Impossible to open a model, even after a clean of the project, or a restart of the computer. The only possibility to use GAMA again is to change the whole workspace.

**Comment by AlexisDrogoul** [comment]
I think the problem is more linked with the "force-quitting" of GAMA than with the inspection itself. It's unfortunate, but I dont think we can do anything on this matter, as Eclipse is subject to the same instability when the application is force-quitted. It's probably a problem of restoration of the workspace state. Do you have any log or error stack associated with this ?

**Comment by mazarsju** [comment]
Well, I don't know if it is a good or a bad news, but I cannot reproduce the bug anymore (although I could before lunchtime)... Seems like my computer needed a short break ^^. I close this issue.
