### ISSUE TITLE
Corrupted Icons in GAMA

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1427]
On a MacOSX, under El Capitan, in French, I have corrupted icons.
A workaround is to switch the System in English.

<img width="727" alt="capture d ecran 2016-01-18 a 19 16 17" src="https://cloud.githubusercontent.com/assets/1555274/12391173/4f871510-be18-11e5-9696-467bca3495c8.png">

**Comment by AlexisDrogoul** [comment]
This bug is documented for all RCP products under El Capitan. See these references:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479590
https://trac.filezilla-project.org/ticket/10669

These is nothing we can do now except using the workaround that consists in switching the language of the OS to English … 

I then close this issue.
