### ISSUE TITLE
clone a Project with git in GAMA

### ISSUE THREAD

**Issue by ElCep** [gama-platform/gama#1452]
Hi dear dev TEAM.
If you have time during this code sprint, it will be nice to be able to clone, commit and push any gama model repository in the interface (something like "import -> Project from SVN") . A nice option when you develop a model in cooperation mode !
Anyway thank you so much for this work!
E.

**Comment by AlexisDrogoul** [comment]
Assigned to Arnaud :)

**Comment by ElCep** [comment]
thank you very much :-)

**Comment by AlexisDrogoul** [comment]
Since GAMA is an RCP application, it *should* be possible to install EGit directly in it, like you would do in Eclipse — through the Install Software… menu (as it was the case in GAMA 1.6.1, for both SVN and GIT). We'll have to test this (probably @benoitgaudou ), but we will not release GAMA with Egit nor SVN.

**Comment by AlexisDrogoul** [comment]
I close this issue, as we will have a more general target for the beta: checking the addition of new (and various) plugins, including of course EGit.
