### ISSUE TITLE
Random values generated are not the same for each simulation (when running a multi-simulation model)

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1453]
cf title.

**Comment by AlexisDrogoul** [comment]
Yep. The seed and random number generator are defined at the experiment level. Since the four simulations share the same generator to generate random numbers, they effectively obtain different series… We will have to move down seed + rng to the simulation level, making a copy of what is defined at the experiment level (and letting the user / modeler change it, also).
