### ISSUE TITLE
Clean the `draw` statement

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1486]
This statement is a mess. It is probably the most used in GAMA, but it clearly fails in the category of 'try to guess the facets' statements.

- [x] remove `asset3D` (replaced by `texture`) and `bitmap` facets (not interesting)
- [x] remove `rotate3D` and allow `rotate` to accept both `point` and `pair<int, point>` values
- [x] eliminate deprecated facets (`geometry`, `shape`, `text`, `style`…)
- [x] better document the facets, esp. `scale`, unusable for file drawing (what to put ?)
- [ ] better document the various uses
- [x] allow `size` to pass a point (a bounding box) for 3D geometries, because `scale` has no meaning here
- [ ] make the `texture` facet usable in both Java2D (for images) and OpenGL.

**Comment by ptaillandier** [comment]
I totally second this enhancement.
Some remarks:
 * I have no idea of the purpose of the "scale" facet
 * for the 3D object files (and svg files), the size facet is used to define a bounding box. However, for the moment, only the sizes given as numbers are used: the bounding box is computed in order to keep the object/shape proportion and to scale the maximal size of the envelope of the object along the three dimensions (width, height and depth) to size. 
 * for the merging of the rotate/rotate3D facets, a good way to manage it is to consider that is the rotation vector is not given, the rotation vector is by default {0,0,1}.

**Comment by ptaillandier** [comment]
Two questions: 
 - should we keep the "scale" facet that is usable only for geometries or the size facet is enough?
 - I think we should change the name of the bitmap facet as this name is impossible to understand for modelers.... any idea?

**Comment by AlexisDrogoul** [comment]
I think we should remove `scale`. Drawing scaled geometries can be done using the `scaled_by` or `scaled_to` operators. 

We should also remove `bitmap`. This facet has no interest (it is used internally to draw the X, Y, Z, but the result is really not very nice).

**Comment by agrignard** [comment]
Quickly,
asset3D can be removed  without any problem (it was a first attempt for the obj/svg rendering)
the facet "scale" can (or might) also be removed. I guess we should only keep the facet "size"

**Comment by agrignard** [comment]
I do not agree for the bitmap, i think in some case it can be useful to
have the text always on the screen plane (exemple on the DEM drawing).
Maybe the name of the facet can be more explicit for the user.

**Comment by AlexisDrogoul** [comment]
OK. I agree that `bitmap` can be useful in some cases. However, to follow Patrick's suggestion, we should then give it a more understandable name, like for instance `perspective` (`perspective: true` would draw the text in 3D, `perspective: false` would draw it facing the user).

**Comment by AlexisDrogoul** [comment]
`perspective` is now replacing `bitmap` (which, while still usable, has been deprecated). The cleansing of `draw` is now more or less complete, so I will close this issue with the next commit.
