### ISSUE TITLE
1.7 rendering is different from the 1.6

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1519]
![screen shot 2016-02-02 at 17 17 07](https://cloud.githubusercontent.com/assets/3928502/12755669/aba82c62-c9d0-11e5-9072-c8cfa9ad61b2.png)
![screen shot 2016-02-02 at 17 17 27](https://cloud.githubusercontent.com/assets/3928502/12755668/aba0dafc-c9d0-11e5-837d-6325c8fbbf3c.png)

1. The black line contour are not there anymore
2. The lighting is different

**Comment by AlexisDrogoul** [comment]
Right. Are there preferences that could change the default lightning ? Because I havent touched this code. However, I would say that, on the first point, 1.7 is more faithful than 1.6.1 to the definition of the modeler, as no `border: true` or `border: #black` is defined to draw the shapes. So there is no reason to draw one.

The only problem is that plan and multiplan do not respect this rule, and neither do they respect the color of the border (when defined). Below, they draw their borders in black whereas I specified `border: #red` for 3D geometries, and they draw a border whereas none is specified for textured geometries.

<img width="736" alt="capture 2016-02-02 a 23 48 04" src="https://cloud.githubusercontent.com/assets/579256/12756692/6ef92050-ca07-11e5-9c24-04a6551e812d.PNG">

Moreover, specifying a border (`border: #blue`) for textured geometries does not change anything to the way they display: either no border is drawn, or the black border of plan and multiplan.

<img width="701" alt="capture 2016-02-02 a 23 51 19" src="https://cloud.githubusercontent.com/assets/579256/12756803/09e60452-ca08-11e5-9ffd-6abaf5b64e32.PNG">

**Comment by agrignard** [comment]
![screen shot 2016-02-02 at 17 58 49](https://cloud.githubusercontent.com/assets/3928502/12757012/7575e160-c9d6-11e5-8c48-a1324872895e.png)

**Comment by agrignard** [comment]
Ok I'll check that. however I think that by default we should draw the border no?

**Comment by agrignard** [comment]
or improved the lighting effect... it should look better than what we have now without bording.

**Comment by AlexisDrogoul** [comment]
One thing I dont get is why we can't have both `texture` and `border` … ?

**Comment by agrignard** [comment]
Well we could indeed... it was a choice (if you draw a textured geometry you only display the texture) but indeed once wants to draw the border...

 Should we enable it?

**Comment by AlexisDrogoul** [comment]
Actually, yes. If someone writes `draw shape texture: … border: … `, he/she is more or less expecting to have both. The same goes with the `color` facet, by the way, although it is a bit more complicated (but maybe, when both `color` and `texture` are provided, we could draw the faces colored, and then apply the texture with an alpha of 0.8 or something like this).

**Comment by agrignard** [comment]
what about this
![screen shot 2016-02-02 at 20 48 26](https://cloud.githubusercontent.com/assets/3928502/12762139/13cb739a-c9ee-11e5-8dd3-38a8b6442366.png)

Border can now be specified for textured Geometry.

By default it draws a yellow border. it the user wants a clean texture he has to set border:false

ok?

**Comment by AlexisDrogoul** [comment]
Woa ! Nice and fast ! However, when you talk about the "yellow" border, it's because it is the default color for agents, right ? (in the Preferences). Not something you hard-coded ?

**Comment by agrignard** [comment]
yep because of the default color. 

by default border is true so it draws it in yellow. if the user specify the border color it works and if the user does not want a border it has to specify border:false 

(I would prefer to have by default no border in texture or at least a black one...)

**Comment by AlexisDrogoul** [comment]
Actually, it would be ok for me too (and logical): if we dont specify a border, we dont get one.

**Comment by AlexisDrogoul** [comment]
And what about the lightning ?

**Comment by agrignard** [comment]
well I don't understand what happens. I did not touch anything in the lightning...

**Comment by agrignard** [comment]
Concerning the lighting we should just change that
	private Color diffuseColor = new GamaColor(100, 100, 100, 255);
in LayeredDisplayData.java line 52

For a mysterious reason I have a "Dirty_work Tree" when I try to pull so I do not manage to commit..

@Alexis just to be sure is it possible that the default value to 10 has been put by mistake when refactoring everything and creating the LayeredDisplayData? Can you fix it and commit it?
