### ISSUE TITLE
Display optimization: draw only the agents located on screen

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1521]
For the moment, at each simulation step, all the agents of each layer are redrawn (except for static layers with refresh: false). This means that even is the user zooms on a small part of the world, the display will be as slow as if all the agents are visible.

One possible optimization that could be tested is to try to redraw only the agents of which the geometry overlaps the current camera view.

This optimization should stay an option (and not be set by default) as it has several drawbacks:
  - if the agent display (aspect) is very different to its shape, some agents could be forgotten in the display  
- will be less efficient than the current way of displaying agents if all the agents are visible.
- if the user puts the simulation to pause and zoom out, we have to redraw all the missing agents.

**Comment by AlexisDrogoul** [comment]
It is an interesting idea. I've already tried to push as much as possible of computations to the OpenGL / Java2D part by delocalizing the creation of images, and putting as much as possible caches into action (although it could be improved in some places, esp. in Java2D), but it's true that a lot of computation still takes place, sometimes for nothing, in the Scope/Thread of the simulation.

An implementation of this could be:

- [ ] to add to IGraphics a method called getVisibleWorldEnvelope(), which would return an Envelope3D of the "visible" part of the world in model units.
- [ ] to check, in FileExecuter, ShapeExecuter and TextExecuter, whether what should be displayed intersects (or not) this envelope and, if it does not, to not "push it" to the IGraphics implementation. This would leave a bit of computation to the simulation thread (like computing the shapes, etc.) but, in all 3 cases (with maybe a little extra effort for texts, but it might be possible to obtain their size), it would avoid the creation of multiple objects (Java2D shapes, BufferedImages, AbstractObjects, etc.) and probably save a lot of time. Since we would only deal, here, with intersections of envelopes (the world one and the envelope we can obtain from the shapes + their location, or the files + their location + their desired size), there would be almost no performance penalty. This would solve the 2 first problems.
- [ ] the last problem you mention would only happen when: (1) the user zooms out and (2) not all the world is visible on screen. In all other cases, either the world is already visible and zooming in or out won't change what is displayed, or it is partially visible and the user zooms in, which does not require recomputing things. (3) the user drags the display. In these cases, we need in a way or another to force a recomputation of the display for the "missing" agents. It is not unfeasible, but my concern is about the unavoidable "lag" that will happen.

Any other idea ?

**Comment by AlexisDrogoul** [comment]
There was of course one complication: the region visible on screen depends also on the position/size of the layer.

However, I have implemented a solution that seems to work quite well (only for geometries for the moment, as a proof of concept. You can see below 3 screens. On the 1st one, a set of ants are displayed with a circle; I move the display to be partially out of the view and I step the simulation once (2nd screen); finally, on the 3rd one I move back the screen: you can see that the circles (only geometries to be displayed, the ants being an SVG file) that were invisible have not been displayed.

There are of course numerous things to improve:

- [ ] the computation of the envelope is currently made at each step, for each geometry, which is absolutely not optimal (and creates some glitches in OpenGL displays). It needs to be cached and invalidated according to the zoom, the movement of the display, the focus, as well as the resizing & collapsing of the view. 

- [ ] these different events themselves need to trigger a redisplay if we are in one of the cases mentioned in the previous comment. The problem is that we should not trigger too many events. It is not a problem for Java2D displays, as the repainting/redisplay of the agents is already triggered by resize/zoom/move events, but it might be in the OpenGL world. We have to be aware of this.

- [ ] There might be a problem with static layers (`refresh: false` layers) if the simulation begins in a focused state (i.e. the static layer is not entirely visible). One solution is to always force them to display all their agents (as they are normally only displayed once).

Some of these things are not completely trivial, so do not expect too fast progresses on this enhancement. However, it's nice to see that it works ! 

<img width="522" alt="capture 2016-02-04 a 15 53 37" src="https://cloud.githubusercontent.com/assets/579256/12810680/496cfe5c-cb5a-11e5-9429-87c3987233d6.PNG">
<img width="535" alt="capture 2016-02-04 a 15 53 53" src="https://cloud.githubusercontent.com/assets/579256/12810682/49d070ae-cb5a-11e5-9717-c46be441dc4c.PNG">
<img width="527" alt="capture 2016-02-04 a 15 54 08" src="https://cloud.githubusercontent.com/assets/579256/12810681/49c99f72-cb5a-11e5-8e20-ab4e632338fa.PNG">

**Comment by AlexisDrogoul** [comment]
OK. Given the fact that it gives surprisingly good results, I have decided to commit the changes in order for everyone ( @gama-platform/committers @gama-platform/core ) to make tests and decide whether we should keep this or not. Notice that it should only affect the zoom-out and pan in OpenGL when the simulation is paused (or when the steps are very long).

I have added a preference, set to false by default. To test the change, you have to set it to true.
<img width="910" alt="capture 2016-02-04 a 18 16 08" src="https://cloud.githubusercontent.com/assets/579256/12813663/03bd01a6-cb6c-11e5-9e11-c141dfe73d8e.PNG">

(see below, the same 3 steps than in the previous comment, on a different model: only a portion of the building are effectively redrawn, which probably saves a lot of computation in OpenGL — not sure it changes anything in the main output/simulation process, however)
<img width="817" alt="capture 2016-02-04 a 18 07 46" src="https://cloud.githubusercontent.com/assets/579256/12813682/288dc4f2-cb6c-11e5-827e-7a6d50821808.PNG">
<img width="823" alt="capture 2016-02-04 a 18 08 08" src="https://cloud.githubusercontent.com/assets/579256/12813683/2930eca4-cb6c-11e5-8d82-f46712accb8d.PNG">
<img width="831" alt="capture 2016-02-04 a 18 08 51" src="https://cloud.githubusercontent.com/assets/579256/12813684/2936025c-cb6c-11e5-80f9-fd117fea588c.PNG">

**Comment by agrignard** [comment]
Interesting!!
