### ISSUE TITLE
Camera position for OpenGL displays

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1554]
It was an old subject, but I can't see any trace of it, so I post it again :

I think it would be fine to change the default position of the camera for openGL displays, to turn it as in this following image : 

![image](https://cloud.githubusercontent.com/assets/12977635/13102393/951e934e-d580-11e5-892d-1b12c645ee82.png)

This will help a lot for the issue #1552. If the user still wants the view upside down (as it is now), he can do it easily with a mechanism explained for the issue #1553.

**Comment by agrignard** [comment]
I think that should be an option (facet of the display cf #1553) rather than the position by default. Remember that in the ideal world opengl could be the default display and could repalce java2D. If it was the case, all the model 2D or 3D would be displayed in Opengl. which means that a model in opengl  is not necessarily a 3D model and once wants to see it #fromTop by default.

**Comment by mazarsju** [comment]
Mmm... I see... 
Well, at least if you can tell me quickly how to do change the default position for OpenGL displays for the #1552 (without commit/push, just a local temporary modification), it would be awesome ;)

**Comment by AlexisDrogoul** [comment]
Again, this will translate into something wrapped up in the fix of Issue #579 — Once we have a set of predefined / user-defined cameras, nothing prevents us from having a global preference where the user would indicate which camera he/she would like as a default...

**Comment by agrignard** [comment]
@mazarsju As far as I remember you can modify the initial position in resetCamera() method in CameraArcBall.java

**Comment by mazarsju** [comment]
Ok nice, works perfectly, thanks ! I close this issue then, now a bit redundant with #579 and #1553.
