### ISSUE TITLE
Graphics positionning not consistent with other positions + bugging with negative values

### ISSUE THREAD

**Issue by RCura** [gama-platform/gama#1555]
There's a small bug (I think ???) with the positioning system of graphics layers.
In the documentation, all the layers are positionned with {0,0} as upper-left., and {0.5,0.5} as center.

With `graphics`, **{0,0} is in the middle of the world**. Not a big trouble though, even if it's still unconsistent with other layers.

```
graphics "Annee" position: {0.0,0.0} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
```

<img src="https://cloud.githubusercontent.com/assets/807703/13114716/01227ed4-d595-11e5-88c6-7e2fa4f4edfa.png" width=200 height=200/> 

{0.1,0} is center + 10% to the right, and {0,0.1} is center + 10% to the bottom

```
graphics "Annee" position: {0.1,0.0} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
graphics "Annee" position: {0.0,0.1} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
```

<img src="https://cloud.githubusercontent.com/assets/807703/13114773/395e6402-d595-11e5-9025-807948cedecf.png" width=200 height=200/> <img src="https://cloud.githubusercontent.com/assets/807703/13114775/3bbde15a-d595-11e5-9509-4c6830cfb156.png" width=200 height=200/> 

But I want my label in bottom-left.
So, using {-0.1,0} or {0.0,-0.1} should work to got toward left / bottom, but it doesn't :

```
graphics "Annee" position: {-(0.1),0.0} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
graphics "Annee" position: {0.0,-(0.1)} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
```

<img src="https://cloud.githubusercontent.com/assets/807703/13114930/fc906baa-d595-11e5-810b-bc16496c08ae.png" width=200 height=200/> <img src="https://cloud.githubusercontent.com/assets/807703/13114932/fdb75eb2-d595-11e5-9207-e8d1b3a31697.png" width=200 height=200/>

My guess is that, as for [charts](https://github.com/gama-platform/gama/wiki/G__DefiningChartLayers#chart-type) :

> position optional, expects a point - position of the upper-left corner of the layer. Note that if coordinates are in [0,1[, the position is relative to the size of the environment (e.g. {0.5,0.5} refers to the middle of the display) whereas it is absolute when coordinates are greter than 1.

So, it probably considers -0.1 as not relative coordinates. And thus, the text goes nowhere.

Could you fix this please by correction the `graphics position:` behaviour to the same as `chart position:` ?

**Comment by AlexisDrogoul** [comment]
Actually, this is a little bit more complex than that. The `graphics` layers are (more or less literally) "aspects" of the world. So the reference agent for drawing text, images or shapes is the world itself, which means that all coordinates are interpreted with respect to its location, which is in the middle of the screen (the world's shape is a rectangle and its location is its center).

What does it mean ? 

When you write ` draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;`, the location of this text will be (by default) the location of the reference agent, i.e. the middle of the surface determined by the layer position and size, and not `{0, 0}`. This explains your three first statements: the text is always drawn in the middle of the layer, and it is the layer that you are moving.

Now, about the negative values of the position, we come to a kind of issue (or let's call it an undocumented choice). Actually, whereas the positive values are interpreted as relative to the top-left corner of the screen (i.e. `position: {0.1, 0.1}` will move the layer right and down by 10% of the width and height), negative values are interpreted as relative to, respectively the extent of the screen in width and the extent in height. In that respect, `position: {-0.1, 0}` will then be equivalent to `position: {0.9, 0}`, which explains why you dont see any text: the layer is almost completely shifted to the right (or to the bottom) of the screen, and your text (still in the middle of it) is drawn in a non-visible portion of the screen (at least in Java2D; you would however see it on an OpenGL display since it accepts to draw out-of-screen elements).

So, to come back to your issue, there are two choices:

1) We keep the current way of interpreting negative values, and, in that case, your only choice (since you cannot offset the layer to the left and the top), is to specify a location in the draw statement (e.g., something like  `draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") at: {0, world.shape.height - 50 #px};`)

2) We change the way negative values are interpreted, by allowing negative offsets of the layers when negative positions are specified, which would allow you to write something like (the layer being moved by -50% to the left and 40% to the bottom to account for the default location of the text): 

```
graphics "Annee" position: {-0.5,0.4} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
```

And whatever the solution we choose, we need to document it !

**Comment by AlexisDrogoul** [comment]
Actually, this is a little bit more complex than that. The `graphics` layers are (more or less literally) "aspects" of the world. So the reference agent for drawing text, images or shapes is the world itself, which means that all coordinates are interpreted with respect to its location, which is in the middle of the screen (the world's shape is a rectangle and its location is its center).

What does it mean ? 

When you write ` draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;`, the location of this text will be (by default) the location of the reference agent, i.e. the middle of the surface determined by the layer position and size, and not `{0, 0}`. This explains your three first statements: the text is always drawn in the middle of the layer, and it is the layer that you are moving.

Now, about the negative values of the position, we come to a kind of issue (or let's call it an undocumented choice). Actually, whereas the positive values are interpreted as relative to the top-left corner of the screen (i.e. `position: {0.1, 0.1}` will move the layer right and down by 10% of the width and height), negative values are interpreted as relative to, respectively the extent of the screen in width and the extent in height. In that respect, `position: {-0.1, 0}` will then be equivalent to `position: {0.9, 0}`, which explains why you dont see any text: the layer is almost completely shifted to the right (or to the bottom) of the screen, and your text (still in the middle of it) is drawn in a non-visible portion of the screen (at least in Java2D; you would however see it on an OpenGL display since it accepts to draw out-of-screen elements).

So, to come back to your issue, there are two choices:

1) We keep the current way of interpreting negative values, and, in that case, your only choice (since you cannot offset the layer to the left and the top), is to specify a location in the draw statement (e.g., something like  `draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") at: {0, world.shape.height - 50 #px};`)

2) We change the way negative values are interpreted, by allowing negative offsets of the layers when negative positions are specified, which would allow you to write something like (the layer being moved by -50% to the left and 40% to the bottom to account for the default location of the text): 

```
graphics "Annee" position: {-0.5,0.4} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") ;
}
```

And whatever the solution we choose, we need to document it !

**Comment by RCura** [comment]
I think the second solution would be the best :) As to not mess-up with potential existing users taking usage of the negatives (out of bounds) positionning, this could be a test of 0 <= abs(x,y) <= 1

Thanks for the follow-up anyway :smile:

**Comment by AlexisDrogoul** [comment]
I forgot to mention the third solution, which does not involve any change: 

3) Use both position and location for the greatest flexibility: 

```
graphics "Annee" position: {0,0.9} {
             draw string(Annee) font: font("Helvetica", 32, #bold) color: rgb("black") at: {0,0} ;
}
```

and probably the most elegant too…

**Comment by AlexisDrogoul** [comment]
Given that the workaround provided in the last comment is probably the most elegant to solve this "problem" (actually it is -- should be -- a feature) and  does not involve any change at all (only a bit of documentation on negative coordinates of layers), I close this issue. Feel free to reopen it if you feel it is necessary to change things.
