### ISSUE TITLE
Multi-level model.... very weird behavior (and GAMA does not like it)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1580]
You can test the following model....very weird result expected.....
```
model multilevel
global {
	init {
		create normal_ag number: 10;
		create macro_ag with:[shape::shape];
	}
}

species normal_ag ;

species macro_ag {
	species micro_ag parent: normal_ag;
	reflex capture_agents {
		write name + " -> " + (normal_ag collect dead(each));
		capture (2 among (normal_ag overlapping self)) as: micro_ag;
	}
}

experiment multilevel type: gui ;
```

**Comment by AlexisDrogoul** [comment]
OK. So can you elaborate on the weirdness and the "GAMA does not like it" ? 

When running the model, what is "weird" is that all the agents are captured in one pass (which itself results in the execution of the reflex `capture_agents` several times… by the same agent)

When trying to reload (or dispose) the model, we obtain a stack overflow (on reading the attributes of agents). 

Am I correct ?

**Comment by AlexisDrogoul** [comment]
Got it. This is due to `create macro_ag with:[shape::shape];` and the "enhancement" of #1558 .

All the world's attributes (including its sub-populations !) were copied into the attributes of macro_agent, resulting in this infinite loop (and strange behavior), as one step of the world would result in the macro_agent being stepped, then stepping itself again, and again…

This raises the question on whether we should revert #1558 or not as, once they have been loaded (for example from a shapefile), it is a bit complicated to know which attributes are belonging to the shape itself and which ones are belonging to the agent…

**Comment by AlexisDrogoul** [comment]
I've reverted the policy regarding shapes attributes. Now, only the geometrical (internal) attributes are being copied. This means that `read` or `get` will only work in the scope of a `create` (i.e. the attributes copied from GIS files will not be available after). This fixes the issue as well as another one where the memory used was a bit too important when reading large shape files.
