### ISSUE TITLE
NullPointerException when running processor

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1583]
When I make a clean of the eclipse project, I have a NullPointerException in the class DocProcessorAnnotations, method "getConstantElt" : ((VariableElement)e).getConstantValue() returns null...
Maybe it's my fault, because I made some changes in the processor today, but I really don't know what... Do you have the same error ?

**Comment by AlexisDrogoul** [comment]
Same here since the last commit.

**Comment by mazarsju** [comment]
That is very weird, and very annoying also... I reverted my repo to an old version (before all the changes I did in the processor), and the same error occurs... I even did a clean up, a refresh of all the projects, built again the processor, nothing works... A sneaky update of eclipse maybe ?

A solution should be to write a test "if ((VariableElement)e).getConstantValue() != null", but I don't know what are the consequences...

**Comment by AlexisDrogoul** [comment]
Actually, this occurs in the doc processor, and I’m a bit surprised it occurs here (i.e. are we supposed to process the doc everytime ?). 

It is, however, harmful for running GAMA.
> Le 25 févr. 2016 à 19:31, mazarsju <notifications@github.com> a écrit :
> 
> That is very weird, and very annoying also... I reverted my repo to an old version (before all the changes I did in the processor), and the same error occurs... I even did a clean up, a refresh of all the projects, built again the processor, nothing works... A sneaky update of eclipse maybe ?
> 
> A solution should be to write a test "if ((VariableElement)e).getConstantValue() != null", but I don't know what are the consequences...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Senior Researcher, UMI UMMISCO 209, IRD & UPMC, France.
--
alexis.drogoul@gmail.com | http://goo.gl/4ewFdJ
[Vietnam] +84915088155 [France] +33608698845
--
GAMA: http://gama-platform.org

**Comment by AlexisDrogoul** [comment]
Found it. The documentation of `getConstantValue()` states that `(it) returns the value of this variable if this is a final field initialized to a compile-time constant. Returns null otherwise. The value will be of a primitive type or a String.`. So it means any constant initialized with something else than a primitive type or a String will return null.

It was the case of the "pixels"/"px" constant. Its value was a `Double` (and not a `double`). Setting it to `double` removes the NPE. I have changed the comment of @constant accordingly.
