### ISSUE TITLE
Front java2D displays are not updated until they are resized/activated

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1594]
When running a simulation, if a display is java2D and is focused from the beginning (ex : one unique display java2d), the panel containing the display need to be resized to be updated.

**Comment by AlexisDrogoul** [comment]
OK. I take this one, at it's likely a consequence of recent Java2D commits. So only the front Java2D display is not refreshing, right ? And what happens if you have 2 java2D displays side by side (you launch the simulation with the two, which should be stacked first, then arrange them side by side, then relaunch the simulation) ?

**Comment by mazarsju** [comment]
No, the problem is still here with the patch...

**Comment by AlexisDrogoul** [comment]
I've committed a possible fix (tested under Windows 10). Can you try it ?

**Comment by mazarsju** [comment]
Yes, works fine now ! I close the issue.
