### ISSUE TITLE
user command does not work anymore in experiment

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1595]
When declaring a user command in the "experiment" scope, impossible to get the action from the model scope : in the java class "UserCommandStatement", `context.getAction(actionName)` returns null.

try this model : 

```
model quick_user_command_model

global {
    action createAgent
    {
        create my_species;
    }
}

species my_species {
    aspect base {
        draw circle(1) color:#blue;
    }
}

experiment expe type:gui {
    user_command cmd_inside_experiment action:createAgent;
    output {
        display my_display {
            species my_species aspect:base;
        }
    }
}
```

**Comment by AlexisDrogoul** [comment]
Well. It's more a change (undocumented and untested one) than a bug, as it's actually a consequence of the architectural changes in the kernel, where the ambiguity between what belongs to simulations and what belongs to experiments is progressively removed. 

So, yes, an "experiment action" belongs to experiments and not to simulations. It's also quite logical when you have several simulations (which one should run this action ?). So it is the responsibility of the developer to define this action in experiments. 

That said, there is definitely a bug in that the compiler does not warn against the absence of this action in experiments. 

Regarding a related matter (the accessibility of "simulation actions" from the UI, since they won't appear anymore directly in the parameter view), please file in another request for enhancement if you think it is important. A tab-based parameter view can probably be a solution (one tab per simulation, allowing also other focused interactions, like hiding the simulation views, etc.).

**Comment by AlexisDrogoul** [comment]
After some thought. 

Although, in your case (and if you have only one simulation), the correct(ed) syntax would be `user_command cmd_inside_experiment { ask simulation { do createAgent;}}`, it's true that this change completely breaks the compatibility with GAMA 1.6.1.

So I can propose an intermediate solution, which is to emit a warning if the action is not found in the experiment and explain in this warning that (if  it is found in the model, of course) it will be executed on all the simulations as a special case for keeping the compatibility, but that it should be better redefined in the experiment.
