### ISSUE TITLE
sum on an attribute of agents

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1599]
I had several times to compute the sum of an attributes of all the agents of a species.
I often do something like: 
sum(my_species accumulate(each.attribute)) 

It is often one the first operators that we introduce to students during training sessions. I was looking for a simpler way to write it, as the accumulate/collect are not so easy to get at first. So similarly to the count operator, what do you think of this syntax:

my_species sum(each.attribute)

Benoit

**Comment by AlexisDrogoul** [comment]
Why not.

But in that case, we need to generalize this, both in terms of operators and operands.

1) Operators:

sum, mul/product, mean, max, min, median, standard_deviation, geometric_mean, variance, mean_deviation

=> the problem is the ambiguity introduced, as, for instance, max and max_of would be basically the same (i.e. agents max_of each.attribute / agents max each.attribute).

So I propose to generalize the `_of` postfix (e.g., `my_species sum_of each.attribute`) to distinguish between iterators and "normal" operators. We would then add new iterators called: sum_of, mul_of/product_of, mean_of, max_of, min_of, median_of, standard_deviation_of, geometric_mean_of, variance_of, mean_deviation_of

2) Operands

as the existing iterators, we should not restrict it to list of agents, bu extends it t to containers of arbitrary objects. To be able to write, for example: `int mean_red <- colors mean_of each.red`).

**Comment by AlexisDrogoul** [comment]
I have added the more common (sum_of, product_of, mean_of, variance_of in addition to max_of & min_of). I leave to the ones interested the exercise of building the other ! :)
