### ISSUE TITLE
Alt + drag on MacOSX (and the equivalent on Windows) do not select anymore in OpenGL displays

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1645]
Alt+drag in an OpenGL display enabled the user to do a multi-selection of agents (drawing a rectangle) and to do a simple measure of the distance (cf. #1085 ). Since, probably, the fix for #1568 (or #1297 ?) it is not working anymore. The same goes for the one in Windows. Both do a simple translation in the XY plan. In addition, the text "d 0.0" (corresponding to the distance) is drawn on screen and cant be removed.

**Comment by mazarsju** [comment]
I have just made a quick fix, tell me if it is the behavior you expect.

I have several comments about this :
- When using mouse interaction, we use the "ctrl" button to do a rotation, and when using keyboard arrow interaction, we use the "shift" button to do a rotation. I don't understand this choice, according to me it is very not intuitive, so I put the same buttons for both mouse and arrow interaction (I chose "ctrl").
- I wonder if the ROI is really used : it only works in very specific case, when we are in the plan Z=0 (it was already the case with the old version).
- Maybe I miss the point here, but I don't understand what the ROI agent selection does (same for the old version, I never used this feature, I don't know how it works).
- There is a button in the interface openGL "use mouse to rotate", "use mouse to translate" that annoys me a bit... Is it really used ? Shall we remove it (in order to simplify both the code and the UI) ?

**Comment by AlexisDrogoul** [comment]
Well I dont know much about the key modifiers used in Windows/Ubuntu, but the whole seemed quite consistent for me on Mac. Now, I barely use the arrow keys. 

Of course we need to rationalize them (so that the same modifiers have the same effect on both mouse and arrows).

No problem for me (if it is documented) to remove the menu for switching between rotate/translate with the mouse.

The ROI is quite ugly at the moment, but potentially VERY useful. I will probably open a whole new issue (or we stay on this one). It works like in the movie below. I think this possibility to have a way to draw an area (in 2D or maybe 3D ?), to measure its size, and to select a whole set of agents is really interesting. 

Now, its limitations are mainly that it only works in 2D. Having the same in 3D would be awesome (but clearly too much work, not on the OpenGL side, but on the logic side of the display of agents: we dont record in OpenGL where each agent is drawn and so the ROI bases its calculation on the shape of the agents, which is not always true).


![screencast 2016-04-02 12-58-15](https://cloud.githubusercontent.com/assets/579256/14224808/92fa1acc-f8d3-11e5-99a4-340889e74b1f.gif)

**Comment by AlexisDrogoul** [comment]
The problem now is that, once ROI has been done once, GAMA does not revert to the normal "mouse for dragging" operation (i.e. the drag always triggers the ROI).

**Comment by mazarsju** [comment]
Here is a fix for this problem.
I don't know how it works on Mac, but in Windows, it's very difficult to get the popup you have on your gif, when you release the click for the selection... (by "difficult", I mean I have to do the all combinaison (press Alt + press click + move mouse + release click + release Alt) in a very short amount of time...)

**Comment by AlexisDrogoul** [comment]
Probably because the drag is disturbed in some way on WIndows ? On MacOSX, I can extend the drag without problem. Have you tried with the trackball ? I dont use a mouse.

**Comment by AlexisDrogoul** [comment]
I think, in any case, that we should rationalize all this:

CTRL (CMD on Mac) + arrows/mouse : 3D move
arrows/mouse without modifier: drag
SHIFT + arrows/mouse drag : select (ROI)

with just one problem with the 3D move with arrows (since we have only 2 directions: temporarily modify with ALT+CTRL to allow the third direction to be used with arrows ?).

**Comment by mazarsju** [comment]
How select (ROI) should work with arrows ? We need an initial position...

I don't understand the problem you mentioned about 3D move with arrow : with the mouse, you are exactly in the same case, having only 2 directions (mouse.x and mouse.y). The 3rd dimension can be assimilated to the zoom I think, and we have the possibility to control the zoom from a keyboard too.

**Comment by AlexisDrogoul** [comment]
Right.

So : 

CTRL (CMD on Mac) + arrows/mouse: 3D move
no modifier: drag
SHIFT + mouse: select (ROI)

That sounds good ! Any other comments by directly implicated people (e.g. @agrignard ) ?

**Comment by mazarsju** [comment]
In fact, in the actual code, there are :
- ALT + mouse for the "select ROI"
- SHIFT + mouse for the "zoom ROI"
Are you in favor to suppress the option "zoom ROI" then ?

**Comment by AlexisDrogoul** [comment]
Forgot about the "zoom" ROI (reminiscent of the zoom in the first incarnation of GAMA).

I would be in favor of exchanging the two, as shift is more popular for selecting than alt (in my opinion).

After it is done, I'll find a way to document this dynamically in the display (i.e. a small popup or menu to indicate the modifiers, etc.).

**Comment by mazarsju** [comment]
I just changed the ctrl and the alt. And the good news is that it fixes also the problem I had on Windows for the selection of agents :). Alt on windows seems to quit the current context, that's why the popup disappeared.

**Comment by AlexisDrogoul** [comment]
ctrl and alt or shift and alt ?

**Comment by mazarsju** [comment]
Sorry, I meant shift and alt

**Comment by agrignard** [comment]
It's a good thing to harmonize and simplify everything. I have always been surprised that all this options look so mysterious for some users like "oh, I did not know we can rotate the model" "oh you can select agent with an ROI??". So of course it has to be well documented but we could think (even if It will not simplify the UI) of kind of control panel like in QGIS, Sketchup ,etc to switch between different mode (dragging, selecting, etc) 

just a side for me the zoom ROI can be useful in big model to zoom on a precise place no instead of scrolling

**Comment by AlexisDrogoul** [comment]
This issue has been resolved -- some of its consequences are now part of new issues #1658 , #1659 , #1660 , #1661
