### ISSUE TITLE
Saving a string with comma into a CSV File doesn't have the expected output

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1690]
Test the following model which should normally save a string, with the different values for i added in the string at each step separated by a comma. You'll see that the CSV file doesn't have comma anymore but semi-colon ...

````

model errorCSV
global
{
	int i <- 1;
	string IString<-"";
	reflex update
	{
		if(cycle=0)
		{
			IString<-IString+i;
		}
		else
		{
			IString<-IString+","+i;
		}
		i<-i+1;
	}
	
	reflex doHalt when: cycle>40
	{
		save [IString] to: "testStringI.csv" type:"csv"; 
		do halt;
	}
}
experiment test type: gui
{
	
}
````

**Comment by AlexisDrogoul** [comment]
Basically, CSV files are "comma-separated values" files. Which means that every value should be separated by a comma. This is why, by default, when you save a string with commas in it, GAMA replace them with semi-colons (so that they are not truncated when re-reading the file).

However, in your case, it is a bit special, as you only save one value (one string), with commas in it. I dont know exactly what you're after, but if you wanted to save all the values of i, the correct way to do it would be to write your model like this:

```
model errorCSV
global
{
    int i <- 1;
    list<string> IString<-[];
    reflex update
    {
        IString<< string(i);
        i<-i+1;
    }

    reflex doHalt when: cycle>40
    {
        save IString to: "testStringI.csv" type:"csv"; 
        do pause;
    }
}
experiment test type: gui
{

}
```

**Comment by dphilippon** [comment]
Actually I already know about this, but the problem was in GAMA 1.6.1, I used this method to prevent the CSV to contains character like brackets. For instance, if I got the list [1,2,3], it will save [1 - 2 - 3] (with - indicating columns separations). I don't want to have brackets inside the CSV, so with the string, I "cheated" to get what I wanted and launch directly a R Script.

**Comment by AlexisDrogoul** [comment]
The change was introduced in #1352 . I dont clearly understand the "cheat" you were talking about, but the model I have presented above will save the values using comma as the separator (without brackets, etc.). If you really want to save exactly the string (without modification / rewriting), you can always use the "text" format (even if your file ends in "csv").

**Comment by dphilippon** [comment]
Okay, I close the issue then.
