### ISSUE TITLE
3D referential and rotation helper should not be affected by light

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1691]
Try to put a diffuse_light to 255, the 3D referential and the rotation helper appear white.

**Comment by AlexisDrogoul** [comment]
Hum, right. I removed the diffuse light in JTSDrawer as it had some weird effect when simultaneously drawing the ROI and the rotation helper. And I think the 3D referential never had any diffuse light defined.
Can you try adding them to the corresponding methods ? The problem is that we should not manipulate GL_LIGHT0 (which is used for the `diffuse_light` facet) but probably another one (GL_LIGHT1 ?), switching it on before drawing the referential, the sphere and the ROI, and switching it off after.

**Comment by mazarsju** [comment]
I didn't really understand your post but simply removing the light while drawing those 2 things does the trick.
