### ISSUE TITLE
Arcball sphere helper should not appear when doing a screenshot (Mac OS X)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1695]
On Mac OS, I really often use the cmd+shit+3/4 option to get a screenshot. I just see that now that we have the "arcball helper sphere" when we press cmd there's no way to get a clean screenshot. Ok there is a feature to get a screenshot in GAMA but the cmd+shift is really practical for mac os user, no?

**Comment by AlexisDrogoul** [comment]
I think that if the view has not the focus, ie if you click in another view
before, you will not get the sphere.

**Comment by agrignard** [comment]
right... well I guess this is enough to close this issue? 

BTW the idea of the sphere is good but I think it can be improve. For instance what does mean the radius of the current one? Shouldn't we draw the "real" arcball sphere (something that is around the model) like in the following picture (taken from GLC_Player) 
![screen shot 2016-04-20 at 15 02 16](https://cloud.githubusercontent.com/assets/3928502/14686918/e6286bf2-0708-11e6-8788-e33c51e23572.png)

**Comment by agrignard** [comment]
Also I would be in favor to keep the original referential and draw another one (like in the previous picture) at the center of the sphere, if found it a bit confusing to have this moving referential.

**Comment by AlexisDrogoul** [comment]
I've fixed the issue described in the first comment by requiring that the COMMAND/CTRL/SHIFT key is recognized only when the mouse is down, in order to keep mouse focus / keyboard focus on sync. This will avoid the problem of the sphere appearing during snapshots (and also other unwanted interactions between views).

For the look of the sphere/referential, this is mainly a matter of taste -- maybe you'd want to open another request for enhancement on this ?
