### ISSUE TITLE
Problem with step and clock status of the simulation

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1707]
Test the following model:
model steppb
global {
	float step <- 1#h;
	reflex test {
		write time;
	}
}
experiment main_test type: gui ;

The write variable has the right value, but the the clock status of the simulation (in the user interface) is wrong: it display each simulation step as 1 second whereas it should represent a hour in this model.

**Comment by hqnghi88** [comment]
Dear Patrick,
It display the clock of experiment, and the step in global belong to the simulation. It seem easy to change to simulation clock instead of Experiment clock but I am wonder if in case of multi-simulation, which step unit will we bring to display? or if we display the exact status in hover popup, corresponding with each simulation and keep the Experiment clock as now?
Cheers.

**Comment by ptaillandier** [comment]
Hi Nghi,

I don't know, but as most of users will not use multi-simulations (or will
use multi-simulations with the same step value), I think it is important to
at least display the right simulated duration in the interface.

Cheers,

2016-04-26 19:41 GMT+02:00 hqnghi88 <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
I think the clock of the experiment should not be displayed using time
units,  only steps. Then each simulation displays its own time status using
its own step.
