### ISSUE TITLE
Facet schedules not taken into account for global

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1708]
Maybe this is just a mistake from myself, but I don't understand the output of this short model : 

```
model new

global schedules:shuffle(my_species2+my_species){
	init {
		create my_species number:5;
		create my_species2 number:5;
	}
}

species my_species {
	reflex r {
		write name;
	}
}

species my_species2 {
	reflex r {
		write name;
	}
}

experiment my_experiment type:gui{
    output {
    }
}
```

The output of this model is : 
```
my_species0
my_species1
my_species2
my_species3
my_species4
my_species20
my_species21
my_species22
my_species23
my_species24
```
Instead of shuffle the 2 species... Is that normal ?

**Comment by AlexisDrogoul** [comment]
Right, there is a bug in the definition of SimulationPopulation, where it does not take anymore into account the "schedules" facet. 

Beside this, if you want to schedule the agents of the 2 species randomly, you also have to specify `schedules: []` in the species themselves, otherwise the agents will be scheduled twice (which is not against the specifications).

One workaround, for the moment, is to write the model this way:

```
model new

global {
    init {
        create my_species number:5;
        create my_species2 number:5;
    }
}

species scheduler schedules: shuffle((my_species2+my_species));

species my_species schedules: [] {
    reflex r {
        write name;
    }
}

species my_species2 schedules: [] {
    reflex r {
        write name;
    }
}

experiment my_experiment type:gui{
    output {
    }
}
```

Currently, we have the following behavior:

- the `world` (or the `simulation`) cannot be unscheduled
- `schedules` at the simulation level is not taken into account

We have 3 choices:

- either we restrict the usage of `schedules` to sub-species of the model (indicating that the "clean" way is to build a dedicated species) and we emit an error when it is defined in `global`.
- or we silently refactor the model by moving the definition of `schedules` to an automatically created sub-species (with no instances) and simply emit a warning to explain that it is deprecated in global. 
- or we keep the same behavior (still silently moving the definition of schedules) without indicating anything. Note that, in that case, the `world` can still not be unscheduled. As a matter of fact, it would be too complicated to do (not impossible, but complicated).

I guess the definition of `frequency` suffers the same bug, unfortunately (havent checked yet).

**Comment by AlexisDrogoul** [comment]
This is normally fixed (for both 'schedules' and 'frequency') by implementing the second option. Note that the world cannot be unscheduled anymore (always runs first). Maybe we should document this somewhere.
