### ISSUE TITLE
Enhance line drawing in Opengl

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1718]
In 3D the line drawing look so 90's!! 

The two main problems
![screen shot 2016-05-02 at 14 03 34](https://cloud.githubusercontent.com/assets/3928502/14962858/e25e4fcc-106e-11e6-9eb5-8a4969a0bb52.png)
 (that we can see on the following screenshot) are:
- Aliased line.
- Dotted line.

I already spend some time trying to fix that but in vain. I don't know exactly where it comes from, but I am sure there is a way to fix that using some opengl function and it would make the GAMA 3D rendering much more "serious"

**Comment by ptaillandier** [comment]
Hi,

Can you test to add these 3 lines in JOGLRenderer:

 cap.setSampleBuffers(true);
 cap.setAlphaBits(4);
 cap.setNumSamples(4);


For me, it seems to fix the anti-aliasing problem.


Cheers,


Patrick

2016-05-02 20:08 GMT+02:00 agrignard <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
On my configuration, it worsens the problem if I simultaneously enable GL_LINE_SMOOTH. Without smoothing lines, it is effectively better. So the problem is not really about drawing the lines, but about the alpha blending. Lines that do not interfere with a polygon (like the roads, for instance, in the road traffic model) are not jagged.

The problem of these capabilities applied the profile is that they sometimes are not available. To be perfect, we should follow one of the guides available on the web (e.g. http://www.codeproject.com/Articles/199525/Drawing-nearly-perfect-D-line-segments-in-OpenGL)

But, in any case, your capabilities, combined with the disablement of GL_LINE_SMOOTH, clearly work on my configuration. If so, we can include them -- and close the issue for now on.

**Comment by AlexisDrogoul** [comment]
Nevermind. I made the changes already. Please test !

**Comment by agrignard** [comment]
well done @ptaillandier. It seems much more better with those 3 lines!! 

@AlexisDrogoul I did not have to change the Smooth Line and it seems ok. Which one are you speaking about? This one GLUtilLight.enableSmooth(gl); line 213? or another one?

**Comment by AlexisDrogoul** [comment]
Actually, I was playing with different values of GL_LINE_SMOOTH and GL_LINE_SMOOTH_HINT to see if any improvement could be obtained. But setting these options worsen the rendering (and actually slow it). I think we can fix this issue, no ?

**Comment by agrignard** [comment]
yes that was a quick issue! Open one hour ago already fix. I'll try to see if there are some impact on  other rendering. I did not get exactly the point of the SampleBuffers but it does the work!
