### ISSUE TITLE
Allow bi-linear filtering for textures in OpenGL Displays

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1720]
I could be nice to have the possibility to use a bi(tri?)-linear filtering for textures in OpenGL Displays.

**Comment by AlexisDrogoul** [comment]
In OpenGL, bi-linear filtering is called by passing `GL_LINEAR` to `GL_TEXTURE_MAG_FILTER` and `GL_TEXTURE_MIN_FILTER` when building the texture, and tri-linear filtering is actually a blending between the bi-linear filtering performed on the different mipmaps (i.e. the images produced at different sizes of the same texture). It is called by doing something like this:

```
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER,
GL_LINEAR_MIPMAP_LINEAR);
```

GL_LINEAR (bi-filtering) is already invoked when anti-aliasing is on. Tri-linear is not because it is costly. Do you have a concrete example of what it would change ? I've made some tests and I dont see a lot of differences even when zooming in and out.

**Comment by ptaillandier** [comment]
Ok, I did not know that bi-filtering was already used when anti-aliasing is on, so we can close this issue.
