### ISSUE TITLE
Pickable item are not drawn in red anymore

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1725]
When an item was picked we use to draw it in red (which was usefull to actually see the picked item) I just discover that the item is now drawn very briefly in red (like 0.1sec) and then is drawing back to its initial color. 

Something may have change in the picking method or somewhere else...

I tag it as a bug unless it has been done by purpose.

**Comment by AlexisDrogoul** [comment]
Well the problem is that picking is probably considered finished as soon as the menu appears. I'll investigate this one.

**Comment by AlexisDrogoul** [comment]
I have taken this occasion to seriously reorganize the way picking was done, as it was almost impossible to understand what was happening. Now the menu listener (the one used for other purposes, including the event layer) is in charge of triggering it (instead of the camera before), and the menu manager in charge of stopping it. In between, the renderer does almost of the job of rendering in the select buffer, etc. (instead of the camera, again). And the state of the picking process, instead of being distributed among 5 variables and 3 classes (picking, pickedObjectIndex, picked, isPickedPressed, etc.) is now centralized in a class called PickingState in the renderer. It should normally work as before -- and it is a lot easier to debug for future problems. 

I consider it as fixed, please reopen if any problem arises.
