### ISSUE TITLE
The undo (Ctrl+Z) in the project Explorer of GAMA will "undo" anything without confirmation

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1729]
For ex: clone a file or porject in the Project Explorer, althought that the file (project) are suscessful saved, but when we give focus in the Project Explorer and press the shortcut key of Undo, this action will remove the files, projects without any confirmation dialog...
The "Redo" cannot recover the thing that have been undone.

**Comment by AlexisDrogoul** [comment]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=460698

This has just been fixed in Eclipse, so we won't (and basically can't, given the low level at which the fix has been made) take any action on this. 

There is no possibility to disable CTRL/CMD+Z automatically given the buggy state of the key bindings in the compatibility layer. However, you might want to try one workaround: catching CTRL+Z in the filter I created and verifying if the active part is instance of the navigator (if (SwtGui.getActivePart() instanceof GamaNavigator)) and, in that case, consuming the event. But, if it works, it would disable it for all operations in the navigator, which is maybe not something we would like to have...
