### ISSUE TITLE
Very slow when opening a .csv file (3300 x 1)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1751]
When I try to display the following .csv file in GAMA,
GAMA takes _a lot_ of time to process and display it.
It can display it, but gets very slow.
In addition very few memory is used (as the file is only 36KB)

[matriceDebitReelPointDOE.csv.zip](https://github.com/gama-platform/gama/files/266056/matriceDebitReelPointDOE.csv.zip)

**Comment by ptaillandier** [comment]
It seems to be due to the creation of the TableViewerColumn (MultiPageCSVEditor, line 223: final TableViewerColumn column = new TableViewerColumn(tableViewer, SWT.LEFT);).

I am not sure that there is a solution to improve it, except by using another implementation of SWT table (maybe with this library: http://www.eclipse.org/nattable/).

**Comment by AlexisDrogoul** [comment]
I came to the same conclusion some time ago, after having tried to use `VIRTUAL` tables -- but nattable is a complete new implementation, and would require a lot of changes. It has to be noticed, however, that the problem comes from the number of columns. Few columns and a lot of lines are ok.

**Comment by AlexisDrogoul** [comment]
I close this issue as there is no easy way to implement even a workaround (SWT is clearly the culprit here). Please reopen if it is a real problem...
