### ISSUE TITLE
1.7b release not functional on Windows 7 / Windows 8

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1776]
Hello,
I have tested the current release with the cmd mode on Windows 64bit. Here are two output files.
Cheers,
Quang
[err.txt](https://github.com/gama-platform/gama/files/271130/err.txt)
[no.txt](https://github.com/gama-platform/gama/files/271131/no.txt)

**Comment by AlexisDrogoul** [comment]
Is it functional ? Most of the logs are problems when loading bundles (we have to resolve this) and the others are harmless. But you dont say if it opens or not.

**Comment by tcquang** [comment]
Hello,
It is functional. But there are no experiment button, and I can create a new model ( no responding).
I just test with Windows 7 32bit  - Virtual machine. But it's not functional. 
Please find the attachement ( but there is only one file have report data)
QUang

[no.txt](https://github.com/gama-platform/gama/files/271178/no.txt)

**Comment by tcquang** [comment]
In  the Gama.ini file, the property Xmx is set by "Xmx2048", So it did not work on my windows 7 32b 2GB Ram.
I have changed to Xmx512m. It function, but it like on Windows 64bit (no button; can't create new project)

Cheers.
Quang

**Comment by tcquang** [comment]
I  just downloaded the version of Gama 1.7 pre-release, that have been exported 20 minutes ago. It is still not good working on WIndows 64bit. The Toolbar is still missing.
Here are the error reports:
[no.txt](https://github.com/gama-platform/gama/files/297939/no.txt)
[err.txt](https://github.com/gama-platform/gama/files/297938/err.txt)
![gamapre_release17_03062016](https://cloud.githubusercontent.com/assets/11825516/15785053/8eb5bb0a-29df-11e6-9ba4-bc53901778d6.png)

**Comment by tcquang** [comment]
I just tried some test on manipulating the files of 2 versions:
V1: The exported version of GAMA from gama.product. 
V2: The pre-release version of GAMA.
1. Replacing sequentially 1 of the folders: configuration, features..plugins of the V2 by the one of the V1: It's not working
2.. Replacing 2 folders (in same times), the folders configuration and plugins of V2 by these 2 folders of V1 : It works

**Comment by AlexisDrogoul** [comment]
OK. It means we have a problem with the MAVEN build (probably not exporting all the required plugins for Windows, or not all the resources). I put @reyman in copy of this. Do you think you could make a diff of the contents of these two folders (the one in V1 and the one in V2) ?

**Comment by tcquang** [comment]
I have listed the differences between on 2 folders: plugins and configuration.
Please find the differences in the attachment file in excel and PDF.
[plugins_conf__diff.xlsx](https://github.com/gama-platform/gama/files/298676/plugins_conf__diff.xlsx)
[plugins_conf__diff.pdf](https://github.com/gama-platform/gama/files/298675/plugins_conf__diff.pdf)

**Comment by AlexisDrogoul** [comment]
OK ! Thanks for this intensive diff. It makes things a little bit clearer (I hope). First of all, msi.gama.ext is not expanded, although it should probably be (but it works on MacOS X like this, so maybe it is not necessary). Second, it seems that all the dependencies (incl. the optional ones, like XPand,  JDT, etc.) of XText are also included, which should not be the case. Once again, it seems to work on MacOS X like this, but maybe it creates problems on Windows ? @reyman , do you think you have an idea of where this difference comes from ?

**Comment by AlexisDrogoul** [comment]
OK. I have solved the first one (simple one), and I think the second case is due to this:

https://wiki.eclipse.org/Tycho/Release_Notes/0.14

Basically, optional dependencies are marked as required (which is not the case for us: JDT dependency is only necessary for building the grammar, not for using it).

However, I dont know exactly where to put the lines they proposing:
```
  <plugin>
    <groupId>org.eclipse.tycho</groupId>
    <artifactId>target-platform-configuration</artifactId>
    <version>${tychoVersion}</version>
    <configuration>
      <dependency-resolution>
        <optionalDependencies>ignore</optionalDependencies>
      </dependency-resolution>
    </configuration>
  </plugin>
```

??

**Comment by tcquang** [comment]
Here are the trees of directories of 2 versions. 
[tree_Pre64.txt](https://github.com/gama-platform/gama/files/298712/tree_Pre64.txt)
[treeExport.txt](https://github.com/gama-platform/gama/files/298711/treeExport.txt)

**Comment by AlexisDrogoul** [comment]
Hi,

Note that, for the moment, and because of #1863 , PDE build is again broken (see #1851 ). The only solution to test a direct release is to manually edit (ie. as text file) the gama.product file and remove all `installMode="root"` properties. 

Sorry for that. I'm waiting for an answer to the multiple posts I have made on different forums to know how to simultaneously enable Tycho and PDE builds. For the moment, the situation is:

- PDE build: does not work with `installMode="root"` (ie. the plugins of the features marked with this property are not copied in the application). Removing the property produces a correct release, but it is not updatable.

- Tycho build: produces a release which contains too many plugins (i.e. all the optional ones), and they seem to interfere with the correct execution of GAMA on Windows (not on MacOS X or Linux, though, which is strange).

Any further hints would be appreciated... 

Cheers
Alexis

**Comment by reyman** [comment]
Hi @AlexisDrogoul , one good way to have a rapid answer is the mailling list of tycho dev. I ask a message about plugin/product separation and one of core developper answer quickly. The list is here : https://dev.eclipse.org/mailman/listinfo/tycho-dev

**Comment by AlexisDrogoul** [comment]
Well, I tried that too but for a reason I ignore, I can't have access to it from Vietnam. Basically, what is to be posted is the previous message: when features composing a product are marked with the `installMode="root"` property, PDE build does not export them, which is a bit strange. And the second thing is about the optional dependencies. I havent found where to put the property I was mentioning in the message above, so that Tycho build does not export all the optional plugins (which are surely the reason why Windows builds fail).

**Comment by reyman** [comment]
@AlexisDrogoul Message sent, i give feedback here if i have an answer.

**Comment by AlexisDrogoul** [comment]
Seems that, due to a bug in Xtext, it includes all optional dependencies despite the build directive. I have produced a new pom.xml for msi.gama.parent that explicitly removes these dependencies. I have successfully built a MacOS X release with it, so can you try to build a Windows build with it ? I will push it on the git repository soon.

**Comment by AlexisDrogoul** [comment]
I have tested one of the Tycho releases on Windows 10 and it works well. I think we are on the way to the solution. We now need to test them on Windows 7 and 8. Travis seems to be more or less stuck (it produces correct builds, but does not upload them -- I've just pushed an issue about this), but you can build them quite simply by going into the root of the `gama` folder on your git repository using bash, and run `./build.sh` from there. Be sure to have Maven installed and configured (http://maven.apache.org/install.html) before. The releases will be produced in `msi.gama.application/target/products`.

**Comment by hqnghi88** [comment]
The new release of Travis work well. I just download it from latest tag.
Cheers.

**Comment by tcquang** [comment]
I have tested the new pre-release, 20 munites ago. It works well on Windows
7 32b.
Congratulations!


2016-06-09 0:36 GMT+07:00 hqnghi88 <notifications@github.com>:

> The new release of Travis work well. I just download it from latest tag.
> Cheers.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gama-platform/gama/issues/1776#issuecomment-224669026>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALRxbK92i4mySbkKQo_XNV-hwtQ2yH0uks5qJv2fgaJpZM4IhkT2>
> .
>



-- 
Quang Chi TRUONG
Tel: 0939388153
