### ISSUE TITLE
Export SVG files in the headless mode

### ISSUE THREAD

**Issue by jdzucker** [gama-platform/gama#1778]
To support advanced function in the gamaR Package. This would enable us to provide a super smooth video.

**Comment by AlexisDrogoul** [comment]
SVG export requires a lot of other libraries...

**Comment by AlexisDrogoul** [comment]
Actually, I made a quick tour of what is available, and I think the solution can be:

- to create a new kind of display which internally uses http://www.jfree.org/jfreesvg/ (a lightweight library)
- to create the corresponding IGraphics object using the same library
- to add an option to the headless experiments so that they use this display instead of the standard `image` Java2D one and retrieve SVG elements instead of BufferedImages (after that the library has everything necessary to save SVG files with the correct headers, etc. )

Not a lot of work, I guess, and most of it could be put in a separate plugin.

**Comment by AlexisDrogoul** [comment]
Moved to https://github.com/gama-platform/gama.experimental/issues/10
