### ISSUE TITLE
clarify graph types and status in gama

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#178]
```
Recent changes in graphs made things more messy there. 
Need an advice from GAMA gurus and leaders for future evolutions. 

1) there is no consistency on the graph actual behavior. Graphs created from GIS are
mapped to agents, but removing an agent does not removes the corresponding node (and
reciproc.). Graphs generated from the novel primitives are "synchronized". If graphs
created from GIS are mapped to agents, we should probably synchronize these graphs
with populations as well. 

2) there is no consistency on how graphs are backed up. Some are encoded as GamaGraphs,
some as SpatialGraphs.  Looks like, when I create a Watts-Strogatz network that is
backed up by agents (thus by shapes), it is implicitly spatialized; thus I should use
SpatializedGraph rather than simple GamaGraphs. 

3) should we introduce graphs that are not related to agents ? That is, "just" a graph
object, without having one agent per edge/node ? 


```

Original issue reported on code.google.com by `Samuel.Thiriot.Asso` on 2012-04-18 22:46:26

**Comment by ptaillandier** [comment]
I don't know what to do for this issue. For the moment, it is possible to define spatial and non-spatial graphs:
graph my_graph <- spatial_graph([]);
graph my_graph <- graph([]);

Normal graphs have for advantages to use less memory (less elements to store) but cannot produce spatial path (in contrary to spatial graphs that produce spatial path)

Concerning the creation of graph:
 - the spatial graph operators (as_edges_graph,...)  produce spatial graphs
 - the graph generation operator produce non spatial graphs
 - the loading of graph files produce non spatial graphs

Not that  non-spatial graphs can have for nodes/edges all kinds of objects (agent, geometry, string, float....) and spatial graphs all kinds of spatial objects (agent, geometry, point)

**Comment by benoitgaudou** [comment]
I close this issue.
About the comments of the original issue:

1) there is no consistency on the graph actual behavior. Graphs created from GIS are
mapped to agents, but removing an agent does not removes the corresponding node (and reciproc.). Graphs generated from the novel primitives are "synchronized". If graphs created from GIS are mapped to agents, we should probably synchronize these graphs with populations as well. 

I addressed this issue as follows: when a graph is created from a set of agents, a weak synchronization between both is created : when an agent is killed/dies it is also removed from the graph. I consider that other kinds of synchronization are not used right now. Do not hesitate to post an additional dedicated issue if needed.

2) there is no consistency on how graphs are backed up. Some are encoded as GamaGraphs, some as SpatialGraphs.  Looks like, when I create a Watts-Strogatz network that is backed up by agents (thus by shapes), it is implicitly spatialized; thus I should use SpatializedGraph rather than simple GamaGraphs. 

cf. Patrick remarks

3) should we introduce graphs that are not related to agents ? That is, "just" a graph
object, without having one agent per edge/node ? 

This has been addressed previously.
