### ISSUE TITLE
Event with Key shows markers because the action doesn't take into account the mouse location

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama#1799]
Hi everyone, 
as you may know, it is possible to manage key event to do an action during an experiment. They are basically declared just as the event with mouse_down and up... However, when you declare a key event, it is useless to give also the mouse location and the selected_agents is also omissible. 
I personally think it would be better to remove those markers when the event is a "key" event (at least to have the models Library in green if we put this kind of interaction events).

**Comment by AlexisDrogoul** [comment]
Having the current mouse location and the agents can be interesting for some users even if the event only captures a key event. We cannot decide it on behalf of them - which means that the interface of the action to call cannot change depending on the context of the event.

Adding this warning is a way to remind people that these two "features" are available. Otherwise nobody would know it.

So, if it is too much effort to add these two arguments to the action, we can put it as an info -- though nobody reads them, more or less. Or we can add a "type" to the event layer, that will determine which interface is called -- but I am a bit skeptical about the real benefit of having to declare a type compared to adding the two arguments.

**Comment by dphilippon** [comment]
Well, I agree that they can be used in some cases, however, even if it is not really difficult to add the two attributes in the action, it's a little bit strange to add attributes in the definition of an action when they will not be used and not having a warning, whereas if you don't add attribute that are useless you get a "warning" marker. 

As another example (even if it is not at the same level but it's still an example), if the user doesn't put the focus facet, the user doesn't have a warning telling him "remember you can do also focus" (I'm quite exaggerating). For this case, the user must go on the Wiki and look for the facets of display...

But I do understand that this is something not really urgent (that's why I depicted it as Priority Low) and it is discussable.

**Comment by AlexisDrogoul** [comment]
Closed. I moved the marker to `info` priority.
