### ISSUE TITLE
Position of the snapshot

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama#1815]
Hello,
When user click on the "Take a snapshot" button, on the simulation screen, the picture is well taken but user don't know where the picture is stored.  In my case, the picture is in the diagram\snapshots but not in the doc\snapshots.

Could you please adjust a messagebox to say that  the picture is well taken and the folder where it is stored. 

Thank you!
![take_simulation_screen](https://cloud.githubusercontent.com/assets/11825516/15479875/a99bd4f4-214c-11e6-905e-9d2f997a846d.png)

**Comment by AlexisDrogoul** [comment]
We will probably **never** put a message box. However, putting them in `docs/snapshot` could be an idea.It's be great if we'd be able, at the same time, to build a simple `.md` file that lists these snapshots and could be directly uploaded to the server.. .

**Comment by AlexisDrogoul** [comment]
Just to add a note, as I hadn't taken a look at your picture: the snapshots are always created in a `snapshots` folder next to your model. Since your model is in `diagrams`, it is quite normal that it appears here. And we will probably keep this rule if you dont mind, as it could be a bit difficult, for large projects with a lot of subfolders containing models (like MAELIA) to put all snapshots in the same `doc/snapshots` place. Especially if you have models with the same name but in different folders... So I close this issue for now on.
