### ISSUE TITLE
Model Library cleaning / Open Discussion for 1.7 Release

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1825]
I think we should put the Toy Models before the Feature. The first time you open GAMA, you explore the library and then you arrive on the feature.. which is a bit weird. Also inside this feature the first folder is the 3D Visualization. I was happy  to have this as a first item before but now I think that 3D could be not anymore a feature but a fact.. ;-)

I try to list each problem in every item (did not have time to finish it)

- 3D Visualization:
	-Build-In Shape? see #1824
	-GIS visualization, I am not a big fan of this model

- Agent movement: 
	-follow path is really simple, i understand the idea to have a canonic model but maybe we can have at least more schematic lines ?
	- Why the grid is not exactly a grid? This nearly grid looks weird, I mean why don’t we put a real graph looking like a grid with 90° angle?
        - GoTo grid what about this wonderful pink color that summarise the agent trajectory? We keep it only for Patrick ?
	- Goto Network: same why this strange grid and not an orthogonal one?
        - Goto polygon, some effort can be done on the graphic design (smaller point, more harmonised color?)

- In Data Importation there is nothing about GIS Import?
- Batch: Maybe the data could be saved in a specific folder
- Clustering: Where the 3D clustering made by Jean-Daniel?
- Color: 
	-Bubble sort 3D looks more like a toy model no?
	-RGB to XYZ looks weird no?
- Co-model: 
	Naming convention, underscore and m1,m2, etc
	English in the comment description
	Ants_Coupling runtime error (soil.jpg is not found)
        The PrePredator sims looks cool but its hard to understand what happens (maybe some label under some agent could help)
	PreyPreadtor_coupling.gaml is not doing anything?

- Database usage: maybe we should document more the fact that the model won’t work if there is no server. 
	Connection Test.gaml: no tag no doc

-------------------------------- To be continued --------------------------------------

**Comment by ptaillandier** [comment]
Hi,


I think we should put the Toy Models before the Feature. The first time you
open GAMA, you explore the library and then you arrive on the feature..
which is a bit weird.
For me, it is not very important, but, it is not a problem to change the
order

Also inside this feature the first folder is the 3D Visualization. I was
happy to have this as a first item before but now I think that 3D could be
not anymore a feature but a fact.. ;-)
You are partially right, but I think it is still important to show in
simple models how to have 3D displays.

-Agent movement:
-follow path is really simple, i understand the idea to have a canonic
model but maybe we can have at least more schematic lines ?
For me, it is good like this: simple to understand

- Why the grid is not exactly a grid? This nearly grid looks weird, I mean
why don’t we put a real graph looking like a grid with 90° angle?
you can change the shapefile if you want (I do not know where this one
comes from ;) )

- GoTo grid what about this wonderful pink color that summarise the agent
trajectory? We keep it only for Patrick ?
I find interesting to show the trajectory. Change the color if you want.

- Goto Network: same why this strange grid and not an orthogonal one?
you can change the shapefile as well.

- Goto polygon, some effort can be done on the graphic design (smaller
point, more harmonised color?)
Do as you want.

-------------------

-In Data Importation there is nothing about GIS Import?

I am agree, we should add one.


-Batch: Maybe the data could be saved in a specific folder

You can modify the model to do it.


-Clustering: Where the 3D clustering made by Jean-Daniel?
Because JD's model does not use the clustering operators of GAMA. So we
should add it in the toy model folder and not in the feature folder.

-Color:
-Bubble sort 3D looks more like a toy model no?

yes, you are right


-RGB to XYZ looks weird no?

I don't know

I agree with your other remarks :) .


Cheers,


Patrick


2016-05-24 16:41 GMT+02:00 agrignard <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
Quickly, on these different points:

- Features and Toy Models are correctly ordered, I think, as the toy models are usually more complex than the feature ones. Having 3D first is also ok, as Patrick said (and, by the way, features **are** facts: everything that is demonstrated in "Feature models" **is** a fact that comes built-in into GAMA).
- Feature models are supposed to be very simple ones, so I'm ok with the schematic shape files in Agent Movement. It's ok also if you want to change the shape files (but keep simple ones).
- on Batch you may want to change the path if you feel it is necessary.
- for Clustering Patrick has already answered. Feature models are here to demonstrate operators, data types, built in into GAMA. 
- Bubble sort  can without problem( and probably should) move to Toy Models (feel free to do it, again)
- Co-modeling is actually a big mess, esp. concerning the naming of the models, I agree. I will open a separate issue on this.
- Database. Yes, please add a comment or a display in the console to warn the user
- Connection will not be here anyway, but in the "network" plugin models.

**Comment by AlexisDrogoul** [comment]
Completely fixed save a "GIS Import.gaml"
