### ISSUE TITLE
Add a preference to define the maximal memory (xmx) allocated to GAMA

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1835]
By default the quantity of RAM allocated to GAMA in 64 bits environments is pretty low and many users have to increase it. For the moment, the only way is to edit the GAMA.ini file which is not so easy to do on Mac OS. So I propose to add a preference (performance tab) to allow to directly choose the memory allocated to GAMA (that could simply modify the Gama.ini file and propose to restart GAMA).

**Comment by tcquang** [comment]
I agree with Patrick, but could you please set the default memory less than 2GB (1 to 1.8GB). Because there exist many computers that have been solved with only 2GB (it's not my case but there exist the core i3 - 2GB Ram). If you set a large default memory, people would not able to launch the GAMA to change the preferences.
Thank you very much!

**Comment by AlexisDrogoul** [comment]
That is going to be difficult. Manipulating the "Gama.ini" file at runtime is, firstly, a bit difficult, and secondly, a little bit dangerous. Moreover, we will probably have right issues (because I dont know if we are allowed, in every environment, to write in its folder). Concerning putting less than 1GB on 32-bits version, it is something we should fix at build time ( @reyman ?). I've pushed a version of the product that differentiates the amount of memory for 32 and 64 bits environment, but it needs to be verified in the built version.

**Comment by reyman** [comment]
Actualy we have the possibility to inject build dependent configuration using ant maven or ressource maven plugin during the build. We already have an `extraresource` folder for that in `msi.gama.application`

**Comment by AlexisDrogoul** [comment]
Regardless of fixing the memory in the product and/or Tycho, I've added a preference, which is only active in the release (as `Gama.ini` does not exist for the development version). In the `Performances` section, it reads the file and writes back the new value, asking for a restart, saving the user from editing it manually.
