### ISSUE TITLE
Spaces in the name of model and experiment

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1837]
The model name does not accept spaces. It is difficult to avoid the CamelCase , the underscore or a meaningless name.

The experiment name accept a string with space but in comodeling, i cant find a way to give experiment name to micro-model identifier, for ex:

import "The Couplings/Traffic Coupling.gaml" as myTraffic

create myTraffic."Traffic experiment";
or
create myTraffic.Traffic experiment;

didn't help.

**Comment by AlexisDrogoul** [comment]
Model names are like species names: they should be written using underscores (the name of the file, on the contrary, should be using spaces).

The problem with experiments is that the name is both used for displaying something readable by users (on buttons, for instance) and, since the co-modeling architecture, as a possible var/species name. I agree it makes things a bit difficult in that case. 

The solution is of course (like for the parameters) to separate the "name" (i.e. syntactic name used in GAML) and the "title" (i.e. the one used for display). This requires some modifications to experiments but also to keep a solution for all the models where only the name is defined (as it is the case now).

I dont have an immediate solution to this problem. Probably the best thing to do would be to enforce some automated solution where:

- when the name is written using a string, we use it for the title and replace all space and special characters by underscore + `_experiment` to compose a new name.

- when the name is written using an identifier, we replace all underscores by spaces, and capitalize the first letter of each name. 

So in your previous example, the experiment would be named `traffic_experiment` and titled "Traffic Experiment".

**Comment by AlexisDrogoul** [comment]
I have committed a different solution, which basically allows to write a sentence like: `myTraffic."Traffic experiment";`. Strings are then allowed for the names of experiments. Please test and close if it is ok.

**Comment by hqnghi88** [comment]
Dear Alexis,
I have changed the names and tested it. It works very well.
Cheers.
