### ISSUE TITLE
full screen 100% full not 99%

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1842]
You will say that I am fussy but this is important. 

As I want to project a GAMA model on a table in some case if table is black I put a black background in GAMA and then only my model will appear on the table. I ve just notice that there is a little white frame on the fullscreen mode (see screenshot)
<img width="1920" alt="screen shot 2016-05-26 at 10 40 31" src="https://cloud.githubusercontent.com/assets/3928502/15578552/e00cf318-232e-11e6-87b3-4c5d042bb20f.png">

is there a way to disable this white frame? maybe a simple option of the fullscreen mode?

**Comment by AlexisDrogoul** [comment]
I am a bit annoyed by this request, because the SWT.BORDER which produces this white border is part of the definition of the view and cannot be changed afterwards. So either we remove borders from every display or we keep them, but we cannot really tweak this. You can try to play a bit with the definitions of the surfaceComposite in LayeredDisplayView, adding or removing this property to see what changes. Or you can use a white background :)

**Comment by agrignard** [comment]
Mmmm.... yes I can use a white background but it means I need to rebuild my hardware (the color of the table) from black to white... a bit more complicated that just saying background:#white/#black

And what if I cannot build a new table?? 
Is it a big problem to remove this border for every display?

**Comment by AlexisDrogoul** [comment]
I've given you the clues to test it. You can add a preference to set the border or not, and use SWT.BORDER or not based on this preference.

**Comment by AlexisDrogoul** [comment]
I've looked quickly -- too bad for you :) It happens only for OpenGL screens. Java2D ones are covering the whole surface. So it is probably out of our reach as no property is passed to the canvas.
