### ISSUE TITLE
find/replace window strange behavior in simulation perspective

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1844]
This is a small problem but I just notice that when you use the find/replace window (ctrl+f) once this window is opened if you move your mouse in the display (so this means you are editing your model while in the simulation perspective which I know is not the usual way of doing but when you develop visual stuff I personally find it essential to see your display while writing) the find/replace window became inactive, when you reactivate it by clicking on it then you don't have anymore the find button active.

**Comment by AlexisDrogoul** [comment]
This is due to a number of things, among which the fix for #1353 , and the fact that displays try to keep their focus as long as possible so as to favor user interaction (i.e. when you move the mouse out of the display, you still can interact with it). The only solution is to click again in the editor. Nothing easy can really be done to fix this so I put it in standby.

**Comment by AlexisDrogoul** [comment]
After some digging, I found that Eclipse has exactly the same behavior: if any view captures the focus when moving the mouse (can be achieved with special preferences in "General"), the search/replace box becomes inactive and when you activate it the "Find" button is disabled because the focus is now taken by this view. You then have to click again in the editor (even if it appears as "on top and activated") to activate "Find". So I close this issue as there is nothing that can be done...
