### ISSUE TITLE
Command line history in the interactive console

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#1845]
In the new GAMA console it would be great (if it's not to complicated) to have an history of the command line like in a classical terminal where you press the up and down arrow the navigate in the history of your command line.

**Comment by AlexisDrogoul** [comment]
It won't be added in the current incarnation of the console (which mixes input and outputs) because, when you output long logs, moving among them with the up/down keys is a natural thing to do. 

What I plan is to have a second console soon, which will be dedicated to interactivity (and in which you will be able to choose the agent with which to interact, also). Its keybindings will probably include such a feature, then.
