### ISSUE TITLE
ROI and agent selection

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1875]
There are several problems with ROI and agent selection:
 - The documentation is not up to date (see http://vps226121.ovh.net/references#Displays): it seems that now the agent selection is achieved using the shift + left click and not alt + left click
- it is not woking with java2D (but maybe it is normal)
- it does not work with the attached model (I can draw the ROI, but no agent is selected):
[ModelPlage 2.zip](https://github.com/gama-platform/gama/files/304097/ModelPlage.2.zip)

### System and version 
GIT version, tested on MAC OS X (El Capitan) with a macbook pro.

**Comment by AlexisDrogoul** [comment]
ROI is now shift+mouse. All combinations with alt have been removed. It is not working (and will not for the time being) on Java2D. I havent tested the model, but there are several limitations for the ROI: the agents must draw their shapes (and not arbitrary ones) and these shapes should intersect the ROI (i.e. not be situated above it, for instance).

**Comment by AlexisDrogoul** [comment]
I tested the model. Actually, ROI works but only if the model is running. Otherwise no agent is selected. Do you see the same result ?

**Comment by AlexisDrogoul** [comment]
OK. Got it. The structure of the model is a bit perilous, because the shape of the world is defined in the init section of the model (see gama-platform/gama2#3) and not in its attributes. The result is that all the populations, which are attributes of the world, are built against the first definition of shape (the default one, continuous, 100x100) and compute their topology from this definition (using it as their "root topology"). When the shape of the world is changed, the root topology is then recomputed (with a different spatial index, etc), and not "updated" (i.e. the world points to a new object).

So whenever an agent is created from one of the species, it is added to the old "root topology" and not to the new one. 

Although changing the shape of the world is not yet allowed, it is a preoccupation bug that this ROI thing has uncovered. We have two choices to fix it: first one is to update the topologies of all populations with the new root topology (if, of course, its points to the old one); second choice is to simply update the dimensions of the root topology -- however, all the existing topologies bounds may be completely wrong at that point. I'm a bit lost here...

**Comment by ptaillandier** [comment]
I have no idea which one is the best choice (I remember having the same type of problem when changing the world shape with the target projection). Maybe, if it possible, we could just for the moment add an error if someone wants to change the shape of the world in the init section.

**Comment by AlexisDrogoul** [comment]
I have implemented a solution, which is a kind of compromise and which seems to work quite well -- I still have to test it with grids and graphs, though and I will commit it. The good thing is that it allows to change the shape of the world without too much trouble (at least, less than the current implementation), but of course it is far from perfect and does not solve the problems raised in gama-platform/gama2#3.
