### ISSUE TITLE
Ant sorting: bad display of SVG shapes

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1903]
### Steps to reproduce
1. Open "Ant sorting"

2. Run the model

### Expected behavior
The shapes of the ants should be "normal"

### Actual behavior
They are completely oversized (see snapshot). Java2D is ok.

![sort - users drogoul documents git gama ummisco gama product target products ummisco gama application product macosx cocoa x86 2016-06-28 20-52-34](https://cloud.githubusercontent.com/assets/579256/16418071/821db2ca-3d72-11e6-83b7-3b71f2d5172a.png)

### System and version 
Current Git version, MacOS X El Capitan

**Comment by ptaillandier** [comment]
This bug is due to the fact that the static Map envelopes is both defined  in Abstract3DRenderer and JOGLRenderer (and in ModernRenderer). As a result, the env of the SVG file is added to the envelope map in JOGLRenderer , but not found when trying to get the value from Abstract3DRenderer. Why do you need to redefine them? (same for other static variables in these classes)?

**Comment by mazarsju** [comment]
Hi,
Those static variable don't need to be redefined of course. Sorry, it was an error I introduced, I just changed it, it seems to do the trick.

**Comment by AlexisDrogoul** [comment]
And I would like to add that, of course, we SHOULD NOT have any static variables in renderers (other than the ones  used to memorize global properties and which NEED to be shared between renderers).
