### ISSUE TITLE
Preferences Properties : set the default value of "Enable OpenGL background loading of textures" to false 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#1912]
### Steps to reproduce
1. Launche GAMA on a random Windows 10

### Expected behavior
GAMA works

### Actual behavior
In all the cases I tried, the run of some experiments does not work.
The fix is to set the default value of "Enable OpenGL background loading of textures" to false .

We could perhaps set it to false in the release ?

### System and version 
Windows 10

**Comment by AlexisDrogoul** [comment]
I'm trying to find a way to detect which combination of OS & Graphic Cards produces this, because it is not random. It can happen on MacOS X, Windows or Linux equally, and it is quite certainly due to the graphics card used (Intel ones, for instance, usually fail, but not on MacOS X thanks to its OpenGL drivers). The problem we're facing is that turning it off will degrade the experience (memory & speed) for all users just because of a handful of faulty machines. 

By the way, do you have a log or something that tells what happens ?
