### ISSUE TITLE
variable/parameter value listener

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1914]
It could be interesting to have the possibility to listen the change of value of a variable/paramete (in particular, if we can refresh a display through the gaml language)

**Comment by AlexisDrogoul** [comment]
You mean, in GAML or in Java ? 
In Java, I was planning to do that in a future release (i.e. to clearly separate the UI with the core, so that the Parameters view, for instance, loses its dependencies towards the core and only calls change /update listeners, like what is implemented for Preferences).

**Comment by ptaillandier** [comment]
I mean a GAML listener:
for instance, I would like to write something like:
parameter "perception distance" var: perception_distance trigger: compute_agent_perception;
or
float perception_distance trigger: compute_agent_perception; 

With compute_agent_perception a global action that will be triggered when the value of the perception_distance variable/parameter is modified.

**Comment by AlexisDrogoul** [comment]
OK. I would however change this requirement to provide a more general way of dealing with these changes (I planned to do this, also, for event layers). Passing an action like this is not really standard and I would prefer giving the possibility to pass a block instead, eg.:
```
float perception_distance on_change: { do compute_agent_perception; }
```

So that you can pass arguments, specify which agent should run it, etc...

**Comment by ptaillandier** [comment]
It is a very good idea!
