### ISSUE TITLE
Default user action "kill" should call the "die" action

### ISSUE THREAD

**Issue by mazarsju** [gama-platform/gama#1926]
### Steps to reproduce
1. Overload the "die" action to an agent, with a `write "debug"`
2. Run the experiment
3. Right-click on the agent, apply the action "kill"
### Expected behavior

The agent should not be deleted, and the word "debug" should appear in the output console
### Actual behavior

The agent is deleted, as if the "die" action were not overload.

**Comment by AlexisDrogoul** [comment]
I'd never thought of overloading the `die` action, but yes, it makes sense if you want to define immortal agents. You're right : this overloaded action is not called (`dispose()` is called instead) in `Kill`. The problem is that we have to be extra-cautious on this one: it would make sense, if we call `die` in `Kill`, to also call it when we kill the simulation. And if your agents are never killed, then we end up in a strange situation where some agents will not be dead although their host and population is disposed. 

Since overloading is not implemented in GAML (i.e. you cannot call something like `super.die()`), we could transform this action into something similar to `init`: the `die()` actions of super species will be called at the end of its execution automatically.

**Comment by AlexisDrogoul** [comment]
Actually, after some thought, I'm more in favor of disallowing the user to overload `die()`. If you want to have your own action, you can always specify a user_action in the species, which would then eventually call the built-in `die()`. But overloading it leads to some potential troubles...

**Comment by AlexisDrogoul** [comment]
OK. I've addressed this request by improving a bit the reflex architecture, allowing the modeler to declare one or more `abort` reflexes, similar to `init` in their principle, but only called just before the agent is disposed of. `abort` reflexes, like `init` or `reflex` ones, can also have a `when:` facet, so that they are only run when this facet returns true. There can be several of them, either inherited, or declared in the same species, and they will be executed in their order of definition.

So your example should now be written:

```
species a {
    abort {
        write "debug";
    }
}
```
