### ISSUE TITLE
Problem with texture (Obj file - OpenGL)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#1951]
### Steps to reproduce
1. Import and run the attached model

### Expected behavior
The texture should be well applied to the object (open the obj file with a 3D viewer such as GLC to see the expected result)

### System and version 
Git version 
[TIP TOP demo.zip](https://github.com/gama-platform/gama/files/387935/TIP.TOP.demo.zip)

**Comment by AlexisDrogoul** [comment]
I've tried to take a look and modify some aspects of the MtlLoader and "obj" files renderer, but it's way too complex and I'm not sure I've understood everything I've done. Maybe we should switch to another library for reading, parsing and rendering obj files, no ? This one seems a bit... hand-made.

**Comment by agrignard** [comment]
I can confirm this is really hand made (one of the contribution of the last last coding camp) but I did not find any generic and better way to do it. Maybe there is some better library that can also deal with other 3D assets format.

**Comment by ptaillandier** [comment]
I don't know it it linked to the previous issue, but with the current version of GAMA, some obj files (with textures) are not so well displayed (it was working well some month ago).  
You can have a look at the cat and the car: the textures are not good

[agent display.zip](https://github.com/gama-platform/gama/files/538496/agent.display.zip)

**Comment by AlexisDrogoul** [comment]
Well, first testing indicates 2 things:

- it doesn't work when the preference "Enable background loading of textures" is on. And it completely freezes my instance of GAMA.
- when it works, how is the texture supposed to be attached to the car, for instance ? A preliminary look indicates it seems to be somehow reversed, but Im not so sure. 

I remember that one of the problems that was occurring in this issue was the fact that the texture was not "repeating". However, I dont know if it was because we were ignoring this indication or because it is supposed to be repeating by default.

**Comment by AlexisDrogoul** [comment]
OK. It was working in the release version of last July. If I come back to the version of GamaObjFile at this time, it works again (even with the fix made on the 4th of August). So it is something else -- I will dig as the number of changes is not so important.
