### ISSUE TITLE
Inverted parameter description and parameter name ?

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#1962]
Using OpenMole workflows and a very simple design experiment plan, i inject value of parameter into workflow into Gama `parameter` during headless initialisation.

The OpenMOLE workflow for Voronoi example :

```
logger.level("FINE")
val seed = Val[Long]
val num_points = Val[Int]

val gama = 
  GamaTask(workDirectory / "Voronoi.gaml", "main_xp", 100) set (
    gamaInputs += (num_points, "num_points"),
    num_points := 5,
    seed := 42,
    
    gamaSeed := seed
  )

  gama hook ToStringHook()
```

```
experiment main_xp type: gui{ 
	parameter 'Number of points' var: num_points;
	parameter 'Width of the environment:' var: env_width;
	parameter 'Height of the environment:' var: env_height;
	
	output {
		display Voronoip type: opengl {
			grid cell  ;
			species center aspect: base ;
		}
	}	
}
```

Produce an error during execution. The parameter `num_points` is not recognized during initialisation of simulation.

With @ptaillandier we find the error, name and description of parameter are inverted ... We switch `parameter 'Number of points' var: num_points;` by `parameter 'num_points' var: num_points;
` and now experiment Voronoi works.

But the inverted way to define parameter name / description seems very very strange, is it a normal behavior ?  

### System and version 
Latest gama dev version, commit 1d312aadbf8c75742950e6316a6446cb1fa09ed6

**Comment by hqnghi88** [comment]
Hi Sebastien,
I dont know how to exec the block of openmole, but i just tested with the headless mode in Gama and the parameter are normally initialized with "normal" order. Can you please tell me how i can reproduce the error, i would like to investigate it.

**Comment by AlexisDrogoul** [comment]
Hi,

experiment parameters and model attributes are two different things in GAMA. In your example, you have a parameter whose title is `"Number of points"`, which points to the model attribute whose name is `num_points`. By convention, the `name` of the parameter will be the `name` of the attribute, not its `title`.   Probably, by defining in OpenMole your input like this: ` gamaInputs += (num_points, "Number of points")`, it should work as expected.

Now, if you prefer to deal with one word, nothing prevents you from naming, in your experiments, your parameters like your model attributes (e.g. `parameter speed var: speed;`) or using only one word (`parameter my_speed var: speed;`). 

ExperimentPlans in GAMA have two ways to retrieve parameters, by the way: either `getParameter(String)` -- which uses the name of the attribute -- or `getParameterByTitle(String)` -- which uses the title of the parameter. Corresponding setters are also defined. I think the headless plugin is using the retrieval and setting by title rather than the attribute names, which is why you think it is 'inverted'. 

Hope this is clear. 

Alexis

**Comment by reyman** [comment]
Thanks @AlexisDrogoul for explanation, this is very clear now.
