### ISSUE TITLE
Error compilation: The variable xxx is not defined or accessible in this context. 

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#1986]
### Steps to reproduce
Open
Toy Models\Boids\models\Boids With Flock.gaml	
### Expected behavior
Tell us what should happen (include all relevant expectations)

### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
Error compilation:
The variable speed is not defined or accessible in this context. Check its name or declare it
line: 120 /Toy Models/Boids/models/Boids With Flocks.gaml

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
gama git

**Comment by AlexisDrogoul** [comment]
OK. Found it. The variables are not correctly sorted as there is a cycle, in this species, in their dependencies. 

The line `geometry shape <- polygon(((boids_in_flock))) buffer 10;` is in cause since `boids_in_flock`, as a species, implicitly depends on the  `shape` of its host.

I will try to issue a fix soon.

**Comment by AlexisDrogoul** [comment]
I will not issue any fix for that as there is no way to "automatically" arrange things. Instead, I issue an error if a cycle is found, suggesting the modeler to move the initialization of the variable in the 'init' section if necessary. I have also corrected the 2 models that exhibit this behavior in the library.
