### ISSUE TITLE
Is the continuous build broken again ???

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#1993]
![releases gama-platform gama 2016-09-19 22-52-30](https://cloud.githubusercontent.com/assets/579256/18639106/cad0d908-7ebc-11e6-9a0b-a953ef623d97.png)
### Go to https://github.com/gama-platform/gama/releases

The "Continuous build" section, which used to contain the ... continuous builds, does not contain anything more, besides the source code. 

What happened ?

**Comment by hqnghi88** [comment]
There is no clue to track. I am watching a little bit.

**Comment by reyman** [comment]
Just one clue,  github deploy some New services after github universe
cobference. Perhaps they change à bit the api you use to push file ?

Le 19 sept. 2016 6:20 PM, "hqnghi88" <notifications@github.com> a écrit :

There is no clue to track. I am watching a little bit.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/gama-platform/gama/issues/1993#issuecomment-248041300>,
or mute the thread

**Comment by hqnghi88** [comment]
It works again. It seem to be a maintenance issue on GitHub repo with the new services? 
Thanks Sebastien, btw, where can I look for the new service? I was wondering about GitHub news but I didn't found something on google.

**Comment by AlexisDrogoul** [comment]
Here: https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

Thanks for watching, anyway. I can close this issue now !
