### ISSUE TITLE
Access a file form its url ? 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2005]
Issue or not?

Is it possible to access a file form a URL

In like with issue #1900 I now want to get this json file form a URL (and not from a local file). 

http://cityscope.media.mit.edu/citymatrix.json

Is it doable (maybe it's already possible but it does not work for json) to write this in GAMA

file JsonFile <- json_file("http://cityscope.media.mit.edu/citymatrix.json");
instead of 
file JsonFile <- json_file("../includes/cityIO.json");

**Comment by hqnghi88** [comment]
URL_file is created for the purpose. But long time no see, I don't remember it or I don't know how fine is it. Conceptually, if you write 
	file  urls<-URL_file("../includes/cityIO.json","http://cityscope.media.mit.edu/citymatrix.json");
	file JsonFile <- json_file("../includes/cityIO.json");
    map<string, unknown> c <- JsonFile.contents;
It will update the contents of your .json from internet each time.

**Comment by hqnghi88** [comment]
small trick, because the writing process is called only in the fillbuffer()
	string  urls<-""+URL_file("../includes/cityIO.json","http://cityscope.media.mit.edu/citymatrix.json");
	file JsonFile <- json_file("../includes/cityIO.json");
    map<string, unknown> c <- JsonFile.contents;

**Comment by agrignard** [comment]
when do use  "urls" variable?

**Comment by hqnghi88** [comment]
Write the line before json file declaration. The var urls is a fake var, the writing of content from url to file is all ready done when gama call operator + of " " and urlfile.

**Comment by agrignard** [comment]
yeah but in that case (I mean with this exact syntax) JsonFile is always readen from the local file if you don't use urls variable???

**Comment by hqnghi88** [comment]
Well it is just current solution withou any commit. When do you want to update the content of local file? Place the call to url before the declaration of filea and it keep you up to date with the url.
If you mean that in simulation time, you want to read a part of json from internet, we must implement it inside jsonfile, i think.

**Comment by AlexisDrogoul** [comment]
Np, there is no possibility to use URLs or URIs to access a file directly now. Too much burden to take care of (waiting time, availability, etc.). A solution like the one proposed by Nghi would in any case be better in all respect (i.e. have an operator that reads something from an URL, copy it in a local cache/file for later reuse). Maybe this could be automated inside the file call (i.e. that the file creates its own local cache, for example if it detects an URL).

**Comment by agrignard** [comment]
Ok @nghi is it a woking solution or just an idea?

If it works that sounds ok for me. The idea would be them too call it in a
global reflex every n seconds to be synchronized with the physical grid (
that is use a GUI)

Le vendredi 23 septembre 2016, Alexis Drogoul <notifications@github.com> a
écrit :

**Comment by hqnghi88** [comment]
It is a working syntax, i ve tried with your link. But i dont know about the security in your room, please ensure that if gama have been block.

**Comment by AlexisDrogoul** [comment]
OK, I've come up with a simple working solution directly in GamaFile, that does not involve URL_file. Basically, it does the same, but allows you to write a URL directly in the declaration of the file. After that, behind the scene, it generates a temp file that will be eliminated by the JVM at the end. It is a partially working solution because it does not really uses the url as a path, which means that files that depend on support files (like .prj for shape files, or textures for 3D files, etc.) will not be able to retrieve them correctly. I should, probably, for these case, create a new method in GamaFile to retrieve "support files with a relative path", or maybe it needs to be done on a per-file-type basis (as the GeoTools library has its own way of fetching support files). Anyway, for simple file types (like JSON, JPEG, PNG, CSV, etc.) it works well. I'll commit it in a few minutes.

**Comment by hqnghi88** [comment]
Dear Alexis,
Thank you for this implementation and it would be nice if the support files could be retrieve automatically, i meant, in the case of GamlFile (i.e the imported models).
Cheers.

**Comment by AlexisDrogoul** [comment]
The support files cannot be downloaded automatically (as it is strongly dependent on the type of files). Rather, I have implemented a method that specifies whether or not a GamaFile subclass should fetch the contents automatically or not. If not, the path is set to null and the url is stored, which means that it will be the responsibility of the subclass to get the contents (incl. the support files) from the url. Otherwise, subclasses have also the possibility to redefine the method fetchFromURL() to load support files. Something to add to #1362, by the way...

**Comment by agrignard** [comment]
Great!This is perfect so I can now control GAMA through a physical table made in lego (like the one in the picture) 

So Is is ok yo reupdate the jsonfile in a reflex? (like every 100 iterations)?

reflex update{
    JsonFile <- json_file("http://cityscope.media.mit.edu/citymatrix.json");
}

<img width="500" alt="screen shot 2016-09-26 at 20 26 05" src="https://cloud.githubusercontent.com/assets/3928502/18856322/d89a2e16-8427-11e6-9406-fc402131a089.png">
