### ISSUE TITLE
Hidden Exception

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2008]
### Steps to reproduce
1. Run the following model: 

model HiddenInAspect

global {
	init {
		create Human number: 2;
	}
}

species Human {
	point p;
	
	aspect default {
		draw circle(3) at: {p.location.x,p.location.y};
	}
}

experiment HiddenInAspect type: gui {
	output {
		display d {
			species Human;
		}
	}
}

2. This model contains an obvious NPE as p has not been initialized, but is used in the aspect.

### Expected behavior
I would expect an exception to be displayed in GAMA.

### Actual behavior
A NPE is displayed in the Eclipse console, but does not appear in GAMA.

### System and version 
GAMA Git latest version

**Comment by AlexisDrogoul** [comment]
Hi,

This is an unwanted effect of trying to minimize exceptions in displays. There is a great number of exceptions thrown (and "hidden") in Java2D and OpenGL, and its sometimes difficult to distinguish the "normal" ones from the "abnormal" ones. Since we have made some progress in the speed with which errors are now reported, maybe we can remove these limitations and allow errors to be reported for display operations. 

Alexis

**Comment by AlexisDrogoul** [comment]
To be more specific : all scopes have a method called `disableErrorReporting()`, which is explicitly invoked by the display surfaces when they initialize their own display scope. If we remove this, then all the errors will be displayed again normally. One solution (maybe) could be to make it a preference (display or not the errors emanating from the displays).

**Comment by AlexisDrogoul** [comment]
I've enabled this preference, which should normally be in effect in the latest versions. Setting it to true should enable the display of output runtime errors (beware that some are more or less unavoidable and will always be displayed...)
