### ISSUE TITLE
Supporting 'super'-like functionality in GAML

### ISSUE THREAD

**Issue by iamharshal** [gama-platform/gama#2009]
### Steps to reproduce

Currently, the actions of parent species are not accessible in child species. This is very important, because otherwise, one has to know, and perhaps re-implement entire functionality of the parent species action. 'super' keyword does this job in Java language, and is quite handy. I guess, if 'parent' is the keyword, one can chain also. For example, 'parent.action', 'parent.parent.action' and so on.

It will be wonderful to have this feature in GAML.
### System and version

GAMA 1.6.x, and perhaps GAMA 1.7.x too.

**Comment by iamharshal** [comment]
Thanks Alexis. Looking forward to have this feature in a future GAMA version.

**Comment by AlexisDrogoul** [comment]
As a side note, if we support a kind of super functionality like this, we won't support "chaining" (i.e. being able to write `parent.parent.action` as (1) it is really bad practice (i.e. bypassing your immediate parent) that is usually caused by design flaws; (2) I dont really see the point of it; (3) I dont know any language that offerts that (maybe I'm wrong).

Of course, you can always emulate it by having actions only calling super actions and being called by a sub-species.

**Comment by iamharshal** [comment]
Agree with you Alexis for chaining. In fact, our models too are encapsulated, meaning we access all species attributes through methods.

**Comment by AlexisDrogoul** [comment]
OK. This has been implemented -- with a minimum of efforts and changes to the existing (this explains some choices below).

Basically, invoking "super" actions consists in replacing `do` with `invoke` (when the action is not used as a function) and `self` with `super` (when it is used as a function). 

See the new example model called `Inheritance.gaml` in `Library Models>Features>Syntax`, which shows the use of these new keywords.

Reopen if any errors arise...
