### ISSUE TITLE
problem with sort operator and non-stable sort criteria

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2027]
### Steps to reproduce
1. test (run) the following model:
```
model testsort
global {
	init {
		create toto number: 100000;
		write ((toto where each.do_sort) sort_by each.val);
	}
}
species toto {
	bool do_sort <- flip(0.8);
	float val <- rnd(100.0);
}
experiment testsort type: gui;
```
### Expected behavior
No error

### Actual behavior
I get this error:

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:773)
	at java.util.TimSort.mergeAt(TimSort.java:510)
	at java.util.TimSort.mergeCollapse(TimSort.java:437)
	at java.util.TimSort.sort(TimSort.java:241)
	at java.util.ArraysParallelSortHelpers$FJObject$Sorter.compute(ArraysParallelSortHelpers.java:145)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)

**Comment by AlexisDrogoul** [comment]
`Arrays.parallelSort()` is unfortunately not very stable when it comes to sorting agents (esp. if they are themselves running in parallel !). 

I have a current implementation which will remove this bug. The immediate fix, before I commit it, is to use Arrays.sort() in the 'sort_by' implementation.

**Comment by AlexisDrogoul** [comment]
More simply, you can remove completely the block beginning with 

```
if (original instanceof List) {

```

**Comment by AlexisDrogoul** [comment]
Actually, after some investigation, the problem comes from the fact that parallelSort() (and maybe sort() also) need to evaluate several times the function on each agent. Since you have 2 random components in it, it is likely that it will not return the same value twice in a row. And this effectively violates the rules (for this particular implementation). 

Anyway, I've switched already to an implementation that maintains a state (i.e. a map) and which applies the function only once per agent (at the price of a sequential sort, as it would be too costly in that case to maintain the state across parallel threads).
