### ISSUE TITLE
Copy/paste in User model

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2043]
### Steps to reproduce
1.Add a folder in User model (e.g my project) by copying it in User Model

2. Delete it and then repaste another folder with the same name 

3.It's not possible to paste the folder, like if it was already there

### Expected behavior
One should be able to repaste the folder

### Actual behavior
No way to paste the folder (even with doing refresh metadata) 
Problems occurred copying the selected resources.
A resource already exists on disk '/Users/Arno/Projects/Gama/MIT/MarakAir/marrakAir/.metadata'.

### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)

**Comment by AlexisDrogoul** [comment]
How do you delete it ? If you dont delete the contents on disk, then this behavior is normal (you have the same in Eclipse).

**Comment by agrignard** [comment]
I delete it from GAMA GUI. Pressing delete. Ok so it means it's not anymore on the GUI but still on the disk. so not an issue right? For the user it's not very user friendly but it is how it is...

**Comment by AlexisDrogoul** [comment]
![delete resources 2016-11-07 23-31-10](https://cloud.githubusercontent.com/assets/579256/20065897/5d586baa-a542-11e6-98c1-db0350f204b3.png)

To delete it from disk, you have to check this box. If it is the case (i.e. you did it first) then it is a bug. Otherwise it is normal (and you have to delete the file on the drive in the OS).

**Comment by agrignard** [comment]
Ok sorry I think it did not checked this box before.

Everything is ok when I check it.
