### ISSUE TITLE
Invisible error when parameter with slider editor is initialized with a non-constant value (another variable)

### ISSUE THREAD

**Issue by jamesfpj** [gama-platform/gama#2044]
### Steps to reproduce
1.
Define variable in global block
e.g. int numberOfInfectedPeopleInit <- 2147 update: when people count (each.isInfected);
2.
Define parameter in experiment block
e.g. parameter "Number of Infected People" value: numberOfInfectedPeopleInit min: 1 max: 2147;
and of course some output display
e.g. display geom3D ...
3.
Run experiment and environment should displays some "display" contains one is named geom3D

### Expected behavior
The running screen should

### Actual behavior
The running environment is blank.

### System and version 
GAMA 1.7
JDK 1.8
OS: MacOS Serrier

**Comment by dphilippon** [comment]
Hi, 
could you be a little more precise on your model ? 
Because actually, the code in the steps contains a lot of error like : 
'update: when' which should not compile as when is not an operator, 
'parameter "Number of Infected People" value:'  where value is not a facet of parameter, it should be 'var:'

Because actually, just with the following model doing what I suppose you are trying to do, it works fine (I have the display in white with the name as given) 

````
model test

/* Insert your model definition here */

global
{
	int anExampleNumber<-2017 update: length(people where(each.isInfected));
	
	init
	{
		create people number:2200;
	}
}

species people
{
	bool isInfected<-false;
}

experiment test type:gui
{
	parameter "NB Infected" var:anExampleNumber min:1 max:2017;
	
	output
	{
		display test_display
		{
			
		}
	}
}

```

**Comment by jamesfpj** [comment]
Dear Prof. Damien,

I attached my project that contains the problem,

If you change the line
parameter 'Number of infected people' var: numberOfNotInfectedPeopleInit min: 1 max: 2147;
into
parameter 'Number of infected people' var: numberOfInfectedPeople min: 1 max: 2147;
and run the experiment you will see the issue.

Prof. Alexis asked me to report this issue during his course in USTH to improve GAMA

Best regards



James F. Parker (Mr.)
m. +84 974 02 03 05
skype: ducpmz
Hanoi, Vietnam

**Comment by dphilippon** [comment]
I cannot find any attachment in the issue (maybe I don't know where, or missing), could you send it to me by email ?

**Comment by jamesfpj** [comment]
Dear Prof Damien,

I did send via email but it seams to be not reach.
Could you please provide another email address (or your email address)

Best regards


James F. Parker (Mr.)
m. +84 974 02 03 05
skype: ducpmz
Hanoi, Vietnam

**Comment by AlexisDrogoul** [comment]
OK. I've taken a look at the model, and it comes from the fact that the initial value of the parameter is defined with reference to the value of a model global variable (and not directly a constant). This causes a problem for GAMA as, when the parameters view is opening, no simulation has yet been defined (actually, the simulation can only be instantiated  **after** the parameters have been computed). This simple model below illustrates the problem:

```
model a {
    int i <- 10;
    int p <- i;
}

experiment e {
    parameter "P" var: p;
}
```

In this model, the value of "P" is set to zero in the parameters, while it should normally be 10 (standard int editors accept nil values and simply turn them to zero, so we do not have errors).

If i now define "P" as `parameter "P" var: p min: 0 max: 100` (invoking the slider automatically), I get this blank window (because sliders use a special formatting that yields an 'invisible' IllegalArgumentException when the value is null). 

So we have two choices here:

- either we try to compute the value of the parameter as much as possible (in the context of the experiment), which should work in simple cases like this,
- or we emit an error saying that the `init` value of the parameter cannot be defined with a reference to another variable of the model. 

What is your opinion ?

**Comment by hqnghi88** [comment]
Dear Alexis, i prefer to have the 1st solution because it seems to work for my fixing-issue on comodeling.
Cheers.
