### ISSUE TITLE
any_location_in on a graph release vs current

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2046]
### Steps to reproduce
I have a model that compiles on release 1.7 but not anymore on the current git version

1.I use a  graph the_graph;
then I do this
location <- any_location_in(one_of(the_graph));

### Expected behavior
It compiles on the release version but not on the current one where I get the following error:

No operator found for applying 'any_location_in' to type unknown (operators available for [type geometry])

### Actual behavior
 I kind of understand why it's not compiling because we need to give geometry and not a graph but why is it compiling on the release version? Should it compile or not?

### System and version 
Current Git Version.

**Comment by AlexisDrogoul** [comment]
Depends what is in your graph. If there are no geometries, then it's normal that it doesn't compile. And if it used to compile, then it was not normal.  GAMA has become a bit more picky about the types since the release version, but it might be possible that some "false positive" are sometimes detected (esp. for complex types like graphs).

**Comment by AlexisDrogoul** [comment]
If you are sure that your graph contains geometries, and want to extract one from it, then you have to define it as a `	graph<geometry, geometry> the_graph;`. How do you declare and obtain it from ? (maybe the return type of some operators are not well declared as well).

**Comment by agrignard** [comment]
Ok I got it. 

I just wanted to understand why it's working one the release and not on the current one. As I am working with different people on that some of them are using the release and I personally used the current one (and I consider that this is the one that we used)

So the way the graph is built is
the_graph <- directed(as_driving_graph(road, dummy_node)) with_weights general_speed_map;
where road are creating from: roads_shapefile and dummy_node from: traffic_shapefile;

**Comment by AlexisDrogoul** [comment]
I think, in this particular case, that the problem comes from both the `directed` and `with_weights` operators, which did not correctly pass the key/contents types of the resulting graph. I have corrected it and it will be committed soon (possibly today). I have corrected other similar operators as well.

**Comment by agrignard** [comment]
I still have the error. Did you commit already?

**Comment by AlexisDrogoul** [comment]
How is "the_graph" created ? As a `graph<geometry, geometry>` or simply as `graph` ?

**Comment by agrignard** [comment]
Nice it was created as graph.

It's ok with graph<geometry, geometry> 

Thanks!
