### ISSUE TITLE
Animated Texture

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2070]
Could be nice to applied a video to a shape in the same way we apply texture

**Comment by hqnghi88** [comment]
I don't know if it' related but could it be possible to also have animated image (gif?)?

**Comment by AlexisDrogoul** [comment]
I have dropped any reasonable hope on implementing a full video->texture converter, as it would require bundling ffmpeg binaries, at least. However, I have implemented a complete solution for animated GIFs, which works quite well (with each GIF implementing its own timer to separate animations from simulation and OpenGL rendering). Since there are plenty of converters available to produce animated GIFs from videos, I will probably close this issue when it will be committed.

**Comment by agrignard** [comment]
This is great!! It will open a lot of possibility for realistic dynamic rendering using dedicated third software to produce the gif.

I agree that if the gif is working fine (especially if we can control independently the animations) maybe it make so sense to deal with video.
