### ISSUE TITLE
marker_size/marker_shape problem in charts

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2079]
### Steps to reproduce
1. test the following model:
model bugchart

global;

experiment bugchartxy type: gui {
	output {
		display phase_diagram  {
			chart "sin_cos" type: xy  
			{
				data "sin_cos" value: [sin(cycle),cos(cycle)]  marker_size: [0.1] marker_shape: marker_square color: #green style: dot;
			}	
		}
	}
}
### Expected behavior
marker_size and marker_shape should impact the chart display

### Actual behavior
Nothing change when I modify the value of these two facets

### System and version 
Github version

**Comment by AlexisDrogoul** [comment]
Not sure the marker_size and marker_shape have been implemented for other charts than `series`.

**Comment by AlexisDrogoul** [comment]
Actually they are working -- sort of. I have seen 2 problems so far, and I have tried to decipher the code, but I'm not completely sure to understand all the odd-names variables and their meaning (`svalues`, `pvalues`, etc.).
- first comes from the `dot` style. This makes use of a different renderer than the "standard" one (if you dont precise the style), where configuring the marker shapes is also different. I have added a case for this.
- second seems to come from the list you were using for the marker_size. When I set it to 1, it works. If I set it to a list, it remains blank (no marker displayed). I'm not completely sure to understand the meaning of this list, as somewhere in the code it is casted to float (and thus put to 0, which is why no marker is displayed !) -- I have thus changed the definition of this facet to only accept float values. 

I have modified the code accordingly, but I still have to test it. Will commit it as soon as possible.
