### ISSUE TITLE
consider replacing html with markdown for model documentation?

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2085]
Hi 

I was wondering if GAMA could introduce markdown as it documentation language for GAMA models and projects instead of the current html documentation of the model. I am referring here to the doc folder of a project. 

I am sure there exist a few open source java compatible libraries. eg.,
https://marketplace.eclipse.org/content/markdown-text-editor
http://www.winterwell.com/software/markdown-editor.php
I am not sure if the above can be integrated into GAMA or if they are just eclipse editors.

I think markdown is much simpler to learn than html and users can create easy model description and model usage guidelines ....something similar as it exists in other popular ABM software. This could be very encouraging for social scientists, and almost everybody who could document a model instead of writing comments in a model.

Thanks

**Comment by sriramab** [comment]
may be this one 
https://wiki.eclipse.org/Mylyn/WikiText

**Comment by sriramab** [comment]
This works with some plugins, I will post a description soon.

**Comment by sriramab** [comment]
I comeback to this to see if markdown can be an integral part of GAMA to be able to write markdown documents for users to describe their models.

**Comment by AlexisDrogoul** [comment]
@dphilippon @hqnghi88 What is the status of the Markdown add-on to GAMA (I remember it was related to what Damien had developed for documenting models).

**Comment by hqnghi88** [comment]
Dear Alexis,
It works. Benoit tested it with 1.8 and maelia . Damieno said that you said that it wont be integrated in the release because the markdown viewer plugin is not included , and he still have something to develope.

**Comment by dphilippon** [comment]
Hi everyone, 
Actually, it was for the UML Generator that I said that if I remember correctly. The markdown and the UML plugins can't be merged because they are for totally different people. While the markdown documentation can be useful for many users, I am not totally sure it is the case with UML. 

Regarding the Markdown plugin, I confirm what Nghi said, we tried it with Benoit, a small change was done by Nghi to export the ui.shared into the 1.8 repository ( if I understood correctly) because it wasn't the case before, so the plugin wasn't working with 1.8. But now it is.

**Comment by sriramab** [comment]
Aren’t These are independent issues? What Damien has now, builds a kind of table of contents for a model ie.,, it lists all the variables, attributes, reflexes etc

The documentation of a model however, per my request , is to be able to write/view a Markdown file in place of current GAMA feature for writing html documentation. 

Markdown can embed html if someone wants to make a complex document.

**Comment by dphilippon** [comment]
You can totally write markdown html in the markdown documentation plugin (see the screenshot). 

![screen shot 2018-04-05 at 6 07 44 pm](https://user-images.githubusercontent.com/15722750/38360267-4aeecfa0-38fc-11e8-8adc-ee792ef474ab.png)
You just have to write the html/markdown code in the /** */ comments. 
However, I see what you mean. It will still be, in a certain way, a table of content. So what you would like is to provide a folder "doc" (for instance) with just a basic markdown file with nothing written in it right ? 
Because as far as I remember, the html file provided in the previous doc folder (we do not have it anymore if I am correct) wasn't automatically generated. It was generated once the project was created but it would remain empty. The user had to write html code by him/herself if ever a documentation was needed.

**Comment by sriramab** [comment]
Yes, you are right. I mean a separate document where I can write /view md document. It also has the advantage when uploaded to github, it already becomes a well "formatted" model documentation.

**Comment by benoitgaudou** [comment]
I just tested: both the default documentation file is in md and the  markdown automatic generator are working.
So I close it, do not hesitate to reopen for new features !
