### ISSUE TITLE
Normal should not be displayed for polygons in OpenGL

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2087]
### Steps to reproduce
1. Test this simple model:
model drawPolygon
experiment drawPolygon type: gui {
	output {
		display view type: opengl {
			graphics "square" {draw square(20) color: #yellow;}
		}
	}
}

### Expected behavior
Only the yellow square should be displayed

### Actual behavior
In addition, the normal vector (red arrow) is displayed.

**Comment by nordie69** [comment]
I can confirm, that this behaviour is the same here at my system environment (Windows 8.1). My model changed it's behaviour a few GIT builds ago like Patrick described it.

Thanks,
Stefan

**Comment by agrignard** [comment]
Yep something is wrong indeed.

I know that Alexis did a lot of refactoring in the Opengl Part one or 2
weeks ago in that kind of commit for instance

https://github.com/gama-platform/gama/commit/55ce179dc8a7c7d09f704fbc85d4f9cda27cd9b1

Quickly:

Why isDrawingNormals is et to true by default? this is one of the reason
basically the normal are drawn in GLUtilNormal.HandleNormal(vertices,
p_norm_dir, renderer); because we set this value to true

On top of that I notice some strange behavior in Opengl (something like if
the scnee was redrawn every frame) I am digging a bit more on that.

**Comment by agrignard** [comment]
One quick way to solve this issue is to remove
GLUtilNormal.drawNormal(vertices, renderer, gl, normal); in
drawTesselatedPolygon of JTSDrwar.java but I prefer Alexis to do it as I
did not follow all the change made on this topic

**Comment by AlexisDrogoul** [comment]
Yes I confirm it was my fault -- and I should have made the simple fix before, but I'm still struggling with the refactoring of the code. Normals are essential to obtain a correct rendering and I needed to display them. Sorry for that. The fix made by Arnaud is ok, but will be reverted some time in the future.

**Comment by nordie69** [comment]
I am happy to see, that now everything works fine again with the latest GIT version and my model (see attached screenshot). Thanks and keep up the good work. Maybe one day I will be able to helpwith issues like that ....

Stefan

![clipboard01](https://cloud.githubusercontent.com/assets/10273646/21869555/7606de40-d858-11e6-8ddc-65c9512ad4eb.jpg)
