### ISSUE TITLE
Increase of computation time per step during simulation (Quadtree problem ?)

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2094]
### Steps to reproduce
I am not quiet sure and I am trying to reproduce it on different model but I have the feeling that the average duration of a step is now increasing as the simulation is running when the display  is used and sync (java or opengl).

I am experiencing this on my current model but I also can reproduce it on some model of the libray for instance:

Boids 3D Analysis 
Ant Foraging Complex

### Expected behavior
The cycle duration should be constant.

### Actual behavior
When the display is synchronize it always increasing. It seems related to the display as the duration does not increase if the display is not sync.

### System and version 
Git version

**Comment by nordie69** [comment]
Hi guys,

I would like to add some comments here. What is being described above is something, I am having with my model, too. I am adding 3 charts to this posting, the first with the total execution time of the model, the second with the execution time per simulated day and the third one with the total quantity of agents beeing simulated. The form of the execution time curve should be similar to the curve of the total quantity of the agents in the third chart! This is NOT what I am seeing in my simulation - the execution time stays on a high level (which will be okay for the middle of the year) but at the beginning an and at the end of the year, the amounts of time per day should be on the same level (which is not). Due to this I can confirm, that the execution time is increasing with the amount of cycles. In my models I have simulated 52.560 cycles with the latest GIT version from today.

Stefan

![execution time](https://cloud.githubusercontent.com/assets/10273646/21871354/ede8ffe8-d861-11e6-8318-e51507d2be25.png)
![expected form of the curve](https://cloud.githubusercontent.com/assets/10273646/21871353/ede8c294-d861-11e6-816a-bd457e382b43.jpg)

**Comment by agrignard** [comment]
This is issue is quiet critical I think.

After some quick profiler with Patrick it seems that it comes from a problem in the QuadTree especially when computing inside a cell. Maybe something related to "concurentLinkedQueue"?

Anyway any help on that would be really appreciated

**Comment by ptaillandier** [comment]
To be more precise, the problème seems to come from moving agents with a geometry that is not a point:

Test model:

model CityGamatrix   

global {
	init { 
		 create people number: 500 {
		 	shape <- square(0.5);
		 	location <- one_of(cityMatrix).location;
         	do findNewTarget;
        }
	} 
} 

grid cityMatrix width:16  height:16 {
	bool is_free <- flip(0.9);
	rgb color <- is_free ? #white : #black;
	int occupancy;
	
	reflex updateOccupancy{
		occupancy <- length(people inside self);
	}
}

species people skills:[moving]{
	point target;
	rgb color <- rnd_color(255);
	path my_path;
	
	aspect base{
	  draw circle(1) color:color;		
	}
		
	action findNewTarget{
		target <- one_of(cityMatrix where (each.is_free)).location; 
        my_path <- (cityMatrix where (each.is_free)) path_between (location, target);		
	}
	reflex move{
		do follow path:my_path;
		if (target = location){
			do findNewTarget;
		}
	}
}

experiment Display  type: gui {
	output {
		display cityMatrixView    background:#black {	
			grid cityMatrix lines: #black;
			species people aspect:base;
		}
	}
}

**Comment by AlexisDrogoul** [comment]
Is it "quiet" critical or "quite" critical :) ? As a matter of fact, the increase of computation time, if the agents move in every portion of the environment during the simulation, is normal: the quadtree distribution will tend to increase (and its efficiency will tend to decrease, unfortunately: in the worst case, it will reach the complexity of a simple implementation, for instance one based on sorting the agents on their x ordinate). In the current implementation, this tendency is reinforced by the use of concurrent data structures that can potentially support parallel accesses by agents (at the expense of memory and speed). So yes, it is "normal". 

The only way to counterbalance this tendency (which would the same in other data structures, btw) is to implement some "backpressure" or "garbage collecting", by rejoining, from time to time, the cells that are empty. However, the problem is to decide when to do it. At the end of every step ? Every n steps ? There is no rule for that -- and it may actually slow down the model a lot if it is done in a very dynamic simulation with thousands of agents moving.

In any case, there is a need here to (1) measure the split of the quad tree and the size of the collections in each node; (2) do it by removing the display, to clearly separate the concerns.

**Comment by AlexisDrogoul** [comment]
Turns out it was a completely different issue. The "new" JVMs we are using (JDK 1.7 or 1.8) have enforced a number of rules regarding compiled class members defined as protected or private. While it was possible in JDK 1.6 to access them almost at full speed (with a sanctified hack provided by Sun), it is now much less efficient and it severely degrades the whole performances of an application. Probably a reason of security or checked exceptions, I dont know. However, the cause of the continuous degradation was the call to getEnvelope() in GamaShape, which used to access the private `envelope` field of the underlying JTS Geometry. This was a choice made to preserve memory (having 2 envelopes, one in 2D in the JTS Geometry, one in 3D in GamaShape, is in fact stupid) -- but it turns out it was a bad choice. I reverted it, this time by choosing a different strategy: first, I sped up the construction of the 3D envelope by relying on the new `GamaCoordinateSequence` class, introduced in the previous batch of commits (by assuming only one type of `CoordinateSequence`, a move enforced by the `GamaGeometryFactory`, we can speed up a lot of things as we only have to browse an array of `GamaPoint`), with the added benefit of almost no intermediary object instantiation. Second, I removed altogether all references to the envelope in GamaShape, relying only on their dynamic creation when necessary (through the `getEnvelope()` method).
The speed up is impressive (even at the beginning of simulations) and the effect on memory almost unnoticeable (however, we need to chase the calls to `getEnvelope()` which were assuming that the envelope was cached). I will commit as soon as possible after testing it.
