### ISSUE TITLE
Moving the OpenGL backend to LWJGL ?

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2110]
For a number of reasons, the current JOGL backend, although correctly running, is beginning to show its age. The first concern is about the maintenance and updates of JOGL, which is lagging to say the least: outstanding bug fixes happen very rarely (the last update dates back from almost 2 years). In comparison, LWJGL is updated much more frequently.  The second is about the absence of bindings, in JOGL, to potentially extremely useful libraries (like [NanoVG](https://github.com/memononen/nanovg), which could make drawing texts much easier), which are included for free in LWJGL. The third one is about the absence of correct and reliable routines for loading/saving 3D objects (retrieving a correct OBJ loader for JOGL has been quite painful, while LWJGL comes with a very robust one and also includes bindings for [Assimp](http://www.assimp.org/)).

We have to discuss this and to investigate the expected benefits and drawbacks of such a move. Feel free to add your opinion in the comments.

**Comment by agrignard** [comment]
I am not against (Assimp and NanoVG looks great) but we know that will impact a lot and need lots of testing.

Before to do this "HUGE" change I think we must release a 1.7 stable version using jogl in order to be sure to have a "stable" and "working" released version. we can then start the big refactoring.

When I check the actual Opengl issue they are all related to shader or keystoning (which are improvements ant not real bug) it means that there is no current important opengl issue.

**Comment by AlexisDrogoul** [comment]
I remove this request for enhancement given the relative lack of support of LWJGL regarding the simultaneous use of multiple GL contexts (and hence multiple views). Having something like NanoVG would be however great for texts, and having Assimp bindings would be great too...
