### ISSUE TITLE
rotate facet called at each frame

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2112]
The rotate facet seems to do a bit more than its job ;-)

It rotates at each frame now

Expected behavior:
the view is rotated once but not at each iteration.

**Comment by AlexisDrogoul** [comment]
Ah ok. I thought the goal of this facet was to replicate the "Rotate" menu command found in the display view. I will commit the fix soon (easy to do). 

But, in that case, isn't it redundant with the orientation of the camera ? And, to be consistant, shouldn't it take a pair angle::axis like in the draw command ? 

Probably we have to think about harmonising the different transformations, since, for me, the camera_xxx statements are used to specify an affine transform (with some duplicates found with the zoom: [scaling] and rotate: [rotation about z] facets, as well as the position: [translation], size: [scaling] facets of individual layers), while keystone specifies non-affine transforms. 

Having too many facets that overlap is not a good thing in my opinion. Maybe eliminating the "up-vector" (orientation) of the camera and replacing it with this "rotate" facet with an angle or a pair angle::axis would be more convenient ?

**Comment by agrignard** [comment]
Yeah I agree there is some redundancy here... and yes a pair would be more coherent. 

however if you think about the java2D display there is no camera so a rotate make sense. 
Also it might be difficult for the "novice" user to figure out how to use the up_vector in order to make its rotation.
