### ISSUE TITLE
Gama & Unity 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2131]
I opening an old idea/enhancement that we already discussed a bit but I would like to get a bit further on that.

It would be great (and would open many new opportunities) to display a Gama Simulation in a high level 3D renderer like Unity. I am not saying that the current java2D or Opengl are useless they are a must have but they show some known limit in term of realistic and performant rendering. 

I have discussed a bit in my lab with some Unity Guru and it seems that one straightforward option would be to ask GAMA Agent to send a udp information (with at least its position) to Unity.

If you think of it many massive player online game rely on this technic: position, used weapons, super power are send to a big unity server and then the rendering is updated according to those information.

So I think one good way would be to use the network skills in order to ask an agent to send its position through udp. I don't know the current state of the network plugin but it used to work with udp.

Why Udp because it's one of the fastest communication protocol, the only drawback is that sometime some package can be lost but as it is only for visualization purpose it's not a big deal if one agent is sometime not displayed.

**Comment by hqnghi88** [comment]
Hi Arnaud,
The last time that i've worked on Network plugin, the Battle Ships of Damien worked well. But it was before two big commits. I test tomorrow and let you know. But i have no idea about the Unity factor.

**Comment by agrignard** [comment]
I close this issue as it's clearly a long term high level enhancement and not an issue at all.

**Comment by agrignard** [comment]
Hi everyone,

By having a look in the experimental repo of GAMA I see that @ysklab seems to work on a Unity project link to GAMA:
ysklab/Scene-GamaUnity

Maybe this can answer to some of the question raised in this issue?

**Comment by AlexisDrogoul** [comment]
And maybe this could be moved to https://github.com/gama-platform/gama.experimental/issues instead, no ? 😄

**Comment by ysklab** [comment]
Hi,
I have started working on this idea since a couple of weeks. The right repository is: 
ysklab/UnitySceneWithGama, which consists of a Cube-Collector game, where a Gama agent moves a ball in a Unity scene in an attempt to collect cubes. After having the total collected cubes reached the needed number (the latter is indicated by the Gama agent at the beginning by mean of notification subscribe message), a notification message from unity to Gama agent is sent, thus, ending the game. Other functionalities are available. I will describe how the whole things work soon.

**Comment by agrignard** [comment]
Issue has been moved to https://github.com/gama-platform/gama.experimental/issues/14
