### ISSUE TITLE
Developing plugins states svn

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2151]
The wiki page on developing plugins still describes use of svn! Is this still correct or should it be github ?

Thank you
Srirama

**Comment by benoitgaudou** [comment]
Hi Srirama,

I suppose that all the page is correct but the SVN part (about sharing an
extension).
In fact I am not sure of the actual p2 repository (repository for the
extensions).

Cheers

Benoit

2017-03-09 19:02 GMT+01:00 Srirāma Bhamidipāti <notifications@github.com>:

**Comment by AlexisDrogoul** [comment]
The recent commits by @hqnghi88 will allow to put plugins in the experimental repository and have them published on a p2 repository available for all users -- instructions will be provided as soon as it is ready.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 Everything is now ready for developers of plugins to use the https://github.com/gama-platform/gama.experimental repository and benefit from an automated update/install repository (http://updates.gama-platform.org/experimental). We just need to document it (in order to get rid of the documentation on the SVN repository, which doesn't work anymore).

**Comment by AlexisDrogoul** [comment]
The page https://github.com/gama-platform/gama/wiki/DevelopingPlugins now has a draft version of the final documentation using GitHub `experimental` repository. Please check (the old doc is marked as `obsolete`).  Thanks @hqnghi88 !

**Comment by AlexisDrogoul** [comment]
I propose to close this issue (now fixed by the new documentation). Reopen it if you feel this doc should be clearer/different
