### ISSUE TITLE
I want to know how to use "agents_inside (unknown)" in GAMA,who can give me a model?

### ISSUE THREAD

**Issue by songweizhen** [gama-platform/gama#2152]
I want to know how to use "agents_inside (unknown)" in GAMA,who can give me a model?

**Comment by ptaillandier** [comment]
Hi,

You can just write something like:
list<agent> agents_inside <- agents_inside(a_geometry);
However, if you are only interested by a specific list of agents or a
specific species of agents, you should rather use the inside operator:
list<people> people_inside <- people inside a_geometry;

Cheers,

Patrick

2017-03-14 6:30 GMT+01:00 songweizhen <notifications@github.com>:

**Comment by benoitgaudou** [comment]
Dear,

Your message is not related to an issue into the Gama Platform but rather a question about its use.
As a consequence and for similar future questions, please use the GAMA mailing list (gama-platform@googlegroups.com) instead of the issue track.

As a consequence I close this "issue".

Cheers

Benoit
