### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by schell0385** [gama-platform/gama#2163]
Hello,

I would like to download the documents and tutorials to my computer - is there a way to do this?

Or. must I use the tutorial from your website only?

Thank you.
L

**Comment by hqnghi88** [comment]
77

On Apr 2, 2017 10:11, "schell0385" <notifications@github.com> wrote:

Hello,

I would like to download the documents and tutorials to my computer - is
there a way to do this?

Or. must I use the tutorial from your website only?

Thank you.
L

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gama-platform/gama/issues/2163>, or mute the thread

**Comment by AlexisDrogoul** [comment]
Hi, 

As far as I know, this issue list is not a place to ask questions. Please ask your questions on the gama-platform mailing-list: https://groups.google.com/forum/#!forum/gama-platform

Cheers
Alexis
