### ISSUE TITLE
strange envelope output + no OpenGL display

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2165]
### Steps to reproduce
1. I used a polygon1 as envelope of the world and also as species. I used polygon2 in graphics draw. Both polygons are of the same area and in same projection. They appear next to each other.

2. I used a polygon2 as envelope of the world. I used polygon2 in graphics draw. And polygon1 as species. Both polygons are of the same area and in same projection. They appear top of each other.

3. Java2D gives a display, OpenGL gives no display at all.

### Expected behaviour
Same area same projection I expect to be overlapping

### Actual behaviour
They appear next to each other.

### System and version 
Which version of GAMA standalone RC1+updates, JDK 8, macOS ... 

![next](https://cloud.githubusercontent.com/assets/12668606/24661434/a94586c2-1952-11e7-9c7b-a2019ecfaf24.jpg)

![overlap](https://cloud.githubusercontent.com/assets/12668606/24661443/af0571d0-1952-11e7-8d2f-90f714859f09.jpg)

![gama installation details 2017-04-04 16-23-03](https://cloud.githubusercontent.com/assets/12668606/24661596/1333d1ec-1953-11e7-8236-1a34ee0525c9.jpg)

**Comment by AlexisDrogoul** [comment]
Sorry -- I've some difficulties to follow your logic.. Can you reproduce it with a very simple model (and post it) ? Furthermore, same area + same projection does not mean equal if your two polygons have different locations.

**Comment by sriramab** [comment]
By area I mean same location, not area as in measured area.
I think it looks like error with multipart features from Arcgis . I am
investigating.

**Comment by sriramab** [comment]
I could not resolve the problem. OpenGL does not give any display. I corrected some multipart features from GIS software but still some discrepancy remains. I attach here the model and the files. try changing between OpenGL and java2d & try changing envelope to either files. 
[display_opengl.zip](https://github.com/gama-platform/gama/files/895220/display_opengl.zip)

**Comment by AlexisDrogoul** [comment]
I've already addressed the "no display" part, due to the combination of `color:` and `empty:`: GAMA failed in identifying the color as the border in that case. However, for the second problem (no overlapping), this is what I obtain in Java2D, first, and OpenGL, second:

![worldsetup - users drogoul downloads eindhoven_abcd models world_setup gaml 2017-04-05 23-32-11](https://cloud.githubusercontent.com/assets/579256/24716227/79cd8c94-1a58-11e7-8082-fe489c4f25c1.png)
![worldsetup - users drogoul downloads eindhoven_abcd models world_setup gaml 2017-04-05 23-34-00](https://cloud.githubusercontent.com/assets/579256/24716228/7a0ea9cc-1a58-11e7-94a2-3f979d58df7f.png)

So there is still a problem here.

**Comment by AlexisDrogoul** [comment]
However, if I transform the "extent" into an agent and display it, it works well in both cases (dont mind the colours):

![worldsetup - users drogoul downloads eindhoven_abcd models world_setup gaml 2017-04-05 23-40-56](https://cloud.githubusercontent.com/assets/579256/24716489/69362b6a-1a59-11e7-96a9-46d5697defc0.png)
![worldsetup - users drogoul downloads eindhoven_abcd models world_setup gaml 2017-04-05 23-41-19](https://cloud.githubusercontent.com/assets/579256/24716492/6a043b68-1a59-11e7-96f8-cbecde82c517.png)

So the problem is somewhere in the initialisation of the `graphics` section.

**Comment by sriramab** [comment]
Thank you for your time. Have you made a commit already ?

**Comment by AlexisDrogoul** [comment]
I've pushed two fixes : (1) the above mentioned one; (2) a new fix that avoids translating GIS data (normally already translated) to the position of their "agent". Tell me if it works (it does for me).

**Comment by sriramab** [comment]
Yes, it works on both layers and both displays. Thank you.
