### ISSUE TITLE
Better way to log/debug plugin load or execution ?

### ISSUE THREAD

**Issue by reyman** [gama-platform/gama#2171]
Hi,
This is more a question or an enhancement than a real issue.
I created a plugin for Gama (Gen* plugin) which contain some new gaml primitive. I try many thing but Gama don't find any of this primitives. 

Is there a better way to log / debug (*.txt or other) the process of loading for extension ?

**Comment by AlexisDrogoul** [comment]
Actually, the primitives identified by the annotation engine are available in the `gaml` folder within your plugin. That's the first step: if nothing is present, then the annotation engine is failing. Otherwise, the primitives should be loaded. If you need it, I can add some debugging information on that point.

**Comment by reyman** [comment]
Hi @AlexisDrogoul , 
When you ask about "gaml file into gaml folder", this is 
- a) into the plugin jar, 
- b) into the plugins folder of gama  ?

The plugin (a) exported by gradle contain a ` gaml > additions > *.class / .java` folder. In the (b) case, i have only the plugin jar.

**Comment by AlexisDrogoul** [comment]
I come back to this one as I seem to have misunderstood your initial question. The best way to debug what's happening when GAMA plugins are loaded is in msi.gaml.compilation.kernel.GamaBundleLoader, in the method preBuildContributions(). If your plugin is not recognised or not loaded, this is where you might get information.
