### ISSUE TITLE
GAMA Type creation not working

### ISSUE THREAD

**Issue by stouhbi** [gama-platform/gama#2173]
### Steps to reproduce
1. I created a type Dummy (and the file DummyType see the attached files) 

2. I tried to call the type in Gama using an operator 
`dummy dumdum <- createdummy("hey", 12.0);`

### Expected behavior
Tell us what should happen (include all relevant expectations)
It should create a type dummy
### Actual behavior
Tell us what happens instead (include relevant information, like logs, snapshots, etc.)
it does not work,  it gives me an error 

> The primitive or action 'createdummy' cannot be resolved (either
>    it is not defined or not accessible)

why is the operator not working ? can I create an instance of this type without using an operator ?
### System and version 
Which version of GAMA, JDK, OS ... (if necessary, copy Help>Installation Details>Configuration in GAMA)
Gama : 1.7
OS : OSX
JDK : 1.8.0_101

[codeTYpe.zip](https://github.com/gama-platform/gama/files/909855/codeTYpe.zip)

**Comment by AlexisDrogoul** [comment]
Sorry, I dont completely understand. When you define a type (say `dummy`), you need to redefine the casting method and this gives you automatically a casting operator (called `dummy(...)`) that you can use to create instances. However, the constructors defined on your java Dummy class are not taken into account and you have to invoke them manually. The casting method takes one argument (and it's up to you to write it so that it returns, with respect to this argument, a `Dummy` instance or null). If you want to have operators creating `Dummy` instances with more arguments, you have to define them yourselves (like you would define constructors). Finally, the `wraps` annotation is here to indicate which Java class is "wrapped" by this GAML type. In your case, it should be `Dummy.class` (not String.class and Float.class, which indicates that a `dummy` object in GAMA could be a string OR a float !).

**Comment by stouhbi** [comment]
For the wrap I thaught that we put the classes that this type uses. I've corrected it. 
However I can't see to get the operator `dummy() ` working. The casting method is redefined in the DummyType class and I tried a simple redefinition : 
```
@Override
	public Dummy cast(IScope scope, Object obj, Object param, boolean copy) throws GamaRuntimeException {
		return (Dummy) obj;
	}
```

but I get the error `Unknown action or operator: dummy` when i try to get an instance of this type in global like this  : 
`dummy dumdum <- dummy("word", 12.0);`
am I writing it wrong ?
I can't see to get the link between the cast method and the declaration in GAML, I know that obj refers to the obj created in GAML, but what about the parameters `params` and `copy`

**Comment by AlexisDrogoul** [comment]
Is your plugin correctly loaded in GAMA ? Moreover, `dummy` should only take one argument. `param` is used in some types (only container types, basically) and `copy` tells whether or not you should create a copy of the object (if you happen to pass it a `dummy`).

**Comment by stouhbi** [comment]
The plugin is correctly loaded, It recongnizes the types and skills i created. 
So you are telling me that I can't create from scratch an instance of type dummy with the default operator `dummy()` ? If not, how can I assign the values to the attributes of my instance ?
Thanks,

**Comment by AlexisDrogoul** [comment]
Well, you have to create constructors (identical to other operators). One is provided to you for free (the `dummy` operator with only one operand, that you can program in the casting method). For instance, if you can create a dummy from a string, then you test in your casting method whether the object passed is a string and you create your Dummy object from there. Or you can create an operator called `dummy` with one String argument. And if you have more complicated constructors, then you create the corresponding operators (e.g. one with a String and a Float, etc.).

**Comment by stouhbi** [comment]
Okey thanks I understand now.
