### ISSUE TITLE
The lost world of R connection, Matlab connection

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2197]
Dear GAMA team

I remember there was (is) an R communication with GAMA. I have looked at the documentation and most of the operators are still working except the one which allows sending parameters from GAMA to R: ` R_compute_param` .

Could someone please look into reviving this? At the university there is a lot of demand from students to use their matlab and R codes. I understand matlab is a commercial, but it would be nice to interacting with R from GAMA.  May be there are better and efficient  java-R libraries than there were a few years ago. I would really like to request for bringing this feature back to life. 

Thank you.

**Comment by sriramab** [comment]
May be you find this useful: http://www.renjin.org 
or this small tutorial http://www.studytrails.com/rjava-eclipse-plugin/jri-r-java-data-communication/

**Comment by hqnghi88** [comment]
Hi Sriri,
Thanks for the suggestion, i return in few days for the results.

**Comment by sriramab** [comment]
Thank you Nghi

**Comment by hqnghi88** [comment]
Hi,
I've just deployed the RJava plugin in Gama. If you are using not-too-old Gama release, you can install the RJava from your release by go to menu Help->Install new software -> enter http://updates.gama-platform.org/experimental to the textbox --> wait a sec and select the RJava in the list ->Next -> Finish.

Because RJava use other packacge (called jri) so it require to specify the path to jri. PLease go to Gama Preference -> External tab -> Browse to the jri folder of RJava (the RJava must be installed in R's library) -> Save.
Then you can test this model, replace the r file with yours.

model RJava
global skills:[RSkill]{
	init{
		file Rcode<-text_file("aidwork1.r");
		loop s over:Rcode.contents{
			list a<- R_eval(s);
			write a;
		}
	}	
}
experiment RJava type:gui{
	output{
	}
}
The RJava support almost data type of R in JAVA, but i am not expert in R so if you encounter or wanna the R-eval return a specific data type, please let me know. For instant, it can return list for Factor, Vector, and String for other R's type.

Regarding MATLAB, i think about it for a long time but i do not find a license to begin the integration. So if anybody have a suggestion it would be nice for the development.

**Comment by sriramab** [comment]
Hi Nghi,

Could you tell me how I can send parameters from GAMA to R?

**Comment by hqnghi88** [comment]
Hi Sriri, i did not try that but how can you pass param in R when you
import a .R file? Or you can try to writeseveral r_eval , i.e,
do R_eval("x<-"+aVar);
do R_eval("print x");
To see if variable x will take the value of aVar from Gama.

**Comment by sriramab** [comment]
Please advice, Which file in JRI must I point to?

**Comment by hqnghi88** [comment]
Hi, on macos you should point to libjri.so . But i need to update the code .

**Comment by AlexisDrogoul** [comment]
Hi, any updates on this one ? Does it work ? I'm a bit lost in the comments.

**Comment by hqnghi88** [comment]
No, it stop at "pointing to libjri.so". Something is different between W and M Os but i haven't found yet. I'll find time to rework on it.

**Comment by sriramab** [comment]
Yes, this would be nice. At least if values of gama variables can be sent to R and get a return from R as  int, float, list, matrix(dataframe) back into a gama variable. This would already be a great step as most R objects can be coerced into these basic data types. The complex r objects may be left for a second iteration/ update.

Thank you for your time Nghi.

**Comment by sriramab** [comment]
I and Nghi were working on this today, and it seems to work. Main issue on mac was to define a global environment variable in `launchd` (reboot needed). Nghi is now refining the variable exchange.

needs use of `sudo nano /etc/launchd.conf` to define 

`setenv R_HOME /Library/Frameworks/R.framework/Resources`

**Comment by sriramab** [comment]
This is more or less working for simple scripts and except for plots. I close it for now. May be it can be revisited. Thank you Nghi.
