### ISSUE TITLE
distance_to produces weird values in Grid Topology when getting euclidean distance of cells

### ISSUE THREAD

**Issue by allanlao** [gama-platform/gama#2217]
### Steps to reproduce
Run the following model

model nav

global {
	init{
		ask cell{
			float d <-  cell[1,1].location distance_to self.location;
			write "distance of " + cell[1,1].name + " to " + self.name + " is " + d;
		}	
	}
}

grid cell width:3 height:3 neighbors:8{
	aspect base{
		draw name + ":" +grid_value color:#black;
	}
}

experiment nav type: gui {
	
}

### Expected behavior

Distance from center cell of moore neighborhood to diagonal should be 1.4
and distance to lateral cells should be 1.0

### Actual behavior

Distance to all cells at neighbour_1 is 0.0 for some cells and 2.0 for other cells

### System and version 
GAMA 1.7 and 1.6 All OS

**Comment by dphilippon** [comment]
Hi Allan, 
everything works fine on my computer with a Moore neighbourhood (I used the model you gave to use in the post) : 
````
distance of cell4 to cell0 is 1.0
distance of cell4 to cell1 is 1.0
distance of cell4 to cell2 is 1.0
distance of cell4 to cell3 is 1.0
distance of cell4 to cell4 is 0.0
distance of cell4 to cell5 is 1.0
distance of cell4 to cell6 is 1.0
distance of cell4 to cell7 is 1.0
distance of cell4 to cell8 is 1.0
````
Which is totally fine for a Moore neighbourhood since the operator distance_to uses the topology of the agent calling it (ie the grid). So when you have a Moore neighbourhood, all your 8 neighbours are at distance of 1.0 considering the grid as a reference system (the distance equals to 0.0 is the distance between the central cell and itself, so totally normal). 

When I change your model to use a Von Neumann neighbourhood, I got this : 
````
distance of cell4 to cell0 is 2.0
distance of cell4 to cell1 is 1.0
distance of cell4 to cell2 is 2.0
distance of cell4 to cell3 is 1.0
distance of cell4 to cell4 is 0.0
distance of cell4 to cell5 is 1.0
distance of cell4 to cell6 is 2.0
distance of cell4 to cell7 is 1.0
distance of cell4 to cell8 is 2.0
````
which is, once again, totally correct (as I told you, the operator distance_to uses the topology of the agent calling it, the neighbours of the central cell are at 1.0 and the others at 2.0). If you want to use the real distance (and not the distance in terms of cell for the grid), you must change the topology to world, so you can use the operator distance_between like this : 
````
model nav

global {
	init{
		ask cell{
			float d <- cell[1,1].location distance_to self.location;
			float f <- topology(world) distance_between([cell[1,1].location,self.location]);
			write "distance of " + cell[1,1].name + " to " + self.name + " is " + d;
			write "real distance of " + cell[1,1].name + " to " + self.name + " is " + f;
		}
	}
}

grid cell width:3 height:3 neighbors:4{
	aspect base{
		draw name + ":" +grid_value color:#black;
	}
}

experiment nav type: gui {

}
````
You can see that I used your model and just added a new variable f that will contain the result of the operator distance_between and I just write the result. 
Here is the output : 

````
distance of cell4 to cell0 is 2.0
real distance of cell4 to cell0 is 47.14045207910316
distance of cell4 to cell1 is 1.0
real distance of cell4 to cell1 is 33.33333333333333
distance of cell4 to cell2 is 2.0
real distance of cell4 to cell2 is 47.14045207910317
distance of cell4 to cell3 is 1.0
real distance of cell4 to cell3 is 33.33333333333333
distance of cell4 to cell4 is 0.0
real distance of cell4 to cell4 is 0.0
distance of cell4 to cell5 is 1.0
real distance of cell4 to cell5 is 33.33333333333334
distance of cell4 to cell6 is 2.0
real distance of cell4 to cell6 is 47.14045207910317
distance of cell4 to cell7 is 1.0
real distance of cell4 to cell7 is 33.33333333333334
distance of cell4 to cell8 is 2.0
real distance of cell4 to cell8 is 47.140452079103184
````
But once again, this operator is dependant to the topology you use (here I used the world, so the units given by the distance are related to the "shape" of the world... If I precise a different shape for the world ```geometry shape <- square(1.0);```, the "real distance" will be different 
````
distance of cell4 to cell0 is 2.0
real distance of cell4 to cell0 is 0.47140452079103173
distance of cell4 to cell1 is 1.0
real distance of cell4 to cell1 is 0.33333333333333337
distance of cell4 to cell2 is 2.0
real distance of cell4 to cell2 is 0.4714045207910317
distance of cell4 to cell3 is 1.0
real distance of cell4 to cell3 is 0.33333333333333337
distance of cell4 to cell4 is 0.0
real distance of cell4 to cell4 is 0.0
distance of cell4 to cell5 is 1.0
real distance of cell4 to cell5 is 0.33333333333333326
distance of cell4 to cell6 is 2.0
real distance of cell4 to cell6 is 0.4714045207910317
distance of cell4 to cell7 is 1.0
real distance of cell4 to cell7 is 0.33333333333333326
distance of cell4 to cell8 is 2.0
real distance of cell4 to cell8 is 0.47140452079103157
````

For more clarifications, you can look at the documentation.
I close this. Feel free to open it once again if you have different results from mine using the models I gave you.
