### ISSUE TITLE
just move the mouse when a rotate scene is activated make the rotation speed increase

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2224]
Not a big deal but it might fix or give an hint to fix other issues related to opengl.

When the option rotating scene is activated I just notice a strange behavior (I am not sure it was here before ), if you just move the mouse (not even press it) the rotation is getting faster. This is kind of weird I don't see what can be the link between moving the mouse and increasing the rotation speed.

### Expected behavior
The rotation speed should be constant

### Actual behavior
Rotation speed incresase (almost proportionally) when the mouse moves

### System and version 
GAMA 1.7 RC2

**Comment by AlexisDrogoul** [comment]
This is due to the synchronisation between SWT (mouse) and OpenGL threads. It seems that the GLDrawable, when synchronising the 2, emits a supplementary `display()` message. I have deactivated this synchronisation from now on, but I know it had been set earlier because of possible conflicts (between SWT / OpenGL and the simulation threads).
