### ISSUE TITLE
Accumulate agents from several grid species

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2237]
### Steps to reproduce
1. I have a simple weather model  with a single grid species (plotWeather).
[Co-models.zip](https://github.com/gama-platform/gama/files/1299482/Co-models.zip)

2. I create a co-model, creating 3 instances and I want to display all the agents of plotWeather from the 3 simulations.
```
import "weather.gaml" as weather


global {
init {	
		create weather.weather_coModeling number: 3 {
			write "" + int(self) + " " + self;
		}

		write "";
 		write "**** Display set of agents ****";
		write "" + weather.weather_coModeling accumulate (list(each.simulation.plotWeather));
		write "" + weather.weather_coModeling collect (each.simulation.plotWeather);
		
		write "" + length(first(weather.weather_coModeling).simulation.plotWeather);
		
	}
}
```
3. I first check I have created some agents (at least in 1 of the simulations) with: 
```
	write "" + length(first(weather.weather_coModeling).simulation.plotWeather);
```

4. I tried to display the plotWeather agents for all these simulations with either:
```
        write "**** Display set of agents ****";
```
```
	write "" + weather.weather_coModeling accumulate (list(each.simulation.plotWeather));
```
```
	write "" + weather.weather_coModeling collect (each.simulation.plotWeather);
```

### Expected behavior
I am expected to have as results:
  - with accumulate: all the agents of the 3 species.
  - with collect : a list of all the species

### Actual behavior
I get the right behavior with collect but not with accumulate, as I get a empty list:
  - with accumulate : []
  - with collect : [plotWeather,plotWeather,plotWeather]

### System and version 
MACOSX
Continuous Built

**Comment by AlexisDrogoul** [comment]
OK. There seems to be a problem in accumulate regarding species, because the sentence `write "" + weather.weather_coModeling accumulate (each.simulation.plotWeather collect each);`, which forces a new list of agents to be recreated, works well. I will take a look.

**Comment by AlexisDrogoul** [comment]
Well, to be more precise, there is a problem with `accumulate` and `grid` populations. It has nothing to do, at first sight, with co-models. `grid` populations are handled in a special way compared to regular `species` populations (their internal list of agents is empty because it is already contained in the topology). But the various streaming operations seem to operate directly on the `elementData` and `size` of the internal list. I dont see clearly how to handle this right now (and which deeper implications it may have on other iterators, by the way).
