### ISSUE TITLE
a hexagon geometry does not fit with the hexagon of the hexagonal grid

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2246]
### Steps to reproduce
1. I use a hexagonal grid in my model. 
To improve the display, I create an aspect to draw hexagons at hand.

grid plot height: 10 width: 10 neighbors: 6 horizontal_orientation: false {
	aspect g {
		if my_com != nil {
			draw (hexagon(10) at_location (self.location))  color: #blue border:#black;	
		}
	}
}

### Expected behavior
I was expected to be able to draw hexagons that fit exactly with the hexagons of the cells.
(just as it is possible to draw squares that perfectly fit to the shape of a 4-neighbors grid cell).

### Actual behavior
I get slightly different hexagons. See the picture:
<img width="639" alt="capture d ecran 2017-09-21 a 06 15 24" src="https://user-images.githubusercontent.com/1555274/30678769-f433d356-9e94-11e7-834c-f3181c28443d.png">

### System and version 
GAMA Continuous Built
MACOSX

**Comment by ptaillandier** [comment]
Hi,

This is not an issue, or at least, the issue is not here. I mean that by default the size of the environnment is 100 x 100. You want to have 10 rows and 10 columns in your grid. But it is not a square/rectangle grid, so the size of the cell is not 10 x 10.
The width of a hexagon is: 100 / (10 * 0.75 + 0.25) = 12.9...  
and the height: 100 / (10 + 0.5) = 9.52....

If you use: draw (hexagon(100 / (10 * 0.75 + 0.25),  100 / (10 + 0.5) ), it is going to work (as well as : draw (hexagon(shape.width,  shape.height )
