### ISSUE TITLE
Right-click on cells on a grid

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2249]
### Steps to reproduce
1. Run the following model:
```
model MM

global { }

grid plot height: 11 width: 11 neighbors: 4 {
	bool is <- flip(0.5);

	aspect nbForest {
		if(grid_x * grid_y < 50) {
			draw circle(3) color: #red border: #black;
			if(is){
				draw square(1) color: #black;	
			} 
		}
	}
}

experiment EXP type: gui {
	output {
		display d {
			species plot aspect:nbForest;
		}
	}
}
```
2. Try to right-click on the cell.

### Expected behavior
I expected to be able to get in the contextual model access (for every plots) at the plot on which I have clicked.

### Actual behavior
When I click on circle without square, I cannot access to the plot (only the simulation is available).
When I click on the square, I can access to the inspect of the plot.
When I click on the circle only (in case of circle with a square), I cannot access to the plot to inspect.

Notice that:
 - this issue does not appear for regular species.

This bug seems to appear when I have several draw in an aspect and that some agents do not draw anything. It is just as GAMA considers only the last draw layer to detect the agent.

### System and version 
GAMA Continuous Built
MacOSX

**Comment by ptaillandier** [comment]
It seems to be linked to Java2D displays as its seems to work normally if I use an opengl display.

**Comment by AlexisDrogoul** [comment]
At first sight, I would say, when computing the envelope of the aspect of the agent in the display, that only the last `draw` is taken into account (which is why the square reacts and not the circle), and that (as an aggravating factor) if the condition is false (i.e. no calls to `draw`occurs) then the envelope is null. Need to check this (and why it works on OpenGL).

**Comment by AlexisDrogoul** [comment]
The explanation is in fact much simpler: the first `if` in the aspect is the cause of this misbehaviour. As a matter of fact, `if` (a regular statement, not specific to `draw`) return by default the result of the last statement it contains. It has no way to tell if it needs to combine (and how) the results of the sequential execution of its statements. Why it works in OpenGL is because individual shapes are labelled after their agent, while in Java2D we rely on the union of the individual shapes to identify the agent. So, some changes are required...
