### ISSUE TITLE
Copy of a species to a list returns a population

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2254]
### Steps to reproduce
1. run the following model.

2.The aim is (after having created 10 bus_stop agents and having created a bus agent with the list of these stops, stops) to create a new bus_stop and to add it to the bus stops list at the index that is after the index of the closest bus_stop.

```
model testDist

global {
	init {
		create bus_stop number: 10;
		
		create bus;
		
		create bus_stop returns: new_bus_stop ;

		ask bus {
			write "New bus : " + new_bus_stop;
			bus_stop closest_bus_stop <- stops with_min_of(each distance_to(first(new_bus_stop)));
			
			write "closest_bus_stop = " + closest_bus_stop;
			write "stops == " + stops;
			int i <- (stops index_of(closest_bus_stop));
			write "add at i = " + i;
			bus_stop bb <- first(new_bus_stop);
			add bb at: i to: stops ;
			write stops;
		}		
	}
}

species bus_stop;

species bus {
	list<bus_stop> stops <- copy(list(bus_stop));
}

experiment testDist type: gui {
	output {}
}

```

### Expected behavior
I would have expected to insert the new bus_stop in the right index location.

### Actual behavior
The bus_stop is inserted at the end of the list.
Note that the insertion at a given location in a list seems to work in general.
But it does not seem to work in an ask statement...

### System and version 
GAMA OSX, Continuous Built

**Comment by AlexisDrogoul** [comment]
Actually, it has nothing to do with `ask`. If you write your model this way:

```
global {
	init {
		create bus_stop number: 10;
		
		create bus;
		
		create bus_stop returns: new_bus_stop ;

		ask bus {
			write "New bus : " + new_bus_stop;
			bus_stop closest_bus_stop <- stops with_min_of(each distance_to(first(new_bus_stop)));
			
			write "closest_bus_stop = " + closest_bus_stop;
			write "stops == " + stops;
			int i <- (stops index_of(closest_bus_stop));
			write "add at i = " + i;
			bus_stop bb <- first(new_bus_stop);
			add bb at: i to: stops ;
			write stops;
		}		
	}
}

species bus_stop;

species bus {
	list<bus_stop> stops; // <- copy(list(bus_stop));
	
	init {
		ask bus_stop {
			myself.stops <+ self;
		}
	}
}

experiment testDist type: gui {
	output {}
}
```

It works correctly. The only difference resides in the use of an explicit loop to initialise `stops`, so that `stops` is forced to be a list and not a `population`. And `population`s, as they schedule their agents independently, do not accept them to be inserted at specific indices. This results from design choices difficult to revert (as they are intended to maintain populations, with their specificities, as much as possible), although we might explore two solutions: have `list(a_population)` return a `list` instead of a population, or have `copy(a_population)` return a `list`.

**Comment by AlexisDrogoul** [comment]
I have issued a fix to explicitly transform populations into lists when they are casted into a list or copied from the GAML code. It remains to be seen if this fix will not have an impact on the performances of simulations, as the casting to lists is heavily used everywhere in the code (and without too much attention to whether or not we make large copies of populations...).
