### ISSUE TITLE
Casting error with path_between operator (call the wrong version of the operator ?)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#2266]
### Steps to reproduce
1.Test the following model:
```
model testpathbetween
global {
	init {
		create dummy number: 2;
		path the_path <- topology(world) path_between (dummy(0), dummy(1));
		write the_path;
	}
}
species dummy;
experiment testpathbetween type: gui ;

```

### Expected behavior
Tell us what should happen (include all relevant expectations)
Get a casting exception.... it is as the wrong version of the operator was called (the one that takes as argument a map instead of a topology).

**Comment by AlexisDrogoul** [comment]
There were actually two problems here:
- [ ] first one came  from the definition(s) of at least two operators (introduced recently ?) that were using `Map<...,...>` instead of `GamaMap<...,...>` (and thus ended with a signature of `unknown, geometry, geometry`). I have corrected the problem, but a warning from the annotation processor would not be superfluous in those cases. However, always defining the exact type you expect is not a bad thing.
- [ ] second one came from the computation of the distance between the signatures of operators and the input signature of the modeler. In this particular case, the distance computed was equivalent. I have introduced a slight modification of this computation (to take into account not only the max distance between two individual types, but also the min distance). I just hope it won't break other calls.
