### ISSUE TITLE
[Unit Test] contains_edge 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2270]
### Steps to reproduce
1. In the unit test, we have the following test: 
`````
graph graphFromMap <-  as_edge_graph([{1,5}::{12,45},{12,45}::{34,56}]);
bool var2 <- graphFromMap contains_edge link({1,5},{12,45}); 	// var2 equals true
`````

### Expected behavior
I was expecting that the previous graph contains the edge.

### Actual behavior

var2 is equals to false, thus the graph does not contain the link.

### System and version 
GAMA Git, MacOSX

**Comment by ptaillandier** [comment]
Hi,

I am not sure that it is a bug, but rather a feature of GAMA dynamicLink.
When you write as_edge_graph([{1,5}::{12,45},{12,45}::{34,56}]), you build a graph with 2 dynamicLink as edges (and not just 2 polylines).

A dynamicLink is a line where the points composing the line can move, and the line geometry will adapted in consequence. 

So to be equals, 2 dynamic Links must have the exact same point (p1 == p2 and not p1.equals(p2)).

To make it work, you should either write:
point pt1 <- {1,5}; point pt2 <- {12,45};
graph graphFromMap <-  as_edge_graph([pt1::pt2,{12,45}::{34,56}]);
bool var2 <- graphFromMap contains_edge link(pt1,pt2); 	// var2 equals true

or use polylines instead of dynamicLinks.

**Comment by benoitgaudou** [comment]
Hi,

Thank you for your answer.
But I was wondering whether there are some points preventing to use the .equals instead of the == to compute the equality between edges ?
Because the following test appears intuitive to me:
`````
graph graphFromMap <-  as_edge_graph([{1,5}::{12,45},{12,45}::{34,56}]);
bool var2 <- graphFromMap contains_edge link({1,5},{12,45}); 	// var2 equals true
`````

Benoit

**Comment by AlexisDrogoul** [comment]
Sure, it makes sense... I have modified the equality test in `DynamicLineString`, with the hope that it doesn't break anything. As a matter of fact, the new equality test better matches the contract of the `exactEquals` method inherited from `Geometry`, so it makes this class a better citizen in the geometry world...
