### ISSUE TITLE
Saving or settings Display Layout

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2287]
A simple way to save or set the display layout. Once you reload the simulation the layout is the same

<img width="1618" alt="screen shot 2017-11-15 at 20 21 38" src="https://user-images.githubusercontent.com/3928502/32869021-c6556092-ca42-11e7-9901-1c6a3ad89781.png">

**Comment by agrignard** [comment]
BTW being able not to show the name of the display and having a kind of microfullscreen effect with just a little frame around would be very useful and minimal

**Comment by AlexisDrogoul** [comment]
About to close this issue, as you should probably compose displays (with layers) for this kind of case.

**Comment by agrignard** [comment]
Not necessary this is just an example,  if you compose only with layers  inside the same display every layer in the same display will have the same camera settings, which makes impossible to have different point of view of the same model. 

When you rerun the same simulation the layout stay the same which means it is stored somewhere right?

**Comment by AlexisDrogoul** [comment]
It is stored in memory as a perspective, and saving + loading it is something I have tried already at least one year ago but to no avail. It seems that a lot of contextual information is not saved correctly, at lest on this "hybrid" version of Eclipse we are using. Maybe it is a case for moving up to new versions.

**Comment by AlexisDrogoul** [comment]
A working, but still experimental version, is available in the latest version. It introduces 2 new operators (horizontal and vertical) that allow to compose arbitrary layouts (see the docs), as well as a layout statement (that can be used instead of `permanent` to describe layouts). In a nutshell, since the syntax is a bit awkward, the easiest way to test it is to compose your views, select "Copy Layout" from the Layout Displays submenu and paste the resulting `permanent` statement in your experiment. Additionally, you can choose to remove tabs and toolbars altogether to obtain something like this:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/579256/42136337-6ae44ff8-7d83-11e8-9f07-3064b860418e.png">

Keep in mind that this is a bit experimental. It doesn't work for multiple simulations, doesn't work well with Java2D displays, and has flaws yet to be discovered.

**Comment by AlexisDrogoul** [comment]
It allows to compose interesting things, for instance the very clean interface below:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/579256/42136518-2e19a1dc-7d87-11e8-8863-513ba22488e1.png">

**Comment by agrignard** [comment]
great!!! I like this effect. 

To push a bit more in the concept of customized layout would it be difficult (clearly not a priority but maybe it's not that hard) to be able to specify the position of a floating window. Like here the "first person" window is floating in the middle of the screen.
<img width="1869" alt="screen shot 2018-07-02 at 10 50 22" src="https://user-images.githubusercontent.com/3928502/42170898-d019803e-7de5-11e8-8c4f-7327892ce4e7.png">

Maybe there is to points here:

- Floating true/false
-Floatiing position

**Comment by AlexisDrogoul** [comment]
Detached views are awfully complicated to manage in SWT. Given that the commit (albeit experimental) answers the request in that thread, please open a new thread on detached views and more focused ones on the problems you will probably discover sooner or later in the current implementation.

**Comment by agrignard** [comment]
Definetly a great feature! 

![gadiohead mov](https://user-images.githubusercontent.com/3928502/44244221-d8dcfa00-a1a0-11e8-9cfe-1228ecae8901.gif)

**Comment by agrignard** [comment]
I am testing a bit more this feature, it's cool

![gadiohead mov](https://user-images.githubusercontent.com/3928502/44244407-d7600180-a1a1-11e8-89f4-049e6517c394.gif)
