### ISSUE TITLE
Problem to run latest build release

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2289]
Trying to run the last build

GAMA1.7_Mac_64_11.16.17_75ee3e9

When I launch it (even with a new workspace) it stays blocked on "building workspace 0%" ....
<img width="1920" alt="screen shot 2017-11-16 at 16 08 10" src="https://user-images.githubusercontent.com/3928502/32915971-a442f8b0-cae8-11e7-9c9c-a7a1f3fa2100.png">

**Comment by agrignard** [comment]
super weird... I guess it's because I have a lot of bin version. 

So if it was called gama.app it wouldn't work I just rename it gamaLastRelease.app and it works ... I guess it's something related to Mac Applications settings stuff...

**Comment by agrignard** [comment]
facing a kind of same issue on windows... is there a problem with this version or what??

**Comment by AlexisDrogoul** [comment]
`facing a kind of same issue`. Could you elaborate ?

**Comment by agrignard** [comment]
very hard to document... i might be the only one to install several binary of the same gama.exe or gama.app I have the feeling that there is a conflict if you run an exe with the same name

**Comment by agrignard** [comment]
I don't know if it comes from  this specific releaseor if it's link to https://github.com/gama-platform/gama/issues/2290 that corrupts my workspace

**Comment by hqnghi88** [comment]
Hi,
Just test this GAMA1.7_Win_64_11.17.17_75ee3e9 and it works, with old and new workspaces.

**Comment by agrignard** [comment]
I will test it more this afternoon on my Windows 10 machine.

**Comment by agrignard** [comment]
I am trying to install it from a colleague mac (macOS Sierra) and we are facing the same issue 

0. Download the last build
1. First step: no way to run GAMA (stay stucked at gama.shared)
2. After a force quit we get tstucked on 0% Building Workspace
3. After the second force quit it's finnaly working.

**Comment by agrignard** [comment]
I guess this is link with #2293

**Comment by thorsilver** [comment]
Since posting earlier I've also tried with the Continuous Build, and that doesn't work either.  My machine then updated itself to High Sierra, still can't get past the dialog box for choosing the workspace location, the program becomes completely unresponsive and I have to force quit.

I'm on a 2017 MacBook Pro which has some hardware differences, don't know if that has anything to do with it

**Comment by agrignard** [comment]
I am facing also the same kind of issue on different mac (different hardware(macbook pro retina and mac book with touch bar and software (captan and sierra) that makes running the latest release  impossible

**Comment by AlexisDrogoul** [comment]
Unfortunately, macs have become a nightmare recently (not only high Sierra,
but also the various 'security' patches applied on older versions).
Randomization of work folders, signature of code, etc.. Have you tried the
steps described on the wiki? No decompression using the built-in software,
copy and paste to Applications, etc. It may work. Or not. Seems like Apple
is trying to remove everything not built with their tools. I will spend
some time trying to investigate signatures a bit more, but do not expect
fast results.

Le 20 nov. 2017 6:34 PM, "Arnaud Grignard" <notifications@github.com> a
écrit :

I am facing also the same kind of issue on different mac (different
hardware(macbook pro retina and mac book with touch bar and software
(captan and sierra) that makes running the latest release impossible

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gama-platform/gama/issues/2289#issuecomment-345769643>,
or mute the thread

**Comment by sriramab** [comment]
I am no expert but hasn’t apple file system changed? Could be a reason?

**Comment by sriramab** [comment]
And I can confirm same name doesn’t work. It has to be a different name for the app for each binary you download.

**Comment by thorsilver** [comment]
Hi Alexis, thanks very much for responding to our predicament.  I'm hopeful that GAMA can work again on Mac OS sometime in the future, but I understand this will take some time due to Apple's questionable practices of late.

In the meantime, I'm going to put Windows 10 on this machine and hopefully have more success on that side of things :)  At the moment the steps outlined on the wiki have not yet succeeded in getting GAMA to run on Mac for me, but I will try a few more variations of those procedures and post here again if I manage to get it working, in case it would help others in the same situation.

**Comment by AlexisDrogoul** [comment]
Hi,

Have you tried to launch GAMA from the command line, so that you can get a log file at least ?  Going into the Gama.app folder, then inside MacOS and running from the terminal `./Gama` ?

Alexis

**Comment by thorsilver** [comment]
Hi Alexis,

Yes, it says the following in the Terminal window when I attempt to run GAMA:

Bad value: "${target.nl}" for NL. Using system default.
2017-11-28 03:10:10.443 Gama[23006:4981786] Persistent UI failed to open file file://localhost/Users/thorsilver/Library/Saved%20Application%20State/Gama.savedState/window_2.data: No such file or directory (2)

Then as always it hangs on the GAMA Models Workspace dialog box.  Does that help?

There is indeed no Gama.savedState folder in Saved Application State, I did check.

**Comment by AlexisDrogoul** [comment]
The latest builds should be much less error prone regarding the complex initialisation of GAMA. If anyone wants to test it...

**Comment by thorsilver** [comment]
Hi Alexis,

Tried the latest candidate build, still same results as before.  Just now I tried the latest commit and made a new build on my own, it still hangs at the same point but only produces this error now:

Bad value: "${target.nl}" for NL. Using system default.

**Comment by AlexisDrogoul** [comment]
Hmmm.. I have targeted different possibilities and tested different combinations. Latest build is the most "stable" (or the less unstable) on that respect: using different accounts, I managed to run it everytime, with only one attempt failing (I had to force quit it, then it launched normally). So I don't really know what happens on your side. Did you follow all the awkward recommendations on the wiki ? If yes, there is probably something else, so we will have to dig a bit more. Does the execution in Eclipse proceed correctly ? (by running the gama.runtime.product)

**Comment by thorsilver** [comment]
I followed the wiki recommendations, still doesn't work.  I just ran gama.runtime.product as instructed in the wiki and it hung at the same point, console reads as follows:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
2017-12-10 15:53:53.580 java[9307:1067495] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
2017-12-10 15:53:53.581 java[9307:1067495] *** WARNING: Method userSpaceScaleFactor in class NSWindow is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

**Comment by agrignard** [comment]
HI everyone,

We are unfortunately facing the same issue here on Mac Sierra with the last release.

Same error message from the terminal also:
Bad value: "${target.nl}" for NL. Using system default.

**Comment by agrignard** [comment]
Also I guess this is not up to date right?

https://github.com/gama-platform/gama/wiki/Installation#on-macos-x

It was for GAMA 1.6.1 no?

**Comment by agrignard** [comment]
Also this issue is about Sierra or also High Sierra ? (I have a colleague that can run GAMA on High Sierra)

**Comment by AlexisDrogoul** [comment]
@agrignard `"${target.nl}" for NL. Using system default.`is not an error, just a warning. And the wiki is correct AFAIK. The problem comes from two different causes (and that's why it happens a lot now): Eclipse Mars is not compatible anymore with the latest JDK (> 1.8.152) on macOS; and issues in the way Eclipse is handling the startup procedure on different OSes (i.e. what uses to work on macOS crashes on Windows and conversely, mainly due to new policies in the OSes, like security policies). Difficult to track all these issues by patching the current version and that's why @hqnghi88 and I have begun working on the oxygen branch (https://github.com/gama-platform/gama/tree/oxygen), which should make things more stable.

**Comment by agrignard** [comment]
mmm ok I see  very unfortunate...
so I understand now the problem

For a quick fix is there a way to get a jdk <1.8.152?

FYI
High Sierra and the latest build 24/01/18 and java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
=> DOESN'T WORK

High Sierra and the latest build 22/01/18
luis-alonso:~ luisalbertoalonsopastor$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
=> WORK

**Comment by agrignard** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

**Comment by agrignard** [comment]
Ok cool it s working with jdk_1.8_151 (and not with 152) so to be super precise I would say JDK (>= 1.8.152) is not compatible anymore

Thanks for the quick answer, we have now one more user!

**Comment by agrignard** [comment]
I guess we can close this issue (feel free to reopen it)
