### ISSUE TITLE
Wrong jdk packaged with the release

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#229]
**Describe the bug**
In the current alpha release there's a problem with the jdk packaged for MacOs with arm architecture: when running it this message appears:
![image](https://github.com/gama-platform/gama/assets/6374469/d69f2118-4e52-48d5-903e-8c43b28c30fe)
changing the path in the ini to a proper jdk 21 makes it work

**Comment by agrignard** [comment]
Do we have an idea of how to fix this without having to "changing the path in the ini to a proper jdk 21 makes it work"

@lesquoyb can you be more explicit and ideally provide the right line of code to change in which file?

**Comment by hqnghi88** [comment]
Hi, Obviously you must have jdk21, otherwise if you are in jdk 17, use the non embedded GAMA it should work. This issue is specific for the ALPHA release with jdk embedded one

**Comment by agrignard** [comment]
This is what I have with a jdk 21 that I copied at the same level of the jdk in Gama.app/Contents/jdk-21.0.3.jdk

<img width="260" alt="Screenshot 2024-07-03 at 17 18 11" src="https://github.com/gama-platform/gama/assets/3928502/4d033ca0-f84f-48bc-8534-59ddd8518a05">

**Comment by agrignard** [comment]
Ok so I installed a jdk 17

`````
arno@dhcp-153-122 UMMISCO % javac -version
javac 17.0.11
arno@dhcp-153-122 UMMISCO % java -version 
java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)
`````

but I get this error when running the GAMA without JDK

<img width="261" alt="Screenshot 2024-07-03 at 17 42 52" src="https://github.com/gama-platform/gama/assets/3928502/692d103c-1a0f-4d66-b21a-11736279819d">

can the log can help?

**Comment by lesquoyb** [comment]
Gama 2024-06 now requires jdk 21, it cannot run with jdk 17

**Comment by agrignard** [comment]
thanks @lesquoyb and @hqnghi88 working now with GAMA without JDK and jdk21 installed

**Comment by RoiArthurB** [comment]
Hi all, so I did some tinkering and I found that this issue only occurs while setting GAMA with a relative path to JDK.

If you edit the `Gama.ini` file and modify the path to your java bin to anywhere on your computer with an absolute path (ie. something like this `/path/to/somewhere/java` instead of that `../../otherpath/to/java`) it'll fix the issue. 

Therefore, I'm thinking the error comes from the new SWT which might modify the `-vm` parameter. My current question is that double slash in the Eclipse's path (`[..]MacOS//..[..]`) which might be an issue for the JDK path resolver or something like this...

**Comment by RoiArthurB** [comment]
I don't fully understand the reason of this issue, but it only happens on MacOS (no pb on Linux nor Windows).

The problem comes from the JDK being one level above the executable, but it's possible to trick it with a symbolic link. Therefore I create one before re-zipping the GAMA release with the embedded JDK. I also updated the `-vm` parameter to use this symlink :)
