### ISSUE TITLE
inclusion or  exclusion of extra or model attributes

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2300]
Hi,

I would like to request the ability to show or hide attributes defined inside species or outside species. For example, inside the population table or in the inspect window.

This could be along the lines of currently possible include and exclude facets in browse, inspect statement in output

thank you

**Comment by AlexisDrogoul** [comment]
Hi, I've implemented a solution that reuses the existing facet `attributes`. You can pass it a list of variables as usual, but also add in this list inline attributes (the ones you create dynamically and store in the agent)-- you however have to specify the type for it to work, i.e. `inspect a attributes:["location", "foo"::int];`, otherwise GAMA will not know what you're going to display.

**Comment by sriramab** [comment]
This statement - inspect or browse with selected list of attributes - works in gaml but not in interactive console. Could you please check or is it meant to be this way?

**Comment by sriramab** [comment]
Please also note, after issuing a `browse species attributes:["attribute"::type]` command, issuing a `inspect species attributes:["attribute"::type]` has no effect and the previous browse command is executed again. However, if inspect is issued for a specific agent, it works after the browse command.

**Comment by AlexisDrogoul** [comment]
@sriramab Interactive console now works. And regarding the second comment, remember that `inspect` and `browse` are synonyms.

**Comment by AlexisDrogoul** [comment]
Closing now unless you have more some problems to uncover.
