### ISSUE TITLE
time does not equal cycle*step

### ISSUE THREAD

**Issue by ronswanson50** [gama-platform/gama#2317]
### Steps to reproduce
1. Set step size < 1 second

2. Compare "time" vs "cycle*step" as simulation runs

### Expected behavior
time should equal cycle*step. It should be the exact amount of time that has been simulated

### Actual behavior
The value for time is rounded down to the nearest integer

### System and version 
GAMA 1.7, Java JDK 8, Windows 10

**Comment by benoitgaudou** [comment]
I tried to reproduce this issue with the following model, but I was not able to get the issue: 

```
global {
	float step <- 1 #s;
	
	reflex toto {
		write time;
		write step*cycle;
		write ""+ (time =cycle*step);
	}
}

experiment Test type: gui {
	/** Insert here the definition of the input and output of the model */
	output {
	}
}
```

This model returns: (showing that time and cycle*step have the same value)
0.0
0.0
true
1.0
1.0
true
2.0
2.0
true
3.0
3.0
true

I tested on the last GAMA Git with Eclipse Mars, MacOSX.

So I close this issue. Feel free to reopen it, if the model does not provide the expected behavior on your computer and attach a complete example.

Benoit

**Comment by ronswanson50** [comment]
In order to see the bug, the value for step should be less than 1 #s. Try 0.5 #s in your second line for example. Actually I think that any fractional step size (such as 1.5 #s) would cause a problem, but I haven't tried those.

**Comment by benoitgaudou** [comment]
Hi,

Indeed you are right.
The issue comes from the fact that the time variable (i.e. the time between
the start of the simulation),
is computed as an integer (in fact a long integer) number of seconds.

This has been fixed and should be available on the next nighty built and
release.

Thank you for your comment.

Benoit

2018-03-11 22:21 GMT+01:00 ronswanson50 <notifications@github.com>:
