### ISSUE TITLE
User interaction : Moving Agents.gaml

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2349]
### Steps to reproduce
1. Run the model Features / User Interaction / Moving Agents.gaml

2. Open the Click and Move [OPENGL] display

### Expected behavior
Same behavior as in the Java2D display

### Actual behavior
The circle, that should be below the mouse, stick to the top-right corner.

In addition, when the user click on the k key, it kills agents as expected, but it also display 4 boxes in the corners...

### System and version 
MacOSX, GAMA preRelease 1.8 and Git Mars

**Comment by agrignard** [comment]
if you remove the java2D then it works in opengl so I have the feeling that this is strongly link to this issue #2323

**Comment by AlexisDrogoul** [comment]
There is clearly an issue with Java2D displays in 1.8, and more precisely with all the workarounds we had to implement to make Java2D displays work in 1.6 and 1.7... Problem is, which one to consider as fixed by the underlying RCP improvements ? Or are there new bugs introduced in RCP since we moved to Oxygen, which renders the "bridge" between AWT and SWT more unstable ? Keep in mind that this bridge is unmaintained since at least 6 years and that it is still a miracle we can display Java2D within the current release... I will try to investigate, but I can't promise anything. 

The easy thing to fix is the problem of the 'k' key, by the way, I will update the model accordingly.

**Comment by AlexisDrogoul** [comment]
I've reactivated an old workaround (which was present to fix #1353) and it seems to do the trick.
