### ISSUE TITLE
[GS] socket stay in use for longer (forever?) after closing gama GUI than headless

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#237]
**Describe the bug**
I experienced a weird problem recently. With a client for gama-server I try to regularly reconnect in case the connection is lost. 
With gama GUI, I open the program, let the client connect then close it and reopen. Everytime at the opening of the socket for gama-server systematically crashes and I can read in the console that it had a Bind exception saying that the socket is already in use.
But if I do the same thing with gama headless I have no problem at all, the server is created without exception and the client can reconnect instantly.
Even weirder, if I start a gama GUI, let the client connect, then close it and try to open gama headless, I also have the same socket already in use exception.

**To Reproduce**
1. open gama in gui mode
2. connect a client to the server
3. close and reopen gama
4. see that the server is not working

**Additional context**
I don't know if the client part is important or not in this case, I didn't try without it yet.
I see two possible reason for that problem: either we use different classes and behaviours in gui and headless to manage the server and for some reason the one in GUI takes way longer to be "cleaned" by the OS, or we do manually some resource closing in headless mode that we do not do in GUI.

**Comment by RoiArthurB** [comment]
This isn't really a GAMA issue but more how OSs works.

It's briefly explained here : https://serverfault.com/questions/181015/how-do-you-free-up-a-port-being-held-open-by-dead-process

> If your program spawned any processes while it was running, try killing them. That should cause its process record to be freed and the TCP port to be cleaned up. **Apparently windows does this when the record is released not when the process exits as I would have expected.**

Long story short : When you close GAMA, Windows (same for MacOS and Linux) takes a bit of time before freeing the port which was in used. When you close a headless version of GAMA, you terminate that process (instead of exiting with GUI version) which triggers the port freeing faster.

A possible manner of trying to fix this issue would be to terminate the server mode faster in the closing progress of GAMA.

**Comment by AlexisDrogoul** [comment]
The fix to this has been committed here : https://github.com/gama-platform/gama/commit/5b4f3b9a02931e5d6e27954469aff47013761cf0 and it has been tested. Closing for now !
