### ISSUE TITLE
end_arrow and pipe (line with a depth) in 3D

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2428]
### Steps to reproduce
1. run
````
model Tuto3D

global {
  init { 
  }  
} 
  

experiment Tuto3D  type: gui {	
  output {
    display View1 type:opengl {
      graphics "axes"{
      	draw line([{0,0},{0,0,100}]) end_arrow:2 color:#gray;
      	draw line([{10,10},{10,10,100}],1) color:#gray;
      	draw line([{20,20},{20,20,100}],1) end_arrow:2 color:#gray;
      	draw line([{30,30},{100,100,100}],1) end_arrow:2 color:#gray;
      }
    }
  }
}

`````

As soon as the end_arrow is used in 3D the behavior is not the one expeced. Not a big big deal but just in case I document this issue 

### Expected behavior
Arrow in 3D

### Actual behavior
As soon as end_arrow is used on a line with a depth (a pipe) it's not displaying the pipe.
I put some code here to reproduce it easily

<img width="653" alt="screen shot 2018-06-22 at 09 31 55" src="https://user-images.githubusercontent.com/3928502/41779389-a9fe6ec0-75ff-11e8-964d-2126e25668f4.png">

### System and version 
GAMA1.8_Mac_64_06.22.18_3cc7214

**Comment by AlexisDrogoul** [comment]
Well, that's due to the fact that we do not have a proper `GamaMultiShape` class to correspond to the `GeometryCollection` class of JTS. Arrows are added to the geometry to form a collection of geometries, and they are all wrapped into one and only one `GamaShape`, which consequently loses individual information (like the type) for individual shapes. Two ways to circumvent this problem: drawing the arrows separately or making the "type" of a shape a collection of "type" when it is composed of a collection of geometries.

**Comment by AlexisDrogoul** [comment]
Hi, I close this issue with the workaround pushed earlier. To note: the display is awful with a 3D pipe, as we don't have 3D arrows (cones, or something like this), so the arrow is strangely positioned on the 3D surface (and I don't see clearly how to change this, beside drawing cones from the aspect).
