### ISSUE TITLE
Integrating µm unit into the platform.

### ISSUE THREAD

**Issue by ILHEM88** [gama-platform/gama#2465]
Hi, 
Is there any possibility to integrate the unit µm (Micrometre) into the platform?
Thank you in advance 
Best regards
Ilhem

### System and version 
GAMA1.8

**Comment by AlexisDrogoul** [comment]
Hi, two new units have been added to the standard units of GAMA

- micrometer: named `#µm`, `#micrometer`or `#micrometers`
- nanometer: named `#nm`, `#nanometer` or `#nanometers`

Enjoy !

**Comment by ILHEM88** [comment]
Thank you very much but which version of GAMA will contain these new units? 
Thank you 
Ilhem

**Comment by benoitgaudou** [comment]
The dev version, but also soon on the continuous built.

Benoit

2018-07-18 10:20 GMT+02:00 ILHEM88 <notifications@github.com>:

**Comment by ILHEM88** [comment]
Okay, thank you very much. 
Best regards 
Ilhem

**Comment by ILHEM88** [comment]
Hi again, 
The unit works well under 2D but I'm not able to visualise the spatial distribution by using it in 3D space. 
Can you help me here? 
Thank you in advance 
Best regards 
Ilhem

**Comment by benoitgaudou** [comment]
Hi,
No we cannot help you with so little information...
Benoit

2018-07-26 20:12 GMT+02:00 ILHEM88 <notifications@github.com>:

**Comment by ILHEM88** [comment]
Hi, 
I have a problem with the viewing of the spatial environment as it's shown from the small code below: 
global
{
	float sizeomega <-500.0#micrometer ;  
	geometry shape <- cube(sizeomega); 
}
experiment Tuto3D  type: gui {
  output {
    display View1 type:opengl {
      graphics "env"{
      	draw shape color: #black empty:true;	
      }
   
    }
    		
  }  
}
That works perfectly in 2D. 
Thank you in advance 
Ilhem

**Comment by benoitgaudou** [comment]
Hi,

There is indeed something strange and wrong in GAMA about the display of
too small environment in OpenGL.
I opened the issue gama-platform/gama2#29 abiout this point.

Cheers

Benoit

2018-07-27 9:55 GMT+02:00 ILHEM88 <notifications@github.com>:

**Comment by IlhemB** [comment]
Dear all, 
I want to have your point of view about a subject related to my last post. Actually, I wonder if I can start using the spatial unit µm, lately integrated into GAMA, in my code. Knowing that the model is conceived in 2D. 
I'm a little bit afraid since there are some issues detected about this unit. 

Thank you in advance 
Best regards 
Ilhem

**Comment by sriramab** [comment]
But meter or centimeter or micro meters is just about scale, can you probably not change your scale of analysis (factor your measurements), If you are consistent with scales and conversions, I do not see why a model cannot be built? just curious.

**Comment by ILHEM88** [comment]
Yes, I I agree with you but also I think that when we integrate the unit we can have small differences due to the calculus since GAMA convert them in meter. 
Best regards 
Ilhem

**Comment by AlexisDrogoul** [comment]
Units matter if you have different scales in your project. If everything is at the micrometer scale, then you can perfectly decide that it is your "default" unit and interpret all your results in this frame. Otherwise, if you have agents that can be measured in meters and others that can be measured in micrometers, it's better to use the unit provided, as you lower the chances to make yourself computation errors (and basically, you'll do the same computations by hand, with the same rounding errors, than what is done in GAMA).

The only issue so far is that of the display in 3D for small values. Other than that, adding a unit is only a substitute for doing a multiplication.

**Comment by ILHEM88** [comment]
Okay, I understand. 
Thank you to all of you for your assistance. 
Best regards 
Ilhem
