### ISSUE TITLE
Drag and drop of external files on windows

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2469]
### Steps to reproduce
1.
Try to drag and drop some external file in file explorer on windows to gama editor

### Expected behavior
Create files declarations.
### Actual behavior
![img_20180722_215224](https://user-images.githubusercontent.com/6105384/43046896-d28b5f8a-8df9-11e8-997f-df271bc95d47.jpg)
 
### System and version 
Gama git, win

**Comment by AlexisDrogoul** [comment]
Works fine for me with the latest commit. Can you test it ?

**Comment by hqnghi88** [comment]
I cant drag and drop files into gama. It still show the unpossible mark

**Comment by AlexisDrogoul** [comment]
Strange. It's working perfectly on my Windows 10 installation. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/579256/43073699-bd4c8918-8ea4-11e8-86f1-d2e1750b23ab.png">

Can you drop files on the editor area of Eclipse ?

**Comment by AlexisDrogoul** [comment]
see also this, this may be related (although it shouldn't work in my Windows...).

https://stackoverflow.com/questions/10138834/eclipse-rcp-drop-file-from-external-explorer-not-accepted

**Comment by hqnghi88** [comment]
It's 3a
![image](https://user-images.githubusercontent.com/6105384/43074176-91fb134a-8ea6-11e8-8f2f-47f7a140ce0d.png)

**Comment by AlexisDrogoul** [comment]
Seems Windows restricts some drag'n drop operations from some devices. For instance, you can't "move" from a CD-ROM. From which device are you dragging the files ? Can you try with a vanilla "C:/" drive ? 

Otherwise, a possible fix is here : https://stackoverflow.com/questions/12912984/why-cant-i-drop-files-on-to-eclipse-swt-drop-target-from-a-cd-in-windows

If it a problem related to the device, I can probably fix it by declaring every drag of resources and files as "copy" (not move).

**Comment by hqnghi88** [comment]
I found it, i configured my eclipse to always run as administrator. When i run as my own user right, it works. 
Thanks.
