### ISSUE TITLE
Some glitch of UI on Ubuntu 18

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2481]
**Describe the bug**
There are several bug of UI on ubuntu 18

**To Reproduce** 
1. Just launch GAMA ( preferable from eclipse, i did not test release)
2. See UI

**Expected behavior**
Beautiful UI

**Screenshots**
There is a wrong size of name bar on navigator. There are several black space, on toolbar of views (console, display) 
![image](https://user-images.githubusercontent.com/6105384/43276336-8a332410-912e-11e8-8f1c-5c3330183971.png)

**Desktop  :**
 - OS: ubuntu 18
 - GAMA version: git
 - Java version 1.8

**Comment by AlexisDrogoul** [comment]
Do your settings in the product still mention GTK2 ? (I think this is the default we put a while ago). You might want to try removing this option and see the result. Ubuntu 16 does not display this, by the way (it's pretty clean).

**Comment by hqnghi88** [comment]
It does not help, --launcher.GTK_version 2, --launcher.GTK_version 3, or remove it.

**Comment by AlexisDrogoul** [comment]
OK. I tried to test it, but I gave up after a few hours trying to obtain a working Ubuntu 18 version. Stuck in a kind of login loop, with no option on the web found to get out of it. What a crap system. 

Anyway, The UI glitches, for me, only consist in the separators between icons (and the size of the "Sync" button in the navigator, which I already fixed in Ubuntu 16). The other (size of the text box) is how Ubuntu manages toolbar when they are too small. I agree its ugly, but there is almost nothing I can do.

**Comment by hqnghi88** [comment]
Sorry for your corruption, it seem your gnome or xserver has been broken. And this issue does not happen in release. So when i add --launcher.GTK_version 2 to eclipse.ini, it works. It mean oxygen launch configuration inherit GTK_version 3 of eclipse and bypass the thing in our product.
