### ISSUE TITLE
Series Examples.gaml seems sensitive, fragile that could make gama "not responding"

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2484]
**Describe the bug** 
I play with #2441 , try to break a workspace

**To Reproduce** 
1. Go to Features\Charts\models\Series Examples.gaml
2. Click on "Different series" experiment button
3. Drag the speed slider to right (Minimum of a cycle 0.0s)
4. Press Play 
5. Just after 20-30s , gama will be heavy loaded , cause by the speed is too fast and the lists are huge (in eclipse show continuously LIMIT REACHED (compressing 5000002 bytes into 1931278 bytes))
6. If it is not, try switch several layout (menu View) when it is still running.
7. If it is not, repeat 2 3 times more from 2.
8. Gama then is not responding and need force close. Then from now, we have a dirty workspace, it will not work well with layout anymore

**Expected behavior**
Well, a bug is supposed to be killed.....

**Screenshots**

![image](https://user-images.githubusercontent.com/6105384/43326005-e582b020-91e1-11e8-980f-6a499fc74035.png)

**Desktop (please complete the following information):**
 - OS: win 10, ubuntu 18
 - GAMA version: git
 - Java version 18

**Comment by AlexisDrogoul** [comment]
I looked by curiosity at the implementation of JFreeChartOutput, and I understand why we break so quickly and easily: one image was created per cycle and per chart ... and they were never released (nor flushed). By changing a bit this default implementation, I can go up to 500.000 cycles without breaking (on a 2GB partition for GAMA). How many cycles did you achieve before breaking GAMA ?

**Comment by hqnghi88** [comment]
Dear Alexis, it was about 10 000.

**Comment by AlexisDrogoul** [comment]
I have implemented and committed a much more realistic and optimised policy regarding chart displays. They now create less BufferedImages and Graphics2D objects than before (good for memory and speed). The update of the series is done continuously, but the update of the chart itself is only done when it has been successfully displayed at least once. And the chart doesnt attempt to draw itself when it has not been displayed at least once. As a consequence, for such frenetic throughputs as the one in the model, the update of the displays is done less frequently, but the charts remain accurate. Of course, memory slowly increases (since the charts contain more and more points), but at a much slower rate than before and the displays don't break (i.e. they continue to display the charts, even if it's less frequently).
The policy is more realistic in that it tries to display something (that's what charts are for !) rather than blindly updating series or data without having a chance to ever display them. So, in a way, it introduces a form of soft synchronisation with the simulation, which depends on the amount of data to compute and to display, and which will remain unnoticeable for "normal" models. However, for this kind of stupid model (which simply outputs random values), the change is noticeable, i.e. it slows down... but at least it displays something even when the delay is at zero (which is its goal, after all).

**Comment by AlexisDrogoul** [comment]
So, @hqnghi88, sorry but you will have to choose another example for breaking GAMA 😃   (it's not too difficult 😢 ).

**Comment by hqnghi88** [comment]
Congrat and Thanks, you have made a big enhance for chart , i think , because in the original version, even the author (guess who?) must set the minimum_cycle_duration to 0.2 , seem to eliminate a heavy task. 
And poor me, how can i break Gama now? I think i have another.
