### ISSUE TITLE
False positive error in the model library (even on a new workspace and with a forcing of the validation of all models)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2493]
**Describe the bug**
When GAMA Git is run on a new workspace, no errors in the model library should appear. But I notice the "Validation views" specify errors on the Preferences.gaml model. Even forcing the validation at hand does not remove this error.
But when the model is opened, the error disappears.

**To Reproduce**
1. Run GAMA on a new workspace
2. Wait for the compilation of the workspace (notice errors in the Validation View)
3. Click on the button "Clean and validate all projects" in the Validation View (and notice errors are remaining)
4. Open the model Syntax / Preferences. gaml (and notice the errors disappear)

**Expected behavior**
I was expecting no error in the model library.
In addition, the click on the button "Clean and validate all projects" should not provide false positive errors.

**Screenshots**
<img width="1792" alt="capture d ecran 2018-08-02 a 10 11 24" src="https://user-images.githubusercontent.com/1555274/43571281-da777a6c-963c-11e8-8077-f89523a1a560.png">

**Desktop (please complete the following information):**
 - OS:  macOS High Sierra
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
Yes. This is normal. Not "normal" as "it should always be like this", but "normal" as "it is complicated to do something else (but I will try)".

Basic line is that many preferences are created **after** the creation of the `gama` agent, because they belong to plugins that are loaded (or not, sometimes) after `msi.gama.core`. For example, editor preferences, some UI preferences, etc. (and some may never be loaded at all, when in headless mode for instance).

So I have to find a way to preregister all the preferences so that the `gama` agent knows which variables he should really be "handling" at startup... And this is where the complicated part begins, as the best way to do this (and we do it a lot in GAMA) is to create extensions in the plugin.xml file...

**Comment by AlexisDrogoul** [comment]
And just to add that forcing the validation will not change anything -- only loading the corresponding plugins will do.
