### ISSUE TITLE
GAMA Workspace corrupted with multiple displays?

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2500]
I know it is a very very not complete bug but I prefer to report it at it happens 3 times in a raw to me today using this version GAMA1.8_Mac_64_withJDK_08.03.18_b0a8d84

I was "playing/working/whatever" with GAMA and I got three times a kind of freeze that forces me to restart GAMA , when I restart from the same workspace and then have this rendering
<img width="1919" alt="screen shot 2018-08-05 at 14 12 24" src="https://user-images.githubusercontent.com/3928502/43688600-d19f355e-98b9-11e8-90c2-d15ffa688bb4.png">

It says Input doesn't exist and the project on which I was working  is not anymore in my user models.

It's ok I can then recreate a new workspace, etc etc but I am a bit surprised to have this kind of behaviour with GAMA 1.8, it used to be much more stable for a while (It's a long time I didn't have to recreate ten workspace the same day)

The only thing I know is that I was working on a project and experimenting some layout stuff with this model https://github.com/agrignard/GamaExperimental/tree/master/CityScope_GAMA_Experimental

So it is maybe related to this issue #2287 or just to the fact that the model is pretty heavy in term of visualization 

It's impossible to document properly as it happens randomly. I will try to dig it and find a way to reproduce it. And put more info here

**Comment by AlexisDrogoul** [comment]
A few questions, because I've never seen "disappearing projects" before:

1) Did you have several instances of GAMA running and using the same workspace ? 
2) Did you try to refresh the resources in the navigator ?
3) Are your projects located in the workspace or linked from the workspace ?
4) Are there any third-party file managers (like Dropbox, GoogleDrive, Git) playing with them (i.e. versioning them, etc.) ?
5) When did the freezes happen ? Doing what ? 

Even if you don't know how to reproduce the bug properly, you have to provide more context.

**Comment by agrignard** [comment]
Yes I know it's pretty vague. I can sometime reproduce it but it's very tricky to document

The only thing I know is that I am indeed having 
1. a third app (GitHub Desktop) but I often have it and I never notice anything wrong
 2. I am experimenting with the layout and permanent facet link to this issue #2287
3. The model is pretty heavy

I will close this one as it's indeed to vague  and I try to add some info related to #2287
