### ISSUE TITLE
Init order when using import  

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2511]
**Describe the bug**
Imagine 2 models: model1.gaml and model2.gaml 

model2  imports model1 (basically model2 inherits from model1 to then add more species in model2 on top of the one existing in model1)

The init of the model2 is called before the init of the model1 but I need to have the model1 initialized before to initialise my model2 (the species of the model 2 need to have some species of the model1 already instantiated (home and work are buliling which is a species defined in model1)).

**Expected behavior**
the init of the model1 should be call before the init of the model2

**Comment by AlexisDrogoul** [comment]
Actually, the logic here is different, so it's difficult (even if it seems more logical at first glance) to say that model1 `init` should be called first. 

Why ? Because the import of models does not follow the inheritance parent-child pattern for init and abort but an aggregation pattern (i.e. inits do not replace previous ones). As a matter of fact, if we had to follow it, models would be provided with multiple "parents" (if they import multiple models). So how to choose which one(s) should be called first ? 

So you better think of `import` as an aggregation rather than inheritance when it comes to `init` and `abort` (or composition, if you prefer: a model composed by different sub-models). Each init should then be responsible for initialising its own scope (i.e. its own model) and in that view, it is logical that the init of the model where the experiment is defined is called first, followed by the ones imported. Of course, these inits can call actions or use variables which follow the inheritance pattern (i.e. the ones redefined are prevalent, and they can call their super implementation if necessary).

Usually (see the segregation models, for instance), one does describe one and only init section, which in turn calls virtual actions so that you can more or less follow the parent-child pattern (i.e. the implementation of these actions can choose or not to call the super action if it exists). 

I describe here what exists, not what "should" exist in an ideal world where, probably, the inheritance would be prevalent (even if it would be difficult to deal with multiple imports). Anyway, composing a model is not that difficult : there is a main one (usually the one with experiments, but it can be imported by experiment models, which is cleaner), which imports other models, each one defining one species (and the global vars / init that come with it). The ones you specialise are the "species models".

**Comment by agrignard** [comment]
Ok I get it.

So in this project https://github.com/CityScope/CS_Simulation_GAMA/wiki/Customization I am trying to design a methodology so that people can enhance an initial model (let's call it model1) with new species. (e.g add autonomous car on top of an existing model made of building, road and people). However I want them to be able to use all the species of the model1 in the model2

One way to define a new dummy species is 
`````
species CustomSpecies skills:[moving]{
  reflex move{
    do wander;
  }
  aspect base{
    draw circle(10#m) color:#red;
  }
}
``````

and then create it in the init of the customized model (model2)
`````
global{
  init{
    create CustomSpecies number:10;
  }
}
`````

If CustomSpecies has no dependencies to model1 everything works fine.
So now the issue is if you want CustomSpecies to have a home and and an office that are one of the buildings instantiated in the model 1.

What would be the clean way to "inherits" from model1, and still have a working model1 ?

Replace in model1
``````
init{
.....
}
``````
by 
```````
action initModel1{
....
}
```````
and then call this action in the experiment of the model 1 (I try it this syntax doesn't work)

`````
experiment model1{
do world.initModel1;
}
`````

and then in the init of model2 once can write

`````
init{
wolrd.initModel1;
create CustomSpecies{
home<-one_of(buildings);
}
}

**Comment by agrignard** [comment]
@hqnghi88 overriding the customizing function can indeed be a good idea
