### ISSUE TITLE
Wrong arithmetic operation order with "^" 

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2519]
**Describe the bug**
Operation "-" has priority over "^", which is totally wrong.

**To Reproduce**
with the following line:

write - 5^2;

The value returned is 25, but we should get -25.

 - OS: win 7
 - GAMA version: 1.8
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
What is totally wrong ? You're comparing apples and oranges there, unary and binary operators. In the majority of computer languages (in Smalltalk, in Java, at least all the languages I know), unary operators have precedence over binary and n-ary operators. See for instance https://www.leepoint.net/data/expressions/precedence.html. So -5^2 is evaluated as (-5)^2, which is perfectly correct.

**Comment by tnguyenh** [comment]
Good to know. However, in mathematics, -5^2 is -25, and not 25. Languages I know use the rule of precedence of ^ over -, even if - is considered as unary. This is true in Maple, Matlab, or even in Google search engine, it looks like a lot of people mix apples and oranges :) See for example the documentation for Matlab: [](https://fr.mathworks.com/matlabcentral/answers/97122-why-do-unary-operators-like-and-used-in-conjunction-with-numbers-not-have-precedence-over-th). I don't know and did not test for other languages. But I didn't imagine when I opened this issue that precedence rule do not always match the ones of mathematics (or even be contradictory like here).

**Comment by hqnghi88** [comment]
https://en.wikipedia.org/wiki/Order_of_operations
Interesting exception:
There are differing conventions concerning the unary operator − (usually read "minus"). In written or printed mathematics, the expression −32 is interpreted to mean 0 − (32) = − 9,[1][4] but in some applications and programming languages, notably Microsoft Excel (and other spreadsheet applications) and the programming language bc, unary operators have a higher priority than binary operators, that is, the unary minus has higher precedence than exponentiation, so in those languages −32 will be interpreted as (−3)2 = 9.[5] This does not apply to the binary minus operator −; for example while the formulas =-2^2 and =0+-2^2 return 4 in Microsoft Excel, the formula =0-2^2 returns −4. In cases where there is the possibility that the notation might be misinterpreted, a binary minus operation can be enforced by explicitly specifying a leading 0 (as in 0-2^2 instead of just -2^2), or parentheses can be used to clarify the intended meaning.

**Comment by agrignard** [comment]
That's an interesting topic to see that for some langage they did't choose the "original/offical" mathematical convention, it might be because of some historical reason maybe at a time when unary operator where faster/easier or slower/harder to execute so maybe this drive the order?

@AlexisDrogoul any idea about this? Is it pure convention or is there any reason? In any way I can understand that people coming from the "mathematical" world can be surprised

**Comment by AlexisDrogoul** [comment]
It is of course pure convention, both for programming languages and mathematical notations. When I say in English "minus 5 raised to the power of 2", do I mean "minus, 5 raised to the power of 2" or "minus 5, raised to the power of 2" ? There is a choice to be made here if you want to simply interpret the first sentence. Since the choice will not match all the intended meanings (because the sentence is ambiguous), languages offer ways to disambiguate it, usually parentheses to express higher precedences, so instead of `-5^2` you can write `(-5)^2` or `-(5^2)`. It's simply a matter of knowing whether your language applies precedence rules between unary and binary operators (which is the case in GAML: https://gama-platform.github.io/wiki/Operators, paragraph "Priority between operators", where you can see that unary `-` and `!` have a higher priority than arithmetic operators).
