### ISSUE TITLE
Operator "sort_by" not working with mixed lists (int and float)

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2521]
**Describe the bug**
When using the operator "sort_by", I get a "wrong casting" error.

**To Reproduce**
Use the code line:

list<float> truc <- [24.5,6,4,9,12.5,21,1,5,24,12] sort_by (each);

then I get the following error:

![image](https://user-images.githubusercontent.com/18676913/44314365-a0dfec00-a418-11e8-9306-4c4d87b9e758.png)

**Desktop (please complete the following information):**
 - OS: win 7
 - GAMA version: 1.8
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
Yep. A very peculiar case (with a mixed int/float list not already casted to either list<float> or list<int> by other operations and an operator that directly uses each of the values, without transforming them), but an issue anyway, that also shows up in `max_by`, `min_by`, etc.. I've fixed it in the forthcoming commit by coercing the value of `each` to the type expected by the sorting function. 
I've also taken this occasion to add a validator to sort_by so that only 'comparable' values can be used (e.g. int, float, point, string, color, etc.).
