### ISSUE TITLE
Increased memory consumption in a model 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2531]
**Describe the bug**
Once again a difficult bug to document especially because I saw that and it might have appear a long time ago.

I noticed that the memory goes really high on some model but it seems that it also happen on a simple road traffic model

**To Reproduce**
Open CityScope_main.gaml and run CityScoppeVolpeDemo 
https://github.com/CityScope/CS_Simulation_GAMA/tree/master/CS_CityScope_GAMA

or 

Building Elevation.gaml

**Expected behavior**
It use to be more around 500Mb.

**Screenshots**
On windows I reach 2gb for CityScope 
![img_3154](https://user-images.githubusercontent.com/3928502/44589485-ade93c00-a786-11e8-8185-6c2efdb4003f.jpg)

On mac I reach 240% of the CPU and more than 1gb og memory for building elevation 
<img width="643" alt="screen shot 2018-08-24 at 10 35 41" src="https://user-images.githubusercontent.com/3928502/44590607-85167600-a789-11e8-9c42-448fd0920536.png">

<img width="582" alt="screen shot 2018-08-24 at 10 42 55" src="https://user-images.githubusercontent.com/3928502/44590989-7ed4c980-a78a-11e8-8133-25d315e3619a.png">

**Desktop (please complete the following information):**
 - GAMA version: GAMA1.8_Win_64_08.23.18 - Java version: [e.g. 1.8]

**Additional context**

**Comment by AlexisDrogoul** [comment]
Sorry, which model are you talking about (CityScope, Building Elevation) ? Which exact version of GAMA (w, w/o JDK) ? On which PC with which characteristics ? And with which version are you comparing it ? 

On a side note, given the size of GAMA now and the number of libraries used, I don't see anything abnormal in having 250% of CPU used when a model is running (esp. with displays, even if they are OpenGL) on a partition of 1GigaBytes (which is probably what is in the ini file, no ?). That's exactly what I have too. 

The best thing you have to do, in my opinion, is to grab a free copy of YourKit Java Profiler and monitor an old version of GAMA and a new one on the same model to have a clearer idea of the memory occupation of the two and on the increase.

**Comment by agrignard** [comment]
I am a bit rusted in YourKit, I basically run it (on my model that is still running since 4 hours and is now at 1.8Gb)
<img width="783" alt="screen shot 2018-08-24 at 16 56 57" src="https://user-images.githubusercontent.com/3928502/44607525-beb5a400-a7be-11e8-8710-f79e3329be57.png">

This is the results of the profile snapshot running on 3D Visualization/models/Building Elevation.gaml

<img width="1640" alt="screen shot 2018-08-24 at 16 57 38" src="https://user-images.githubusercontent.com/3928502/44607562-d7be5500-a7be-11e8-924a-b81072057d53.png">

What kind of other information would you like  from the profiler?

**Comment by agrignard** [comment]
Ok so I am trying to track this unfortunate memory leak.

I have try different model incremental in term of "display and behavior" complexity

1. Gama alone without any model : 400Mb
2.Tutorials/3D/model/model 3. gaml: Simple sphere wandering : 550Mb stable
3.Features/3D Visualization/Models/Building Elevation.gaml
   3.1 Desactivate the move reflex: 690Mb stable
   3.2 Just make people wander (do wander) : 730 Mb Stable
   3.3 Make people waner on the graph (do wander: 770 Mb stable
   **3.4 Normal behavior with goto: increasing memory** (1Gb after 15 000 cycles) and as shown previously it reach 2gb in several hours.

So could it be the goto that takes more memory than before? the question now is why do we have this memory leak and when did it appear at some point ? I have tried with some version around July and it looks the same.

What I know is that I have been running demo for a long time (several days)  with the GAMA RC2 (around november 2017) and the memory was stable (the computer on which we are running the demo is running different software and there is no room for GAMA running 2gb of RAM in one day. It was also a kind of proud of the fact that GAMA was the lighter software compare to Unity and Grasshopper. Gama is now the heavier with the same model running. There is few room in this computer for a third greedy software (I am the one complaining that Unity and GH are so so heavy compare dwith GAMA (they also take around 2gb of ram to run). 

Unfortunately I cannot run easily version GAMA 1.7 RC2 to track back which version was ok (I cannot launch those version anymore from my computer (version of JAVA?). Do you think the benchmark:true facet could help to track this bug? Did the java profiler help?

**Comment by AlexisDrogoul** [comment]
And when you collect the garbage? Does it go back to a normal size? Because
if you give GAMA 2gb of ram, it will probably use them until it needs to
gc. Try giving Gama 500mb, for instance and see what happens.

Le sam. 25 août 2018 à 19:29, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
Ok i'll try to change the .ini to 1gb (it seems indeed to limit the amount of RAM at least on my Mac). For my specific issue that could be an option (then GAMA is not the big one tacking all the memory). When you say can you collect garbage is there a way to do this in GAML? I see the little trash in the UI bu tit doesn't affect the memory I see in my activity monitor (I might do another issue for this).

However I am a bit surprised that by default GAMA is not doing its best to reduce the consumption in term of memory. I mean it's a bit like if you buy a car that by default will consume a lot (even if it's not needed) but if you want you can go to the mechanic or fix it yourself (if you know how to do it) to reduce the consumption.

I don't know how exactly how the garbage collector works, I just have the feeling that GAMA didn't reach that amount of memory before and I don't see why the memory actually increase in that kind of model where we don't create new object during the simulation.

**Comment by AlexisDrogoul** [comment]
@agrignard I don't understand your problem and what you are complaining about. If you want GAMA to consume only 200Mb, set Xmx to it (or less) and that's it. You'll not be able to run all models and millions of agents, but you will have a "small GAMA". 

And please try to understand how the JVM memory management works before, maybe ? GAMA is creating **hundreds of millions** of objects every minute, like any other complex Java program, most of which can be collected by the GC because they have a very short life (i.e. the list you return from a result, etc.). If you allocate it 2GB, depending on your Garbage Collect configuration (and you can play with the parameters if you want, they are documented in the Oracle sites), you will reach 2GB at some point in GAMA unless you allow frequent Garbage Collection, which is not a good idea when running simulations. The '-server' option is precisely here to allow for a continuous performance rather than continuous garbage collection. If you want, you can try different configurations (with or without '-server', playing the Xms, Xss, Xmx, meta sizes, and types of GC), maybe one will fit your needs for this model. 

The memory allocation in GAMA is particularly optimised, and (if we remove the fact that Java 8 consumes more memory than previous JDKs) the same models do not consume more memory now that they were one or 2 years ago. After that, it is always possible that there might be **memory leaks** in some algorithms, but then try to track them with the appropriate tools (not the task manager, which gives you the whole memory consumption of the JVM and not the heap memory, which you are interested in), but YourKit, for instance. Launch a model for some time with memory profiling turned on. Kill the model. Collect the garbage in GAMA. Then observe what objects might still be residing in memory while they shouldn't (graph instances, agents, whatever). Then relaunch again to see if you can identify leaks.

**Comment by hqnghi88** [comment]
Dear Arnaud,
Is your model use opengl? I have seen a slowndown phenomenon in current gama git. 
Dear Alexis,
Does yourkit show the leaking of ipengl pipes?
I have tested two version s: 1.7 rc and git. I realized a really slowndown in git regarfing with 1.7rc (by eyes). I did not mention the memory, just the performance is seem to be slow down in Procedural city model 3d.
I will post an issue with video or  an reproducible tracking ( if i can find out).
Just ask for your opinion if it should relate with thist memory issue?

**Comment by agrignard** [comment]
Ok so it's more clear now. No problem I can play with the config (once again I am playing the role of the user here that by default will have a full 2Gb consumption of memory and will never understand why because he is not a java developper). Once can argue it's nothing knowing that we all have big computer now. What I know is that I can clearly recognise  when GAMA is running or not in my computer just by listening my fan. But ok this is how it is let's say that JAVA is a greedy guy.

So to finish this issue, I will dig  the solution you provide (to reduce the Xmx is enough for this specific case (I will see a bit more what is this -server option).

1However this is what I tried to documented in one of my comment above there is a different behavior between **wander** on **goto** (maybe it is justified) if not I will do a new issue dedicated to this.

Finally maybe the difference I see between GAMA 1.8 and GAMA 1.7 that it was running with JDK7 and it is now using JDK8, why not (but it's a huge increase then).

And then it can be important to document (for the non java developper) the different option he can play with in order to have either a version that consume a lot but that is very efficient or something less efficient that can run longer without consuming too much.

**Comment by agrignard** [comment]
@hqnghi88 yes there are using Opengl but I didn't notice a specific decrease in term of rendering performance. In my case the speed of the simulation is ok it's just a question of memory consumption.

I think you can create a dedicated issue for the opengl one (I quickly checked procedural cities and it looks fine but maybe you're right)

**Comment by AlexisDrogoul** [comment]
To let you play with this, I have added an action to experiment agents called "compact_memory" that simply calls `System.gc()`. You can add it in any experiment, for instance like this: 

```java
	reflex compacting when: every(100#cycle) {
		do compact_memory();
	}
```
And you will see that the variation of memory used  is actually very small (on my computer, it remains between 75mb and 150mb) -- but you have slowdowns every 100 cycles.

@hqnghi88 : I didnt notice any slowdown in the simulation. And if there are slowdowns in the OpenGL display, the best way to check it to see the difference in FPS (I get ~90 FPS at a constant rate). It is however possible that displays with textures are now slower to show than before since the the improvements made to their appearance.

**Comment by hqnghi88** [comment]
Sorry I did not use right notion. It should probably be the visualization 3dwhich has been slow down. If you say so, i will dig it And post an enhance issue ( if it is not caused by specific hardware conf) as the decreased is just 5-10% and should relate with textures or lights.

**Comment by agrignard** [comment]
Ok I'll try to System.gc() even if from what I now understand controlling the heap memory doesn't have a big impact on the global foot print of the JVM... I just test quickly to set a 256 XmX the global foot print is still close to 750Mb (so more than 200% of the heap...)

To control the hole JVM foot print it is indeed more complex 
https://betsol.com/2017/06/java-memory-management-for-java-virtual-machine-jvm/

So I get the point that different option will give different behavior ( '-server', playing the Xms, Xss, Xmx, meta sizes, and types of GC) and I guess the current configuration in Gama.ini as good reason to be the one it is now.
