### ISSUE TITLE
Randomness in GAMA

### ISSUE THREAD

**Issue by ClemensM1** [gama-platform/gama#2551]
Hey all,

I'm interested in the exact working of the one_of operator in GAMA. What is the underlying distribution or logic for this operator?

In the documentation (https://github.com/gama-platform/gama/wiki/OperatorsNR#one_of) it says a value at a random key is returned, but how is this random key generated?

Thanks for your help!

Clemens

**Comment by ClemensM1** [comment]
perfect, that's what I was looking for. Thanks so much 👍

**Comment by ILHEM88** [comment]
Hi Benoit, 
I have a small question about the same subject. If I want to choose uniformly one agent form the living population  (there are creation and death of agents in time) when we apply the myagent <-one_of(population) does the choice concerns only the living agents?  I test it and I found that all the time the chosen agent is alive through the operator "dead(myagent)" that is always false. 
Thank you in advance 
Ilhem

**Comment by benoitgaudou** [comment]
Hi,

First of all this is not the location to post questions; but this is the place for issues.
Please ask your questions on the mailing list: gama-platform@googlegroups.com

For your question, yes when you chose a random agent in the population of a species you will always get a living agent. 
The only small point you have to pay attention is when you store an agent in an attribute of an agent.
When the agent dies, the attribute keeps the value of the agent, but the agent is dead.

See this small example as illustration.

``` 
model NewModel

/* Insert your model definition here */

global {
	toto t;
	init {
		create toto number: 10;
	}
	
	reflex before {
		write " ------- " + cycle + " --- before";		
		write t;
	}
	
	reflex t {
		t <- one_of(toto);
		write " ------- " + cycle;
		write t;
		write "" + list(toto) + " - " + length(toto);
		write toto accumulate (dead(each));
		ask t {
			do die;
		}
		write t;
		write "" + list(toto) + " - " + length(toto);
		write toto accumulate (dead(each));		
	}
	
	reflex after {
		write " ------- " + cycle + " --- after";		
		write t;
	}
}

species toto {}
experiment exp {}
```

**Comment by ILHEM88** [comment]
Hi Benoit, 
Thank you for you for your explanation. I want just two small clarifications to end my conversation here, I'm sorry.
1/ In your example, if the agent is dead, the list toto list change by eliminating the dead agent which is normal, I don't understand the relation with what you just explained to me about the change in the attribute. 

2/Actually my first question was about the way that one_of chooses one living agent.  since one_of chooses uniformly one agent from the living agent what if the list is like that: (agent0, agent2, agent5) the others are dead does GAMA uses another list for example (0,1,2) and we chose uniformly on element form this last for example 1 that correspond to agent2? 
Thank you in advance 
Ilhem

**Comment by ILHEM88** [comment]
Hi Benoit, 
Thank you for your explanations. Actually my first question was about the way that one_of chooses one living agent.  since one_of chooses uniformly one agent from the living agent what if the list is like that: (agent0, agent2, agent5) the others are dead does GAMA uses another list for example (0,1,2) and we chose uniformly on element form this last for example 1 that correspond to agent2? 
Thank you in advance 
Ilhem

**Comment by benoitgaudou** [comment]
Hi,

1/ the example with the population of agents and an example "stored" /
referenced in an attribute was only to show that when an agent dies it is
removed immediately from the population but that it remains as an object of
the simulation (in a dead state) that be still be referenced by an
attribute.

2/ Basically it is what you mention: for any container GAMA uses the list
of keys (here index) and chooses a random one and thus returns the
corresponding element.

Cheers

Benoit

**Comment by ILHEM88** [comment]
Hi Benoit 
I understand your explanations. thank you very much for that. 
Best regards 
Ilhem
