### ISSUE TITLE
Java error: illegal argument arise only with all parallelism switch enabled

### ISSUE THREAD

**Issue by enrricomv** [gama-platform/gama#2552]
**Describe the bug**
If I configure Gama-1.8_RC2 in order to "Make species schedule their agents in parallel" enabled, in a random way Gama raise a "Java error"

This happens in the MacOS release and in the Linux64 one (Ubuntu 16.04.5)

**To Reproduce**
Run an experiment with 10k agents

**Expected behavior**
No Java error

**Screenshots**
<img width="2522" alt="screen shot 2018-09-17 at 18 43 40" src="https://user-images.githubusercontent.com/33745781/45637655-5602d400-baab-11e8-8f8b-1ab58791b278.png">

**Desktop (please complete the following information):**
 - OS: [macOS High Sierra AND Ubuntu 16.04.5]
 - PC Model: []
 - GAMA version: [1.8_RC2_EmbeddedJDK ]
 - Java version: [e.g. 1.8]
 - Graphics cards / Display system: [can be useful for displays, OpenGL problems]

**Additional context**

**Comment by AlexisDrogoul** [comment]
Please be more specific about the model you are testing and and what it
does, as this is not reproducible for all models.

Secondly, what Gama provides is the possibility to run agents in parallel,
but it will not solve the concurrency problems that may exist in a model by
magic. So, without the model itself, there is nothing that can be done to
'solve' this issue.

Le lun. 17 sept. 2018 à 23:59, enrricomv <notifications@github.com> a
écrit :

**Comment by benoitgaudou** [comment]
Hi
I was able to reproduce the error message with the model3 of the trafic tutorial in the model library.
I changes the numbet of created agents to 10000, run the model.
After some steps the issue appears...

**Comment by AlexisDrogoul** [comment]
OK. I have issued a simple fix for the most important bottleneck (and error generator) of parallel runs:  the QuadTree. For the moment, we had to keep the agents sorted in the quadtree in order to faithfully reproduce experiments (see #723). However, this constraint does not exist anymore when species run their agents in parallel (as they depend on the threading mechanism), so it is possible to remove it and use concurrent maps. Please note that this only applies (for the moment) when the general preferences is set to true (not when individual species define the concurrency level).
