### ISSUE TITLE
call of actions with and without operands

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2596]
**Is your request related to a problem? Please describe.**
I was not able to find whether this enhancement has already been discussed.

I have the feeling of an incoherent way of calling actions with and without operands. See the example below:
```
global {
	init {
		create toto;
		ask toto {
			do dodo;
			do dodo();
			do dodoParam(4);
			
			write fofoParam(3);
			write self fofoParam(3);	
			write self.fofoParam(3);		
			
			write fofo();
		//	write self fofo();  // Compilation error 
			write self.fofo();
		}
	}
}

species toto {
	action dodo {
		write "dodod action";
	}
	
	action dodoParam(int t) {
		write "dodod action " + t;
	}
	
	float fofo {
		return 0.0;
	}
	
	float fofoParam(int t){
		return float(t);
	} 
}

experiment Test type: gui {}
```

**Describe the solution you'd like**
As an action with a parameter can be used with the syntax `self fofoParam(3)`, it seems coherent to be able to call in the same way `self fofo()` but this provides a compilation error.
```
			write self fofoParam(3);	
			write self.fofoParam(3);		
			
			write fofo();
		//	write self fofo();  // Compilation error 
```

**Comment by AlexisDrogoul** [comment]
The problem lies in the grammar, at a completely syntactical level. `k1 k2()` cannot be recognised as an expression while `k1 k2(k3)` can. The reason is really simple: the latter can be assimilated to an n-ary operator, which allow to declare the first argument before the operator itself, while the former is a unary operator, and they do not allow this inversion.  Besides this, however, I am in favour of removing the possibility to write  `write self fofoParam(3);` and to only keep the dotted notation. 
What's your opinion on this ?
