### ISSUE TITLE
self in attributes: facet of a save

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2605]
**Describe the bug**
In the save statement, when we want to save attributes of the agents we want to save, we sometimes need to use the self pseudo-variable. See e.g. "Save to SHP.gaml" in the features:
```
save building to:"../results/buildings.shp" type:"shp" attributes: ["ID":: int(self), "TYPE"::type];
```

This line works perfectly (the shapefile is well-created with the expected value in ID), but the compiler detects it as being an object of type "model".

as a consequence in the following line, an unexpected warning appears on the `roads_weight[self]`:
```
map<road,float> roads_weight <- road as_map (each:: each.shape.perimeter * (each.slow ? slow_coeff : 1.0));

save road to:"../results/road_network_weighted.shp" type: "shp" attributes:["weight"::roads_weight[self]]; 
```

**Expected behavior**
The `self` should of type `road`instead of a model.

**Desktop (please complete the following information):**
 - OS: macOS mojave
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
There is a problem of consistency here (I remember the `attributes` facet had been added to allow the computation of expressions when saving shape files, but it has not been thought about completely.. ). Because the parser is correct in emitting a warning: `self` is the agent that executes `save` if we refer to GAML's grammar; however, in the same map, the existence of attributes is verified against the species that is saved (and not this `self`). Then the execution, for reasons I perfectly understand, substitutes each agent of the species when interpreting `self`, as if it was interpreting `each` inside an iterator. 

We have to make a decision here, because this situation is really too ambiguous and makes some operations not only confusing, but also impossible to do: what if I want to refer to the saving agent in this expression ?

**I would be in favour of adopting the same policy than for iterators**, i.e. allowing to declare iterator facets, where `each` could be used to represent each agent of the denoted species (and `self` would represent, correctly, the calling agent). 

@benoitgaudou @ptaillandier @sriramab : what's your opinion on this ?

**Comment by benoitgaudou** [comment]
The situation is indeed very ambiguous and it could be great to make it clearer.
The solution with each seems from my point of view very good to this purpose.

**Comment by AlexisDrogoul** [comment]
I'v actually chosen a different strategy. Facets can now be declared as using a "remote context" (like statements as `ask`, for instance). This enables them to use `self` and `myself` with `self` representing an agent of the species denoted by the statement and `myself` the agent calling the statement. In your case, `self` is then correctly of type `road` and `myself` allows to access the world.
