### ISSUE TITLE
Create statement with a species attribute given as parameter of an action

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2611]
**Describe the bug**
The following model showed a compilation error on the create, with the error "Species cannot be determined". But this model should work (and many MAELIA code is based on that :-) ).

```
global {
	init {
		do toto(a);
	}

	action toto(species<agent> agt) {
		create agt number: 1;
	}
}

species a {}
 ```
The commit 3be6cb2 was made to allow the previous model to compile.
Nevertheless I made it a little bit too fast, and add a warning in the validator.

Perhaps this should be double-checked.

**Desktop (please complete the following information):**
 - GAMA version: git

**Comment by hqnghi88** [comment]
Dear Benoit,
I want to ask a very small question: why not use species<a> instead of species<agent>. Agent is more generally but what maelea do in toto beside create? even with init values , species have different attributes?
global {
	init {
		do toto(a);
	}

	action toto(species<a> agt) {
		create agt number: 1;
	}
}

species a {}

**Comment by AlexisDrogoul** [comment]
`create agt; ` should not emit an error, not should it emit a warning, as it is perfectly correct even with `species<agent>`. Errors should be emitted only if the modeler wants to access an attribute which is not available in `agent`, for instance, later in the code. But the definition of `create` here is ok. So, no error, no warning !

**Comment by AlexisDrogoul** [comment]
I think we can close the issue if you remove the warning, no ?

**Comment by AlexisDrogoul** [comment]
I've taken a closer look at the problem, and I have to admit the original behaviour was correct. 

```
action toto(species<agent> agt) {
		create agt number: 1;
	}
```
**SHOULD NOT BE ACCEPTED**

The reason is that it would allow to pass in arbitrary species to `create`, including abstract or "forbidden" ones, like mirror species, etc. 

So the model provided as an example should not compile and should not work. If a lot of MAELIA code is based on this, then the scope of the parameter in the models should be restricted (i.e., as @hqnghi88 suggests, `species<a>`). 

As a consequence, https://github.com/gama-platform/gama/commit/3be6cb25e29628a255e4ecc34d48da9cad6700f8 should be reverted...

**Comment by AlexisDrogoul** [comment]
OK. After a lot of thought about this issue and #2621, I've decided to relax the constraints existing in the compilation phase, so as to allow passing not-yet-known species to `create`.  A more thorough validation is made at runtime.
