### ISSUE TITLE
Providing a weight with type integer prevents adding more than one edge in a graph

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama#2617]
It seems that the "edge" constructor requires the weight to be of type float. Providing a weight of type int produces strange behaviours:

1) With the following syntax, it works as expected. The graph eventually has 2 edges.

model essai

global {
	graph<geometry, geometry>  the_graph <-  graph<geometry, geometry>([]); 

	init{
		the_graph <- the_graph add_node {0,0};
		the_graph <- the_graph add_node {1,1};
		the_graph <- the_graph add_node {2,2};
		
		add edge({0,0}, {1,1},1.0) to: the_graph;
		write the_graph;
		add edge({0,0}, {2,2},1.0) to: the_graph;
		write the_graph;	
	}
}

experiment simulation type: gui {}

2) For the following model (same model, with an integer weight), the second addition of an edge doesn't work. However the lines "add edge[...]" trigger a warning.

model essai

global {
	graph<geometry, geometry>  the_graph <-  graph<geometry, geometry>([]); 

	init{
		the_graph <- the_graph add_node {0,0};
		the_graph <- the_graph add_node {1,1};
		the_graph <- the_graph add_node {2,2};
		
		
		add edge({0,0}, {1,1},1) to: the_graph;
		write the_graph;
		add edge({0,0}, {2,2},1) to: the_graph;
		write the_graph;	
	}
}

experiment simulation type: gui {}

The warning is somehow not so clear:

The type of the elements of the_graph(geometry) does not match with the type of the argument (int). The argument will be casted to geometry.

3) The following model doesn't work properly. Only one edge is created. Furthermore, there is no warning at all in the editor.

model essai

global {
	graph  the_graph <- []; 

	init{
		the_graph <- the_graph add_node {0,0};
		the_graph <- the_graph add_node {1,1};
		the_graph <- the_graph add_node {2,2};
		
		
		add edge({0,0}, {1,1},1) to: the_graph;
		write the_graph;
		add edge({0,0}, {2,2},1) to: the_graph;
		write the_graph;	
	}
}

experiment simulation type: gui {}

**Comment by AlexisDrogoul** [comment]
Indeed this does not work and it will never work properly (unless large changes are made to the addition/removal of edges and vertices or I implement a trick). The reason is that `edge` with 3 parameters comes in 2 flavours: one with a `float` parameter at the end, to express the weight attached to the edge; one with any other type at the end (integer, string, whatever), to represent the actual object that is wrapped by the edge.

So in your case, what you are doing amounts to adding edges that wrap an integer. That is why, in the 3rd case, you only obtain one edge: you add 2 times the edge `1` to the graph (changing its vertices).

The trick I can implement is to consider that, by default, using this operator with `int`s  is equivalent to using it with `float`s . So, writing `add edge({0,0}, {1,1},1) to: the_graph;` would add an edge between the 2 vertices with a weight of `1.0` and adding the edge `1` between these 2 same vertices would require to use the 4 parameters form of the operator, namely: `add edge({0,0}, {1,1},1, 1.0) to: the_graph;`. 

What's your opinion on this ?

**Comment by AlexisDrogoul** [comment]
I don't see for the moment another way than the one exposed in the previous comment to fix this issue. I am going to commit the changes and close it. Please reopen if you think it creates more problems !

**Comment by tnguyenh** [comment]
I just reopen and close to say that I'm perfectly fine with your solution. I didn't know exactly how the operator work, since the documentation is incomplete. By the way, when typing "edge" and choosing the operator "edge" in the list redirects to the edge category, which doesn't mention the operator "edge". It is still possible to find the operator in the full list, however there is no description of the different usage, which could be have been useful.
