### ISSUE TITLE
save attributes in shapefile (using a map instead of a list of pairs) does not save the attributes

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2620]
**Describe the bug**
Consider the model of the library Features / Save statement / Save to SHP.gaml.
It uses the following syntax:
```
save building to:"../results/buildings.shp" type:"shp" attributes: ["ID":: int(self), "TYPE"::type];
```

But the documentation of the facet `attributes` explains this facet is expecting a `map`. 
So we tried the following syntax (casting the list of pairs in a map) 
```
save building to:"../results/buildings.shp" type:"shp" attributes: map(["ID":: int(self), "TYPE"::type]);
```

Now the geometries are properly saved, but no attribute is saved (there is no column in the attribute table).

**Expected behavior**
The two syntaxes should work (saving attributes).

**Desktop (please complete the following information):**
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
The documentation is not explicit enough: only literal maps (what you call `list of pairs`) can be used here. The reason is simple and related to #2605 : these maps are used as functions, evaluated for each agent, and not as a constant which would be evaluated only once. But when you use `map`, you actually force the expression to be evaluated... 

I will issue an explicit warning in this case.
