### ISSUE TITLE
Travis failing unexpectedly

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama#2708]
**Describe the bug**
Again, Travis is failing to validate the models of the library. See for instance this build : https://travis-ci.org/gama-platform/gama/builds/531023637?utm_source=github_status&utm_medium=notification

<img width="594" alt="image" src="https://user-images.githubusercontent.com/579256/57564692-23ab3b80-73da-11e9-9ad3-19bb729eaef5.png">

The error is pure nonsense...

**Comment by hqnghi88** [comment]
I am totally lost. I take the 3 old commits that make gaml compilation error in travis and play with it in its own branch, to be sure no others modifications affects them. And the results are too confuse : 2 of them is fixed with model modification (Ant: comment the lines contains error, Model 13 : ((predator as list) max_of each.energy)) ==> (predator max_of (each.energy)) ) and 1 is fixexd by next launch of travis.

in addition, Thread.sleep(15000) after preloadGAMA() or after GamlModelBuilder.loadURLs did not help. And after GamlModelBuilder.loadURLs, even an iterating through folders show that all the model are there, the compilation error still occurs. When it occured, it was always the same model, the same place, the same error.

At last, the second launch of headless for validation always remove the error.
Any guide would be very nice (even it must take sometime).
Thanks.

**Comment by hqnghi88** [comment]
Lets take an error that travis say
Unknown field 'energy' for type image_file 
This come from the line i add in model 13:
write ((predator as list) min_of each.energy);
So the error is totally no meaning.
Then I trace the compilation process by observing the log at bottom of logs:
7371 https://travis-ci.org/gama-platform/gama/builds/534535076
7372 https://travis-ci.org/gama-platform/gama/builds/534536355
7373 https://travis-ci.org/gama-platform/gama/builds/534537001

In the normal (local) gama, the trace show that compilation has found the right type list of predator. 
  GEComp casting list<predator>


But in travis the trace shows a nonsense type: list of image_file 
  GEComp casting list<image_file> 

The core thing in these compilation trace lead to ParametricType.java -> createParametricType()
And this function always use cache the types with an algorithm like hash table (i think)

			final Integer key = t.hashCode() + ct.hashCode() * 100 + kt.hashCode() * 10000;
			ParametricType p = CACHE2.getIfPresent(key);

It seems that the calculation of key has chose wrong  (a same key for 2+ elements).  So i try these build above with:
7371 , 7373 : Cache false
7372 Cache true
The result show that it is reasonable (reproducible).
There is one more case in the past (the one with Ant Foraging model) that i must re-test too.

@AlexisDrogoul 
Yes, i totally agree with the spirit of caching as decrease the memory used for big models. But i am wondering as this phenomenon already take all library models into account (355 models+) , can be considered as a big model (comparing with Maelia? i dont have this source to test). As i specify above (may be im wrong) the calculation of key need to be reviewed?

**Comment by AlexisDrogoul** [comment]
Hello @hqnghi88 , again, beautiful work ! I sent you by mail an alternate version of ParametricType, it may be worth to check it. One of the reasons why it could be important is to enable the identity tests between types (not only to gain some memory).

I guess however that a clean implementation should rely on TypeManager (the builtin and the ones built for each model)...

**Comment by hqnghi88** [comment]
I tried your class,
Firstly , with the old, turn on USE_CACHE = true (https://travis-ci.org/gama-platform/gama/builds/534618537), it fails ,same error, to be sure it is not times event or travis'emotion relate
THen, with new version (https://travis-ci.org/gama-platform/gama/builds/534618635), it passed. 
Seems the solutions is fine. Hopefully for the clean implementation then.
Thanks.
