### ISSUE TITLE
File and Class not found when launching GAMA Git version 

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#2736]
**Describe the bug**
When launching Gama from Eclipse, I have a file not found exception about an icon in the ui.shared package. I have another error related to apache StringUtil class. It does not affect the usability of the platform.

**To Reproduce**
Launch the git version from Eclipse

**Screenshots**
Log file attached 

[consolOutput.txt](https://github.com/gama-platform/gama/files/3222682/consolOutput.txt)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - GAMA version: git

**Comment by AlexisDrogoul** [comment]
Verify your products, run configurations, etc. the plugin `org.apache.commons.lang` should normally be there in version 2.6.x. Is it the case ?

**Comment by hqnghi88** [comment]
with current git, I cannot reproduce, switch 5 workspace, refresh 2 times for each. The only way to reproduce (not sure) is when i revert to 4 days ago git. But in that case, clean configuration helped.

**Comment by AlexisDrogoul** [comment]
Impossible for me to reproduce this, also...

**Comment by hqnghi88** [comment]
@agrignard dont know if it is your case , if you are playing with some different gama version
I start with CI version in E:\Downloads, all models are found there.
Then i quit gama, remove the folder CI and start eclipse, gama. The library are blank, because the links are still point to deleted folder (e\downloads) even with several refresh, close, open.
![image](https://user-images.githubusercontent.com/6105384/58419797-c390e680-80b5-11e9-8df8-187e2fe46341.png)
Even with clean crash workspace.
So @chapuisk , Arnaud, if verification of launch product configuration does not help, please try to delete all library (DONT check the delete on disk) or try new workspace....
![image](https://user-images.githubusercontent.com/6105384/58420064-811bd980-80b6-11e9-94cb-ad3d6a1dbc06.png)

**Comment by agrignard** [comment]
Thank you @AlexisDrogoul and @hqnghi88 for the tip however I still have a blank library (after cleaning, synchronizing, restarting and creating new workspace etc)
I cannot delete all the libray as there is nothing inside 

Where do I check my  ````org.apache.commons.lang ````plugins? I dont find it in ````gama.runtime.product````

**Comment by AlexisDrogoul** [comment]
Are you sure your Git repo is up to date ? 
The apache plugin comes with Eclipse, and should be installed in the run configuration of your product (you can check in it). It is installed by one of the features of GAMA (`ummisco.gama.feature.dependencies`).

<img width="534" alt="image" src="https://user-images.githubusercontent.com/579256/58427328-79b1fb80-80c9-11e9-8541-8a308c0d37c2.png">

**Comment by agrignard** [comment]
I have this
<img width="799" alt="Screen Shot 2019-05-27 at 16 56 05" src="https://user-images.githubusercontent.com/3928502/58427596-5de62f80-80a0-11e9-9fa3-0436448b7a62.png">

Ok it works for me now after a Nth clean and applying the Run Configurations

I am ok with this issue I let @chapuisk confirm if it's working for him

**Comment by AlexisDrogoul** [comment]
Although I do not see why you would require a special setup, you could also try to reexport the plugin from msi.gama.ext, by changing the `Require-Bundle` section of its `MANIFEST.MF` file to : 

```
Require-Bundle: com.google.guava;bundle-version="15.0.0";visibility:=reexport,
 org.eclipse.osgi,
 org.apache.commons.lang;bundle-version="2.6.0";visibility:=reexport
```

**Comment by chapuisk** [comment]
On my side, it's getting worst ! I did a git clean, so I have nothing left locally and then a pull. @hqnghi88 when I try with a new workspace, I got the same error and not any models in the library. try to change the MANIFEST.MF, doesn't do much. I'll try to hard rebase on git ...

**Comment by chapuisk** [comment]
I start a fresh Gama git repo with a clone and get rid of the error ... I think I can close the issue, even if the problem could happen again. There is a delta between Eclipse git plugin and git command line that produce the issue somehow somewhere ...

**Comment by hqnghi88** [comment]
small thing i just want to make a trace here for future "somehow somewhere" , i just realize some small issue  like you two describe and i found the cause is the capitalization of model folders name, example: on my old base (another machine), i make a pull, in git bash, it is surely update, but i found in eclipse , there is a small ? in some place, ie, in maths plugin \ models\ Ordinary Differential Equations\ model\**technical details**, while in the updated online git, it is **Technical Details**, a small change but it seem egit is not smart enough.
