### ISSUE TITLE
Camera upside down in Boids using camera_pos

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2744]
**Describe the bug**
Open Boids 3D Analysis

In experiment ````MultipleView```` display ````ThirdPersonn```` change the value of the 

```` camera_pos:{int(first(boids).location.x),int(first(boids).location.y),250} ````

to 

```` camera_pos:{int(first(boids).location.x),int(first(boids).location.y),2500} ````

then run the model , the camera is upside down see screenshot. It was suppose to be seen from the top (with the referentiel on the top left).

Somethign related to y vs -y?

<img width="1339" alt="Screen Shot 2019-05-29 at 11 28 17" src="https://user-images.githubusercontent.com/3928502/58546059-e087ff80-8204-11e9-8537-730528f74b8f.png">
 

Git version (related to #2742)

**Comment by AlexisDrogoul** [comment]
I propose that you list these issues under #1878 if possible !

**Comment by AlexisDrogoul** [comment]
Reopening this issue for the next round of development on GAMA 2.0

**Comment by AlexisDrogoul** [comment]
Solved with https://github.com/gama-platform/gama/commit/9f59fce337ecc47700232869b365a1fd4f5f5331. The problem was the computation(s) of the "up vector"/orientation, messing up everything as soon as the other vectors were either too close or parallel. The decision taken was to remove all possibility for the user to fix this "up vector"/orientation and let GAMA compute it itself by default.
