### ISSUE TITLE
Keystone and camera position (to show simulation on a 3D map)

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2751]
Here is more a discussion than really an issue for the moment.

I had to show a simulation on a 3D map (HoanKiemAir project).

To make the simulation image to fit with the 3D map, I had to play with the camera position (in the 3 dimensions) and the keystone.

First of all I noticed that, when I run a simulation in fullscreen to configure the display on the 3D map and when I modify the camera location, if after that I enter in the keystone mode, it takes into account the camera location defined in the experiment.
----> is it an issue ?
But perhaps, it is a bad way of doing to modify both of them alternatively... 
@gnoubi, @agrignard, @tnguyenh : Do you have an opinion on this point ?

In addition, to save the modification made in the keystone, I had to open the lateral pane, click on the button "save as facet" for the camera, then copy paste it in the model code and do the same for the keystone. 
----> Would it be possible to have a button that modify the experiment ?

thank you in advance

**Comment by AlexisDrogoul** [comment]
You certainly won't have a button that modifies the experiment ! What if you want to create another one with these values, for instance ? What would be more practical, I guess, would be to have the camera and keystone editors available as a kind of overlay instead of being in the left panel and to be able to manipulate the camera and the keystone at the same time.

**Comment by agrignard** [comment]
@benoit welcome to the tangible simulation world!

Now that you are using this feature I am more than happy to discuss about it (I had a bit the feeling to be the only using it and requesting for improvement ) but I guess you experienced it during HoamKiem Air.

In my case in the different projects made the last 3 years dealing with tangible simulation I have always had a mix between playing with the physicla position of the projector first (te reduce the maximum the keystoning) then the camera and the keystone last. Unfortunately not that much with the keystone because of the bad quality rendering of a keystoned display (https://github.com/gama-platform/gama/issues/2174).

Usually, you need to set the camera position and then the keystone separetly with the copy facets. And then copy it in gaml in camera_pos facet and a keystone facet. It's bit difficult at the beginning but ones your configuration is done you just have to run your experiment with the right parameter.s.

So maybe we can create some more specific issues for now. In my case I found the camera and keystone current solution pretty usable the only drawback still remaining for me (even if the issues is closed is this one #2174)

**Comment by AlexisDrogoul** [comment]
I'm not sure someone tried turning antialias on and testing the result of keystone operations (regarding #2174). If it is improved (I have no real way nor time to check), then antialias could be turned on by default when keystone is applied.

**Comment by agrignard** [comment]
Yes it's definetly better with the anti-aliasing on however there is still some kind of anti-aliasing rendering. it's pretty straightforward to check by pressing 'k' and playing with the keystone. The line doesn't look exactly like straight line ones keystoned.

**Comment by AlexisDrogoul** [comment]
Just to point out that the definitions (of camera and keystone) are now copied automatically to the clipboard whenever you change one of them. It's the closest we can probably go in terms of automation of the process. The next step will probably be the possibility to save a whole experiment layout (incl. camera + keystone) to a new experiment file.
