### ISSUE TITLE
edge weights on undirected graphs are directed

### ISSUE THREAD

**Issue by rumenzu** [gama-platform/gama#2775]
**Describe the bug**
In the code below, an undirected graph is created with an edge and associated weight.
While the edge source and target can be reversed for checking containment, direction information is kept when associating a weight.
Hence, `weight_of` returns two different values depending on the edge direction, which is counterintuitive since we defined an undirected graph.

```gaml
global {
	graph foo <- undirected(graph([]));

	init {		
		add edge(1, 2, 0.1) to: foo;
		
		if foo contains_edge (2::1) {    // true
                    write (foo weight_of (2::1))  // 1.0
                    write (foo weight_of (1::2))  // 0.1
                }
	}
}
```

**Expected behavior**
As we work here with an undirected graph, the two `write` statements in the above code should print the same value, 0.1 in this case.

**Desktop (please complete the following information):**
 - GAMA version: 1.8

**Comment by AlexisDrogoul** [comment]
AFAIK, there are absolutely no rules / theories that say that the weights should be symmetric, because it ultimately depends on the meaning you attach to the weights in your graph, and also the meaning you attach to the "undirected" quality (see for instance here: https://cs.stackexchange.com/a/77646) . What you call intuition is clearly depending on these meanings ! 
I then close this issue -- feel free to reopen it if you feel this is important to state the difference or propose specific constructors...

**Comment by rumenzu** [comment]
Thank you for the feedback, I'll keep symmetry myself in the model.

However IMHO, if `contains_edge` returns true no matter the orientation while possibly having several edges (and their weights), you have some kind of degenerated multigraph semantics (where the maximum number of parallel edges is 2). If orientation matters, the user should stick with a digraph. But I'm simply writing my thoughts and I'm far from being an expert in graph theory.

I understand your concerns, transforming a digraph to a graph and merging edges is inevitably destructive. Perhaps two different keywords such as `graph` and `digraph` could be used to construct the respective types of graph, and only allowing transformation from a graph to a digraph could be kept. But maybe `undirected` is too popular to be removed.
