### ISSUE TITLE
Strange behavior of among with a conditioned list

### ISSUE THREAD

**Issue by Damapproject** [gama-platform/gama#2818]
**Describe the bug**
The facet among fails when using a list with a condition.

**To Reproduce**
```
list<int> lisa <- [1,2,3,4,5,6,7,8,9];
	
init{
	write "ok : " + 2 among lisa;
	write "not ok : " + 2 among lisa where (each > 5);
}
```

**Expected behavior**
The first among works normally, but the second one gives randomly an empty list, a list with one element, or a list with two elements which is the expected behavior.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GAMA version: 1.8
 - Java version: 1.8.0_191

**Comment by Damapproject** [comment]
It works when casted with list() or just with parenthesis!

`write "ok : " + 2 among (lisa where (each > 5));`

**Comment by benoitgaudou** [comment]
This is due to the order of execution of the operators:
in the case of `2 among lisa where (each > 5)`, first among is executed on `2` and `lisa`, which returns a list of 2 elements from lisa list.
Then `where` is applied on the new list and `each > 5`. So if all the elements are lopwer that 5, then the returnes list is empty.

**Comment by AlexisDrogoul** [comment]
@benoitgaudou you were too fast 😄 
Actually, `2 among lisa where (each > 5)` is an ambiguous sentence, which can be interpreted as: 

- `2 among (lisa where (each > 5))`
- `(2 among lisa) where (each > 5)`

Both are valid interpretations as far as human languages are concerned. In computer languages, however, a choice has to be made (the precedence from left to right, or from right to left, is fixed), and GAML uses the second one, which is why you obtain your results.
