### ISSUE TITLE
Graph.gaml 

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2861]
**Describe the bug**
The graph layouts `layout_circle` and `layout_grid` (at least in the way they are used in the mode `GAML Syntax/Data Types And Structure/Graph.gaml`) provides empty display. 

**To Reproduce**
1. Run the Graph.gaml model
2. Click on the button `Create graphs`
3. Click on the button `Layout Graph`
4. Now choose as layout `Forced` and click several times on the `Layout Graph` button (you will see the graph layout evolves but tending to a convergent configuration).
5. Choose now `Circle` or `Grid` as layout and click on the `Layout Graph` button.
The display becomes empty and white.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8.0

**Comment by AlexisDrogoul** [comment]
Can't reproduce it with Circle, but only with Grid (which seems to be empty all the time in my case).

**Comment by ptaillandier** [comment]
I just commit some fixes.... but the issue is still here.
To reproduce the bug, create a grid/intersection/distance graph, then apply twice the grid/forced layout.

The problem comes from the fact that once the locations of the vertices have been modified (by one of the three layout algorithm), it is not possible anymore to find the edges in the edgeMap.
