### ISSUE TITLE
Inheritance, reflex redefinition and execution order

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2872]
**Describe the bug**
A child species, when redefining a reflex of the parent species, can change the order of the reflex execution.

Consider the following model:
```
model NewModel

global {
	init {
		create parentSp;
		create childSp;
	}
}

species parentSp {
	reflex first_reflex {
		write "" + self + " in FIRST reflex";
	}
	reflex second_reflex {
		write "" + self + " in SECOND reflex";
	}	
}

species childSp parent: parentSp {
	reflex second_reflex {
		write "" + self + " in SECOND reflex - from children species";
	}		
}

experiment NewModel type: gui  { }
```

The parent species, when executed, provides the following log:
```
parentSp(0) in FIRST reflex
parentSp(0) in SECOND reflex
```

**Expected behavior**
When I execute a child agent, I was expecting the order to be preserved, and that the second_reflex executed to be the one of the child species.
```
childSp(0) in SECOND reflex - from children species
childSp(0) in FIRST reflex
```
But it seems that the reflex of the child are executed first, even if the redefine a parent reflex, what was unexpected.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: 1.8.0, git - master

**Comment by AlexisDrogoul** [comment]
I don't see it as an issue, as the semantics of reflex redefinition is actually not defined. It is stated that reflexes are executed in the order they are defined. But what should be the correct order, then, when you redefine some ? Suppose I have a species S1:

```
species S1 {
    reflex R1 {}
    reflex R2 {}
    reflex R3 {}
}
```
and S2, one of its children:
```
species S2 parent: S1 {
    reflex R4 {}
    reflex R2 {}
}
```

Now, how should the instances of S2 run their reflexes ? 

1. S1.R1, S2.R2, S1.R3, S2.R4 (as you seem to propose) ? But what if the redefinition of R2 in S2 depends on some code running in R4?
2. S2.R4, S2.R2, S1.R1, S1.R3 (as it is the case now, all the reflexes of S2 run before those of S1) ? We break the order defined in S1 but respect the one defined in S2. 
3. S2.R4, S1.R1, S2.R2, S1.R3 (unredefined reflexes of S2 first, then the order defined in S1) ? 

Many combinations are possible, but the problem is for modelers to be able to predict this order. Imagine what could happen with 3, 4, 5 levels of inheritance ! So the scheme "children reflexes first, followed by the reflexes of parents which have not yet been executed" is probably the simplest to remember in that perspective.

**Comment by benoitgaudou** [comment]
The question comes from the prey-predator tutorial.
And in particular, from the fact that inheritance is presented as specialization (/generalization).

In the tuto, a generic animal is presented with basically 2 reflexes (with the idea that such an agent first move, then eat).
```
species generic_animal {
  reflex move {}
  reflex eat {}
  cell choose_cell(); 
}
```

When comes the `predator` species, it is supposed to be a specialization of `generic_animal`, with the redefinition of some actions and reflexes: `choose_cell` is different and so is `eat`. So we write :
```
species predator parent: generic_animal {
  cell choose_cell() { ... }
  reflex eat { ... }
}
```

But now the predator first eats and then move. And only by changing something in the `generic_animal`, I do not see how to implement the predator.


So more generally, my preference would go to a solution where the order of the reflexes of the parent is not modified, the reflexes of the children coming before or after.
The current behavior prevents to, given a model, to specialize a species by redefining a reflex and keep the model execution logic...

**Comment by AlexisDrogoul** [comment]
Reflexes are not the right architecture to do this, and this should be
reflected in the tutorials.

One reflex that calls actions, which can be redefined in subspecies, is the
way to go, because we can not take the responsibility to change the order
of execution defined in a species (like in my example)





Le dim. 25 août 2019 à 13:44, benoitgaudou <notifications@github.com> a
écrit :

**Comment by AlexisDrogoul** [comment]
To be clearer, generic animals should be defined with :

```
reflex behave {
    do eat;
    do move;
}
```

And actions should be preferred to reflexes if inheritance is involved. This should be reflected in the tutorials !

**Comment by benoitgaudou** [comment]
Yep, I am modifying the model with the idea of redefining only actions.
I think I will keep the two reflexes eat and move, but integrating actions
in each of them, that will be redefined and children species.

Perhaps a warning on a reflex from the children species, redefining a
parent reflex, could warm the modeler against possible counter-intuitive
behavior of the model ?

Benoit

Le dim. 25 août 2019 à 14:39, Alexis Drogoul <notifications@github.com> a
écrit :
