### ISSUE TITLE
Problem with dxf file and world enveloppe 

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#2874]
**Describe the bug**
I have a model that is working on GAMA 1.8 and produce now a nil pointer exception on the current build. 

Here is the model 
https://github.com/CityScope/CS_Proxymix/tree/master/ProxymixABM

this syntax works on 1.8 

`````
file ML_file <- dxf_file("../includes/ML_"+curFloor+".dxf",#m);
geometry shape <- envelope(ML_file);
`````

In the current build when I run the model it produces this exception

`````
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in geometry shape <- envelope(ML_file) ;
NullPointerException: null
when applying the envelope operator on null
in initializing attribute shape
in agents Simulation 0, Proxymix0
`````

**Desktop (please complete the following information):**
 - Mac OS
 - Gama 1.8 Bin 26/08/2019

**Comment by ptaillandier** [comment]
The problem seems to come from the fact that you use a variable in the name of your file. For example, if you replace
file ML_file <- dxf_file("../includes/ML_"+curFloor+".dxf",#m);
by
file ML_file <- dxf_file("../includes/ML_3.dxf",#m);
it is going to work. I do not know why it was working before and not anymore.
