### ISSUE TITLE
when wander on graph, java error: nil value detected

### ISSUE THREAD

**Issue by EmilioMichael** [gama-platform/gama#2900]
when I run a simulation with wander, it works at first. However, when an agent gets into the "wander" status from another status, the error pops out. I have no idea what's going on. I spent several days to solve this problem but failed...it drove my crazy. If there anyone knows the solution. Thank you so much!

2 occurrences in 2 agents at cycle 6: Java error: nil value detected
in 
NullPointerException: null
in agents agent18, Simulation 0

**Comment by benoitgaudou** [comment]
Dear,

As we have no idea about your model, a sentence such as : 
"when an agent gets into the "wander" status from another status, the error pops out"
cannot be understood.

Could you share your code in order that we can identify the error.

The exception you are showing explains that you use an object with a nil value (i.e. it does not have a value). As an example, it could be due to the fact that the graph has not been created ...

Cheers


Benoit
