### ISSUE TITLE
tests coverage using coveralls.io

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama#2919]
Hi

Just found this being used by other projects. May be somethings useful for GAMA?
https://coveralls.io/

**Comment by hqnghi88** [comment]
Hello Sriri,
Thanks for the information. In fact , i did not know much what the test coverage mean, but we have a code analysist service already (sonarcloud) from @RoiArthurB . So just to be sure it is not double, why not, we can try it as it is free.

**Comment by sriramab** [comment]
May be duplicate, I dont know. Perhaps someone can assess which is more friendly.

**Comment by RoiArthurB** [comment]
Hi all !

First, what is a code coverage? Code coverage is the percentage of code which is covered by automated tests ( [wikipedia for more details](https://en.wikipedia.org/wiki/Code_coverage) ). So Coveralls (and many other tools) checks which part of the code is tested and which is not. 

In fact, [SonarCloud](https://sonarcloud.io/organizations/gama-platform/projects) propose that feature, but we do not use it because the code coverage used in GAMA is not test for the JAVA software but for the GAML language.
![image](https://user-images.githubusercontent.com/16764085/71416316-2bb1a600-2660-11ea-8f3c-ad3e657789cf.png)
