### ISSUE TITLE
csv dynamic

### ISSUE THREAD

**Issue by mayaaq** [gama-platform/gama#2925]
How to read CSV file contains graph(node, edge) in a dynamic way, node by node. And assign an agent to each a node.

**Comment by benoitgaudou** [comment]
Dear,

The following model (of the GAMA model library) : *CSV File Import.gaml*
shows you how to read a csv file line by line and cell by cell.
So I guess this can used for what you want to do ?

Cheers

Benoit

**Comment by mayaaq** [comment]
I need any reference help me in "assign one agent to each node from CSV file". Because I am beginner in GAMA.
Can you help me please?

**Comment by benoitgaudou** [comment]
In fact, "assign one agent to each node from CSV file" is not really clear
for me.
Do you want to create 1 agent per line of the CSV file (if one line
correspond to one node) ?
Then you have to ask you what you want to store in the agent ?

Cheers

Benoit

**Comment by mayaaq** [comment]
Yes I have graph represent soical network. The csv contains
+ n1 n2
+ n2 n3
- n1 n2 and so on.
I want to assing to n1 agent1 ,n2 agent2 and so on. Where + mean create edge - remove edge.
At end I want make graph partition.

**Comment by benoitgaudou** [comment]
Few remarks:
- first of all, as your message is not an issue but a question, I will close this issue.
Please post your question on the mailing list (https://groups.google.com/forum/#!forum/gama-platform)
- secondly, contrarily to your first email, it seems that your csv file contains your graph edge by edge: 1 line is an edge, linking 2 nodes (with perhaps + or - to specify if you create or delete it, I guess)

My advice to proceed:
- define a species for the nodes
- create a graph object
- read your csv file line by line.
- for each line, if this is an addition of egde, check whether the nodes exist.
You can code in the name attribute of the agent, the id of the node ("n1" or "1").
To check whether a node with the considered name exists, you can use "where" and "empty" operators.
So If you want to add an edge and that the nodes agent does not exist, you have to create them.

Final remark, if your file contains dynamic network, you will have to think about linking the dynamic of the graph and the simulation step, because if you load the whole dynamic graph at simulation initialization, you lose the interest to have stored all the dynamics.
