### ISSUE TITLE
schedules facet in global triggers an Exception

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#2952]
**Describe the bug**
I read in a previous (and quite old) issue that the `schedules:` facet is not taken into account anymore in the `global` species. (cf. #1708).
Nevertheless, it appears that when we try to add it, no warning appears but at execution, an Exception is triggered...

**To Reproduce**
Run the following model:
```
model managerscheduler

global schedules: [world] + B + A  {
	init {
		create A number:10;
		create B number: 10;
	}
}

species A { }

species B { }

experiment "Schedule" type:gui { }
```

We get the following exception:
```
1 occurence in Schedule0 at cycle 0: Java error: nil value detected
NullPointerException: null
msi.gaml.descriptions.TypeDescription.getOrderedAttributeNames(TypeDescription.java:316)
msi.gama.metamodel.population.GamaPopulation.<init>(GamaPopulation.java:167)
msi.gama.metamodel.population.GamaPopulation.createPopulation(GamaPopulation.java:99)
msi.gama.metamodel.agent.GamlAgent.initializeMicroPopulation(GamlAgent.java:224)
msi.gaml.descriptions.SpeciesDescription.lambda$4(SpeciesDescription.java:672)
msi.gaml.compilation.IGamaHelper.run(IGamaHelper.java:35)
msi.gaml.variables.Variable.initializeWith(Variable.java:486)
in agent Schedule0
```

**Expected behavior**
Either nothing or species are scheduled in the set order.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git
 - Java version: 1.8

**Comment by AlexisDrogoul** [comment]
I've fixed the issue. 

Two things here: 

1. The world is now alway scheduled first, so it should not be added (i.e. only `A + B`), otherwise a stack overflow will be triggered. I've changed the documentation to reflect that.
2. #1708 actually explains what has been implemented: using `schedules` in `global` is ok, it just creates an "invisible" species called `_internal_global_scheduler` and moves the facet to this species transparently.
