### ISSUE TITLE
Request new UI of user_input : user_list_input

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#2979]
with the user_input statement, for now, we can only display a message which contains/describe the list of choices, then user must enter the index of the choice.
![image](https://user-images.githubusercontent.com/6105384/80664737-c106f000-8ac1-11ea-9a55-c17433c07490.png)
I would like to have the same thing where it can display the choices as a list/combobox for user to not have enter a number but only click and chose the option.
It can be a new statement user_list_input
or reuse the existing with some customized param, for ex, adding @ before the list of question...
user_input("@1.option1 , 2.option2", ["Your choice"::1])["Your choice"])
Gama git.

**Comment by AlexisDrogoul** [comment]
The `user_input` implementation was a mess.... And the way to call it also. I've decided to deprecate the current use (it is of course still functional) and, instead, allow to use two operators (`enter` and `choose`) inside a list  instead of the crappy map; in that sense, something like : 

`map<string, unknown> params <- user_input(["Number of agents"::100, "Color"::#red, "2D"::true]);`

can be written: 

`map<string, unknown> params <- user_input([enter("Number of agents",100, 0, 100), choose("Color", rgb, #red, [#red, #green, #blue]), enter("2D"::true)]);`

`enter()` can take many arguments (a simple value, or a type and a value, or an int/float with min/max or step values...), and `choose` allows to choose a value among a list.

**Comment by AlexisDrogoul** [comment]
Using this new implementation, the function : 

```gaml
	string ask_dataset_path {
		int index <- -1;
		string question <- "Available datasets :\n ";
		list<string> dirs <- self.gather_dataset_names();
		loop i from: 0 to: length(dirs) - 1 {
			question <- question + (i+1) + "- " + dirs[i] + " \n ";
		}

		loop while: (index < 0) or (index > length(dirs) - 1) {
			index <- int(user_input(question, ["Your choice"::1])["Your choice"]) - 1;
		}
		return dataset_folder + dirs[index] + "/";
	}
```

can be rewritten: 

```gaml
	string ask_dataset_path {
		list<string> dirs <- self.gather_dataset_names();
		string choice <-  user_input("Choose among the datasets available :\n ", [choose("", string, dirs[0], dirs)])[""];
		return dataset_folder + choice + "/";
	}
```
