### ISSUE TITLE
Bar charts from a datalist built from a dynamic list of agents do not have appropriate legends

### ISSUE THREAD

**Issue by bitmixes** [gama-platform/gama#2980]
**Is your request related to a problem? Please describe.**
When I try and plot bar charts using datalist, the values come up to be fine but not the legends. It is interesting to note that the order of the values in the chart is appropriate. The only issue is that the corresponding legend name does not appear properly.

**Describe the solution you'd like**
Notice in the following two examples how inappropriately the legend appears. Ideally, I would like the unique agent name to be below the corresponding total_dist value. How do I achieve that?

**Describe alternatives you've considered**
`		display "distance_bar_chart" type:java2D 
               {
	    	chart "my_chart" type: histogram style:stack
	    	y_range:[0,2000]
	    	x_label:'Agent name'
	    	y_label:'total_dist'
	    	{
		    datalist
			legend: people collect each.name
			value: [people collect each.total_dist]
			color: #green;
	    	}	
		}
`
![image](https://user-images.githubusercontent.com/42370063/80786183-2217ec00-8bc6-11ea-8f2e-2f9f114ae76f.png)

`display "distance_bar_chart" type:java2D 
              {
	    	chart "my_chart" type: histogram style:stack
	    	y_range:[0,2000]
	    	x_label:'Agent name'
	    	y_label:'total_dist'
	    	{
		    datalist
			legend: [people collect each.name]
			value: [people collect each.total_dist]
			color: #green;
	    	}	
		}`
![image](https://user-images.githubusercontent.com/42370063/80786328-a4a0ab80-8bc6-11ea-90df-11d293b729c7.png)

**Additional context**

**Comment by AlexisDrogoul** [comment]
Looks like a problem of unordered maps being used internally m.. @benoitgaudou it reminds me of a similar problem (with colors?).

**Comment by sriramab** [comment]
Can you try:
```
display "distance_bar_chart" type:java2D { chart "my_chart" type: histogram style:stack y_range:[0,2000] x_label:'Agent name' y_label:'total_dist' { datalist legend: **list**(people collect each.name) value: [people collect each.total_dist] color: #green; } }
```

**Comment by bitmixes** [comment]
Unfotunately 
`legend: list(people collect each.name)` 
ends up showing nothing in the graph.

**Comment by AlexisDrogoul** [comment]
Maybe you have already tried this obvious syntax, maybe not ... 

```gaml
display "distance_bar_chart" type:java2D { 
    chart "my_chart" type: histogram style:stack y_range:[0,2000] x_label:'Agent name' y_label:'total_dist' { 
        datalist legend: people collect each.name value: people collect each.total_dist color: #green; } }
```
If not can you try it ?

**Comment by bitmixes** [comment]
> Maybe you have already tried this obvious syntax, maybe not ...
> 
> ```
> display "distance_bar_chart" type:java2D { 
>     chart "my_chart" type: histogram style:stack y_range:[0,2000] x_label:'Agent name' y_label:'total_dist' { 
>         datalist legend: people collect each.name value: people collect each.total_dist color: #green; } }
> ```
> 
> If not can you try it ?

That was the first thing that I tried, since it works fine with series graphs I am using. For the bar chart though, it shows an empty chart.

**Comment by AlexisDrogoul** [comment]
Strange. I've tried in one of the models using datalists (BDI Tutorial 2), and it works like a charm. Even with the odd `color: #green` facet. I've copied the last statement I sent you, adapted it a bit (instead of each.total_dist, I have each.gold_sold), but it displays exactly what is specified. 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/579256/80940528-42d08380-8e0a-11ea-863a-39a66b3dfb8b.png">

I'm a bit surprised, by the way, that you obtain a non-stacked histogram with your code. 
Would it be possible for you to share your code ?

**Comment by bitmixes** [comment]
Here you go.

[https://github.com/bitmixes/GAMA-public](url)

**Comment by sriramab** [comment]
If my memory serves me right, for a `stack` you need `accumulate_values:true`, so

`datalist [list of names] value: [list of values] accumulate_values:true color:[list of colors]`

**Comment by bitmixes** [comment]
> If my memory serves me right, for a `stack` you need `accumulate_values:true`, so
> 
> `datalist [list of names] value: [list of values] accumulate_values:true color:[list of colors]`

Even without `style: stack`, the issue remains. Sorry if I gave the initial impression that I wanted a stacked graph, but I actually do not.

**Comment by AlexisDrogoul** [comment]
Without the data, difficult to run your model. Maybe you have an "invisible" error somewhere. 

Can you check that this switch (the one highlighted) is on in the preferences. 

![image](https://user-images.githubusercontent.com/579256/80945630-6a2d4d80-8e16-11ea-8a2c-51705a6ee24b.png)

**Comment by bitmixes** [comment]
I did this and re-ran. No changes whatsoever. Can you access my code and data files here ? [https://github.com/bitmixes/GAMA](url)

**Comment by bitmixes** [comment]
Either 
the names appear correctly and bars do not appear at all, 
OR 
the names are the same for each bar and the bar values appear in order and correctly.

**Comment by pcaillou** [comment]
Hi,  I am curious too. accumulate_values:true can be useful if the data structure doesn’t allow GAMA to guess if it has to accumulate or not… But you are right Srirama, it does look like a bad guess from the data of what the chart should be… Philippe     De : Srirāma BhamidipātiEnvoyé le :lundi 4 mai 2020 09:36À : gama-platform/gamaCc : SubscribedObjet :Re: [gama-platform/gama] Bar charts from datalist do not have appropriate legends (#2980) If my memory serves me right, for a stack you need accumulate_values:true, sodatalist [list of names] value: [list of values] accumulate_values:true color:[list of colors]—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bitmixes** [comment]
Okay. So I have figured out that removing a reflex of species people solves the issue. This reflex included some agents to die if they did not match a criterion.

`	reflex die when: shortest_path_length >= 1500.0 {
		nbpeople <- nbpeople - 1;
		do die ;
	}`

![image](https://user-images.githubusercontent.com/42370063/80950792-e71dee80-8e39-11ea-9859-8917d10f93ea.png)

**Comment by pcaillou** [comment]
Hi, I didn’t manage to run your code but I may have found possible explanations :1 – The most probable : why do you use style :stack ? Can you try with style :bar (the default) The style can impact what Gama infers from your data 2 – The only way I manage to reproduce your bug (no bar but some legends) in some experiments is when I create and kill agents (like you) with sometimes duplicate names. The chart series are linked to the name and there can be inconcistencies between the series names and values. But I think you don’t change yourself the agent names ? (Gama creates unique names by default) If this doesn’t work :Can you put :                             write(list(people collect each.name));                            write(list(people collect each.total_dist)); in your code to display the values after the init and when you do the chart that does not work and send us the values?Thank you ! Philippe   De : bitmixesEnvoyé le :lundi 4 mai 2020 11:06À : gama-platform/gamaCc : pcaillou; CommentObjet :Re: [gama-platform/gama] Bar charts from datalist do not have appropriate legends (#2980) Okay. So I have figured out that removing a reflex of species people solves the issue. This reflex included some agents to die if they did not match a criterion.reflex die when: shortest_path_length >= 1500.0 { nbpeople <- nbpeople - 1; do die ; }—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pcaillou** [comment]
Sorry, I noticed my answers looked really ugly after going through github... Thanks to the Windows Mais program :)
I put my last comments:

I didn’t manage to run your code but I may have found possible explanations :
1 – The most probable : why do you use style :stack ? Can you try with style :bar (the default) 
The style can impact what Gama infers from your data

2 – The only way I manage to reproduce your bug (no bar but some legends) in some experiments is when I create and kill agents (like you) with sometimes duplicate names. The chart series are linked to the name and there can be inconcistencies between the series names and values. But I think you don’t change yourself the agent names ? (Gama creates unique names by default)

If this doesn’t work :
Can you put :

                            write(list(people collect each.name));
                            write(list(people collect each.total_dist));

in your code to display the values after the init and when you do the chart that does not work and send us the values?
Thank you !

Philippe

**Comment by bitmixes** [comment]
Sorry for the late reply. I was working on a different subject during the last two weeks.

I had tried with the style: bar and without mentioning any style explicitly. That trial failed.

As I had mentioned in one of the previous replies and as you have mentioned in your second alternative, the death of the agents is creating the issue. As and when I remove it, the output visualisation is appropriate.

This is the list obtained when the model is initialised with 30 agents.
`['people0','people1','people2','people3','people4','people5','people6','people7','people8','people9','people10','people11','people12','people13','people14','people15','people16','people17','people18','people19','people20','people21','people22','people23','people24','people25','people26','people27','people28','people29']
[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
`

And this is the list obtained when the model finishes running. 21 agents died during the first cycle for not satisfying the distance criteria and 9 survived and walked.
`['people0','people3','people7','people10','people13','people16','people17','people19','people26']
[747.7599384591624,1482.520836477067,1289.2562567288498,461.594532716921,414.1284196067507,289.275828476405,1121.803291254399,1394.12102569442,368.6798879200871]
`

**Comment by AlexisDrogoul** [comment]
The issue has been fixed. I tested it on two different models. Please reopen if you still have problems with dynamic lists of agents.
