### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by HuberSeppe** [gama-platform/gama#2994]
Hey there,

I would like to request an enhancement. A darkmode would be great. 

Thank you for your work, I really like working with GAMA.

Best

Patrick

**Comment by RoiArthurB** [comment]
Hello, the current version of GAMA (1.8 and the Continuous version) do not support Dark Themes.

The problem is that these versions of GAMA are build on top of Eclipse 2019 which didn't support it. But, we are working on a new version of GAMA (simply named GAMA 2) which is based on Eclipse 2020 which support Dark Themes. So you'll be able to use it at that time.

**Tweaking GAMA**

If you're running on Linux, and your eyes can't handle a full white screen, here's a little workaround : 
GAMA Linux use GTK 3 since the release 1.8, so you can override the default GTK theme used to use a dark one : https://gama-platform.github.io/wiki/Troubleshooting#workaround-if-you-use-a-gtk-dark-theme

Here's some look about it (it's not made for it, but it works 🤷)

![2020-05-29-095135_1920x1080_scrot](https://user-images.githubusercontent.com/16764085/83215812-020e2500-a192-11ea-9bf9-1a3d4d765fef.png)

![2020-05-29-095048_1920x1080_scrot](https://user-images.githubusercontent.com/16764085/83215785-f6baf980-a191-11ea-9d20-3bbd95036487.png)

**Comment by AlexisDrogoul** [comment]
This issue is no longer valid as a dark mode exists now. See however the existing problems in #3137
