### ISSUE TITLE
installing egit plugin no longer possible (on Windows) [suggested labels: bug, affects usability]

### ISSUE THREAD

**Issue by JimmyWikipage** [gama-platform/gama#3041]
**Describe the bug**
It is no longer possible to install the egit plugin with a fresh / new installation of the latest GAMA version (with JDK). The installation fails because a set of requirements are missing, that the plugin apparently expects to find in Eclipse, but which apparently are not included in GAMA (see below for error message). 

**To Reproduce**
1. Install a fresh version of GAMA with JDK (the latest, 1.8.1)
2. Go to the plugin installer
3. Enter the egit update page: http://download.eclipse.org/egit/updates
4. select the plugin to be installed (anything including the checkbox for the "Git integration for Eclipse" will do)
5. The installation fails, with the error reading: 
  "Cannot complete the install because one or more required items could not be found.
  Software being installed: Git integration for Eclipse - Source Code 5.9.0.202009080501-r (org.eclipse.egit.source.feature.group 5.9.0.202009080501-r)
  Missing requirement: Git integration for Eclipse 5.9.0.202009080501-r (org.eclipse.egit.feature.group 5.9.0.202009080501-r) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jsch.ui [1.3.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Git integration for Eclipse - Source Code 5.9.0.202009080501-r (org.eclipse.egit.source.feature.group 5.9.0.202009080501-r)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.feature.group [5.9.0,5.10.0)"

**Expected behavior**
The expected behavior would have been to install the plugin.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PC Model: attempted this on 4 different Windows 10 machines, one intel-based and one amd-based desktop, one Microsoft Surface Pro 7, and one Razer Blade Laptop
 - GAMA version: 1.8.1 with JDK

**Comment by sriramab** [comment]
Sir, If you are not too particular about the version, I believe 4.1 still works (Eclipse GitHub integration with task focused interface 4.1.0.201509280440-r)

**Comment by AlexisDrogoul** [comment]
Hi, I have been able to successfully install EGit on the 1.8.2 version, first by hand when running from Eclipse and then in the release version. So the good news is that it is not incompatible with GAMA 1.8.2 (you can import models, etc.). I am sorry about the incompatibility of the latest version with GAMA 1.8.1, but Srirama is right. Better stick with version 4.1 (which you can obtain from the update site listed here: https://wiki.eclipse.org/EGit/FAQ#Where_can_I_find_older_releases_of_EGit.3F), because we are unfortunately not going to fix this...
