### ISSUE TITLE
Problem with old syntax with message

### ISSUE THREAD

**Issue by quanzh97** [gama-platform/gama#3048]
When I try to use the content from the message, there is an error.

		message priceget <- cfps[0];
		int price_get <- priceget.contents[1];

No operator found for applying 'internal_at' to types [unknown,
   list] (operators available for [types [container, list], types
   [geometry, list], types [agent, list]])

**Comment by AlexisDrogoul** [comment]
You get this error because the type of the `contents` of the message is unknown. You can actually put anything in this contents, so what you get ultimately depends on what you store ! If it is a `list` that you have stored, in which the second position is an int, then you have to cast it explicitly, for instance:  `int price_get <- list(priceget.contents)[1]; `
