### ISSUE TITLE
Consistency of printed list of agent and the gaml syntax

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3053]
For example, we have a species named "home". When using GAML syntax, we can access agents by indexing '[ ]', i.e:
		list<home> home_target <- [home[79],home[38],home[39],home[4],home[40]];

but when write this list to console, the parentheses are used:

[home(79),home(38),home(39),home(4),home(40)]
Is it possible to print out to console with the same syntax (using [ ] for indexing, instead of ( ) )

Gama git.

**Comment by hqnghi88** [comment]
fixed

**Comment by AlexisDrogoul** [comment]
I will revert this one, sorry ! Actually, `home(79)` and `home[79]` have different meanings and the former is correct for serialisation:
- `home(79)` means the `home` agent with index 79 (indices are unique, and this is a casting operation)
- `home[79]` means the `home` agent situated at the 79th position in the population

When no agents die, the two are equivalent (i.e. the agent of index `i` is at position `i`). However, as soon as agents are suppressed, they become desynchronised. 

So, in a model, when you write `home_target <- [home[79],home[38],home[39],home[4],home[40]]`, it is probably not exactly what you intended to write (i.e. you do not want the 79th agent in the list, but the agent with index 79), and it would be more correct to write `home_target <- [home(79),home(38),home(39),home(4),home(40)]`... 

When an agent is asked to serialise itself, it is then correct to output its species and its unique index in the species using `my_species(my_index)`, which will always designates this agent, rather than `my_species[my_index]`, which may designate another agent after some time (if agents dies in this population).

**Comment by hqnghi88** [comment]
Well, it's ok for me to change the line in model to ( ), to be consistency with what written in the console, it means the issue is still fixed.  Thanks for the explanation. But i still dont know if there is someone like me , who used the [ ] for accessing elements in containers??

**Comment by AlexisDrogoul** [comment]
Of course, a lot of people do it, and populations (and species) have to remain coherent with this. When you write `home[79]`, it will correctly try to get the 79th agent in the population (exactly like the 79th element in a list), and return an error if there is less agents. 
The rollback I will introduce is that when the agent of species `home` with index `79` will serialise itself, it will use `home(79)` (return the agent with index 79) and not `home[79]` (returns the agent at position 79).
