### ISSUE TITLE
GNU Gama

### ISSUE THREAD

**Issue by cepek** [gama-platform/gama#3067]
Dear All, are you aware that you are using the name of our project Gama
(https://www.gnu.org/software/gama/  started in 1998) for your project
https://gama-platform.github.io/ ?  As you started your project last
year, it is not our concern but yours to solve this confusing situation.

Aleš Čepek

P.S. your given contact address  gama-dev@googlegroups.com given at https://gama-platform.github.io/wiki/Overview#citing-gama is fake. My email address is cepek@gnu.org

**Comment by AlexisDrogoul** [comment]
Hi,

Nice to discover your package dedicated to the adjustment of geodetic networks ! 

The GAMA modeling and simulation environment exists since 2006 (first paper published  in 2007 in case you're interested : Amouroux, E., Chu, T. Q., Boucher, A., & Drogoul, A. (2007, November). GAMA: an environment for implementing and running spatially explicit multi-agent simulations. In Pacific Rim International Conference on Multi-Agents (pp. 359-371). Springer, Berlin, Heidelberg.).

The full name of the project (and associated site) is "Gama Platform". So, besides the fact that these two softwares have absolutely nothing in common, the names are different too and I don't see any confusing situation here. 

Cheers
Alexis
