### ISSUE TITLE
Operator/statement to extract/query data from big asc/geotiff file

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama#3087]
In the current version (1.8.2), when we use an asc file or a geotiff (raster data) in a gama model, we must declare the file variable:
file data<-file("xxxx.geotiff");
and we may have to use the grid to initialize/create agent. This process works well with small raster data, i.e maximum 1000x1000 grid, even without any complex computation.
BUT in some case, the real raster data usually are bigger than that. let say minimum 3000x3000 in a asc file. And we known that the geotiff can contain multi-band data (a list of grid_value for each cell).  So the importation into GAMA is very hard to be done, most of the time the initialization can not finish even we have enough memory.
I think the cause is from the GamaGridReader, as we implement a hard-code of for loop
for (int i = 0, n = numRows * numCols; i < n; i++) {
...
}
This loop is already long with a minimum raster data like 3000x3000x12
So i wonder if we can :
- postpone this loop when we declare the file variable.
- have an operator/statement to read separately the data , for ex, the_file get_grid_value_at (x,y) 
- reimplement the loop to be able accelerate by some parallel mechanism.

I can make a experimental plugin to do it but i think the power of gama is the capability to deal with multi type of data and this workflow is much faster, easier in qgis so i think we can enhance gama in some ways.

**Comment by AlexisDrogoul** [comment]
This issue is linked with the discussion on the group (https://groups.google.com/g/gama-platform/c/iUq_gnrNO8A), and the idea of trying not to do too many computations on complex datasets unless they are explicitly asked by the user (and, in that case, to reduce the usage of memory as much as possible).

**Comment by AlexisDrogoul** [comment]
Hi,

Regarding this issue, a first solution might be provided by the new `field` type, which proposes a light mechanism to land grid/raster files. After that, a field can be accessed like a regular `matrix<float>`, with the possibility to read and access `bands` too. 

A second issue is the speed required to load such files. It might be the case that we can speed it up by paralleling the operations. It can be a good idea (but it requires having access to the inner loading mechanism, which is not always possible -- I dont know if GeoTools permits it).

The third issue is the possibility to use these big files as "databases" , i.e. without loading them immediately. Again, it might be interesting to see if the new `field` type could not be used for that. Instead of immediately copying the data in memory, we could perfectly only keep a link to the field provider and load portions of it on demand. 

Let's tackle these different issues one at a time, ok ? And first, can you tell me if `field` partially solves your main problem.

**Comment by hqnghi88** [comment]
Dear Alexis,
I tested the library models, it is great, indeed! Congrats. I am currently (try to) use fields for a cell risk model of whole city (HCM) . i  will post new issue if any (actually i still hope for a database-like that load a bunch of needed data only, but we will discuss in other post). I close this issue for now.
