### ISSUE TITLE
documentation request

### ISSUE THREAD

**Issue by axb21** [gama-platform/gama#3097]
Hi, 

I am new to GAMA and evaluating it for use in an ongoing project of mine. I've run into a few bumps in the road and am unsure where to look for answers. The documentation I've found, while very good, is not at a level of detail I'd find helpful, and I am too new to the project to even begin to guess where to look in the source code. I apologize if this is a repeat of a previous issue, but I was unable to find an existing answer.

Mainly, I would like to see low-level document for some of the built-in types such as `agent`. I do not know where to go to find out how to determine which attributes an agent has, or determine if it has some specific attribute. Perhaps neither of those is possible or good practice, but I don't know where to go to find that out, either. `agent` feels like a black box to me and it makes me nervous; I'd like to have a full picture of what it can and cannot do, analogous to API documentation for a software library. Does that exist anywhere and I missed it?

I would also like to see lower-level documentation around file input. For instance, GAMA performs some behind-the-scenes magic to parse CSV files, OSM files, etc. Where can I find details on what that magic is? How much control, if any, do I have over the parsing? Is there more detailed documentation on these?

Some concrete questions:
* According to the documentation, CSV files are parsed by column and then a `loop` goes over the file record-by-record. What function do I use to determine how many records there are per row?
* What does GAMA do if two rows have a different number of records? Does it give an error? Does it merrily parse away? Something else?
* I have OSM data with keys like `"power:source"`, but when I naively `get` or `read` with a key name like `"power:source"`, GAMA returns `nil`.  Is that a bug? Expected behavior? Am I not able to grab data from keys like that? Is there some lower-level way to parse OSM files so that I can get data like that?

Anyway, you get the idea I hope. Really I'd like either pointers to more thorough documentation of such topics, if it exists, or pointers into source code where I can look for myself. 

Thank you! I am enjoying GAMA quite a lot, and it has so many powerful features I'd love to make use of it and with any luck give back anything interesting I make with it. I'm going to need a little help to get started, though!

**Comment by benoitgaudou** [comment]
I updated the documentation  by:
- providing details about agent types :  https://gama-platform.org/wiki/next/DataTypes
- providing more  details about  csv file and  the  way to import date  files in https://gama-platform.org/wiki/next/FileTypes

```According to the documentation, CSV files are parsed by column and then a loop goes over the file record-by-record. What function do I use to determine how many records there are per row?```
CSV files are parsed by rows. Here what I added in the documentation:

"To manipulate easily the data, we can consider the `contents` of the data file, that is a matrix.
As  an example, we can access the number of lines and columns of a data file named `my_file` with `my_file.contents.dimension`."

"What does GAMA do if two rows have a different number of records? Does it give an error? Does it merrily parse away? Something else?"
In this case the file will be parsed, the dimension of  the result is the number of rows and the number of elements of the longest row.

"I have OSM data with keys like "power:source", but when I naively get or read with a key name like "power:source", GAMA returns nil. Is that a bug? Expected behavior? Am I not able to grab data from keys like that? Is there some lower-level way to parse OSM files so that I can get data like that?"
At  the end of the day, OSM file is nothing more an XML file that could be parsed as it.... which will not be really  convenient.
