### ISSUE TITLE
Propose a syntax to extract sublists/subcontainers from containers

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama#3099]
**Is your request related to a problem? Please describe.**
There's no convenient way to get a sublist made of the _n_ th first elements of a bigger list. In the same logic, it's also complicated to get a sublist of the _n_ th elements in the middle of that list.

**Describe the solution you'd like**
All languages have a pretty or convenient way to do so (like in python : `array[0:n]` or `array[n:m]`)

**Additional context**
There's some way to do it in GAML (like `accumulate(range(0, n), ourlist[each])`), but it's not convenient to use and looks really hacky to use.

**Comment by minhduc0711** [comment]
There is already an operator for this: [`copy_between`](https://gama-platform.github.io/wiki/OperatorsBC#copy_between)
But we can still add support for slicing using square brackets like so because it does look prettier IMO.

**Comment by AlexisDrogoul** [comment]
l -: [1,2,3,4,5]
first(2,l) -: [1,2]
last(2,l) -: [4,5]
copy_between(l,1,3) -: [2,3]

Isn't enough ? And what would be the point of adding a bracket-based syntax (beside confusing how to pass parameters to operators) ?

**Comment by minhduc0711** [comment]
@AlexisDrogoul I suppose this is just syntactic sugar in the case of lists. 
However this might be a cleaner way to perform matrix indexing in GAML (for now I have no idea how to index a matrix tho, e.g. slicing a smaller submatrix).

**Comment by AlexisDrogoul** [comment]
@minhduc0711 I dont agree with it being "just" syntactic sugar. It is the way of passing arguments which needs to be coherent between operators. Why would operators on containers allow a bracket style passing of arguments and not other objects ? 
Secondly, the issue was about lists, right ? Because matrices are a different matter. `copy_between` is not implemented for them but it wouldn't be two complicated to do. I can take a look at this if needed (something like `copy_between(m, {c1,r1},{c2,r2})` for instance).
Finally, I've made a small commit for lazy people, so that they can indifferently use `between` or `copy_between`  😉

**Comment by minhduc0711** [comment]
Sorry, I meant that `array[n:m]` is syntatic sugar, because Python and R users like it a lot.

About coherent argument passing, square brackets are used for the `at` operator. I think both `at` and `copy_between` can be considered as list indexing, therefore I find it logical for them to share the same syntax.

**Comment by AlexisDrogoul** [comment]
Would a syntax using pairs (`[begin::end]`) rather than the awkward `[begin:end]` (no meaning in GAML, risk of confusion with facets and necessity to change the grammar) satisfy your delicate needs 😉 ?

With, for the moment, two different meanings:
```gaml
		list array <- [1,2,3,4,5];
		write sample(array[1::3]); // internal_between(array,1 :: 3) -: [2,3]  -- creates a copy of the sublist
		array[1::3] <- 100; // only assignments are allowed for ranges
		write sample(array); // array -: [1,100,100,4,5]
```

**Comment by minhduc0711** [comment]
Yes, that seems more reasonable for GAML.

**Comment by minhduc0711** [comment]
Sorry I did not notice the new commit for this. I just tried the syntax and it was working as expected.
