### ISSUE TITLE
Documentation for generate_pedestrian_network

### ISSUE THREAD

**Issue by Shinrod** [gama-platform/gama#3107]
Hello,

After the reply of https://github.com/gama-platform/gama/issues/3105, I've been working on the pedestrian example for the past few days (using Gama 1.8.2).

I'm trying to use `generate_pedestrian_network` but I'm lacking the documentation to use it properly. I saw the comments on the example, but would it be possible to have a more complete description of what each parameter does ?

(Note : I'm especially interested on how to use it on bigger spaces than the example. Not more complicated, just bigger : an area of about 10000x10000 with around 100 obstacles.)

Thanks

**Comment by ptaillandier** [comment]
Hi,

You are absolutely right, this operator lacks documentation (my fault). I
can try to improve it even if it will be complex because the role of some
parameters is quite dark. Could you add an issue to this (label:
documentation)?
I have to say that when I use it, it usually takes quite a few tries before
I get a pedestrian path graph that I like (because it depends a lot on the
input data and it's often difficult to predict the result).

Cheers,

Patrick
