### ISSUE TITLE
The `die` action of the `global` species does not stop the clock

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3145]
**To Reproduce**
```
model NewModel

global {
	reflex stop when: cycle = 100 {
		do die;
	}
}

experiment exp {}
```

**Expected behavior**
~~The simulation should stop at cycle 100.~~
The clock should be stopped along with the simulation.

**Comment by AlexisDrogoul** [comment]
What do you mean by "the clock should be stopped" ? Which clock ? That of the simulation or that of the experiment ? In the first case, it is normally stopped (and if not there is a bug, but I wonder how your model determines it ?); in the second case, it is normal that the clock of the experiment does not stop when a simulation dies. Otherwise we could not have several simulations in one experiment. 

For normal experiments (i.e. `gui` ones) the two clocks are synchronised: during one step of the experiment, all its simulations perform one step. For `batch` ones, one step corresponds to the execution of a whole set of simulations. For both, anyway, even when no simulation is created, their clock will continue to tick...

**Comment by minhduc0711** [comment]
Sorry for being vague, I was referring to this thing
![image](https://user-images.githubusercontent.com/34294427/126611902-5a6c1e8b-9931-4e03-a59c-18847771a4ec.png)

**Comment by AlexisDrogoul** [comment]
Yes. it is written "Experiment" :)

So if you tell a simulation to die, it will (logically) not kill the experiment, which will keep on ticking. Just move your reflex in the experiment instead, and your experiment will die... 

If you click on the button above, you will see that you have access to the experiment and the simulation(s) it contains. If you kill the simulation, only the experiment will be available. 

![Parameters and C… 2021-07-22 15-46-25](https://user-images.githubusercontent.com/579256/126612517-af5a07c1-a6a2-438f-8897-16b1bfd2775d.png)

**Comment by minhduc0711** [comment]
Thanks for clearing this up!
