### ISSUE TITLE
Mesh transparency only take effect after one step

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama#3174]
**Describe the bug**
Define a mesh for instance
````
mesh heatmap position: {0, 0, -0.01} scale: 0.0 color: palette([ #white, #cyan, #yellow, #yellow, #red, #red, #red]) transparency: 0.75  smooth: 4 triangulation:true;
species building aspect: base refresh:false transparency:0.5 position: {0, 0, -0.015};
			
````

**Expected behavior**
I would assume to see directly the building below but you need to run at least one step to see the building.

I guess something is missing in the init

**Screenshots**
![yo mov](https://user-images.githubusercontent.com/3928502/131650612-be78c2cd-b3f9-43fd-be07-fdf7add501f8.gif)

**Desktop (please complete the following information):**
GAMA_1.8.2_Alpha_withJDK_Mac_08.26.21_0c64cc94

**Additional context**

**Comment by AlexisDrogoul** [comment]
I do not really understand what is happening here. Do you have a simplified model to try ? 
And have you tried to have the same logic in terms of z-position and order of layers ? Because you are playing here with different notions, and in that case (like in the other issue) the two logics are reversed: you first draw the mesh and then the buildings, but you consider that the mesh is above the buildings. For instance, if the mesh is displayed first (in terms of layer) with transparency, then this transparency should not apply to the buildings (which are displayed after) even though you draw your mesh above: transparency should not reveal something which is not yet drawn, right ?

**Comment by agrignard** [comment]
After indeed cleaning my Z position. I cannot reproduce it. let's close it for now
