### ISSUE TITLE
skeletonize's result is different when changing the world shape

### ISSUE THREAD

**Issue by litingzhen** [gama-platform/gama#3247]
**Describe the bug**
1.8.1， with the same geometry, use skeletonize to this  geometry，but the result is different when changing the world shape.

**To Reproduce**
```
         shape_file myshp<- shape_file("xxxx");	
	 geometry shape<-envelope(myshp)+500;
         create geoshape from:myshp;
	 list<geometry> skeletons <- list(skeletonize(last(geoshape )));
	 write length(skeletons);
```

**Expected behavior**
when I change the shape (500-->1000 )，the skeletonize  result should be same.

**Desktop (please complete the following information):**
 - OS: win10
 - PC Model: 
 - GAMA version: 1.8.1
 - Java version: 1.8
 - Graphics cards / Display system:

**Comment by litingzhen** [comment]
the shape_file is [freespace.zip](https://github.com/gama-platform/gama/files/7533814/freespace.zip)

**Comment by ptaillandier** [comment]
Hi,

I can't test the script because some files with the shapefile are missing
(.shx, .dbf and .prj files)

Cheers,

Patrick

Le dim. 14 nov. 2021 à 20:31, litingzhen ***@***.***> a
écrit :

**Comment by litingzhen** [comment]
Sorry, all in this zip.
[freespace_allinone.zip](https://github.com/gama-platform/gama/files/7536568/freespace_allinone.zip)
e

**Comment by ptaillandier** [comment]
Hi,

I tested with GAMA 1.8.2 and we have the same issue... but I am not sure
that it is possible to fix this issue as the skeletonization depends on the
triangulation: the differences are due to rounding problems in the floats
(slight difference in the coordinates). There is not much we can do about
it.

Note that if we define a not null value for the tolerances of triangulation
and of clipping, the results are similar in all cases: skeletons <-
(skeletonize(last(geoshape ),0.1,0.1));

Cheers,

Patrick

Le lun. 15 nov. 2021 à 14:15, litingzhen ***@***.***> a
écrit :

**Comment by AlexisDrogoul** [comment]
I think that there is nothing we can do automatically here. The arguments to `skeletonize` are largely enough to cover this error. I'm closing the issue then, but feel free to open a new one in https://github.com/gama-platform/gama2/issues
