### ISSUE TITLE
Experiment  built-in list `simulations` is empty when `pref_parallel_simulations_all` is true

### ISSUE THREAD

**Issue by chapuisk** [gama-platform/gama#3263]
**Describe the bug**
When `pref_parallel_simulations_all` is set to true for batch mode (i.e. allocated cores are always fully used), the simulations are not kept in memory whatever the value of facet `keep_simulations`.

**To Reproduce**
1. Change Gama preferences to have `pref_parallel_simulations_all` to true (preferences > execution > parallelism > in batch mode, allow to run ...)
2. Add a reflex to any batch experiment
3. See empty `simulations` attributes

**Expected behavior**
Simulations should be kept in memory, as it is the case when the parameter sets (actually a point in the parameter set) are launched one after another. However, It may required to change how Experiment in Gama triggers the reflexes.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - GAMA version: 1.8.2 and git 1.8.2

**Comment by AlexisDrogoul** [comment]
I dont really understand the sentence `However, It may required to change how Experiment in Gama triggers the reflexes.` . Can you elaborate, what does it have to do with the simulations ?

**Comment by AlexisDrogoul** [comment]
In any case, I've issued a possible fix for this. Please test and tell me if it solves your problem !

**Comment by chapuisk** [comment]
@AlexisDrogoul It seems that simulations variable is no more empty. However, there is another issue: at least for the library model of batch exploration, permanent block is no more reached (or do not update display). It might be related to the unclear sentence, I wrote first about how reflexes are triggered in batch mode: permanent block seems to be updated, every end of n repeated simulation, as it is the case with reflexes. Allowing multiple ParameterSet (n repeated simulation) to be run simultaneously might break this rule. It might then require to revised when permanent block (or reflexes) are triggered in experiment

**Comment by benoitgaudou** [comment]
@chapuisk 
I just tested the `Batch.gaml` from the model library, with the `pref_parallel_simulations_all ` preference set to true.

Launching the `Exhaustive` experiment has 2  effects:
* A reflex in the experiment  is only executed when all the 27 simulations are finished.
* Ass  a consequence the display in the `permanent` block is updated only 1 time (when  all the simulations are  finished).
* the  variable  `simulations` contains all the 27 simulation.

I guess this is a quite expected behavior. 
Do you agree ?  (you can close  the  issue if  agree :-) )
