### ISSUE TITLE
Weird behaviors with import (problem with order of import?)

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama#3268]
**Describe the bug**
According to the "manipulation" of the editor, the same model can have different behavior regarding import (different order of import?)

[test_import.zip](https://github.com/gama-platform/gama/files/7766191/test_import.zip)

**To Reproduce**
1. Import the attached model, and open model2.gaml
2. comment the import of model1
3. run the xp model2
4. The result should be 2
5. Uncomment the import, and run xp model2, the result is still 2
6. Comment the import of main model and run model2, the result is 3
7. Uncomment the import and run xp model2, the result is still 3

In 5 and 7, with the same model, we have two different results.

Tested with GAMA 1.8.2 git version

**Comment by AlexisDrogoul** [comment]
This is an effect of the terrible legacy of the `global` section inheritance rules (or lack of clear rules and semantics). Since `model2` imports both `main model` and `model1, it seems to have a hard time deciding which version of `main_function` to run. I am not completely clear, however, on to why this particular configuration is undecidable. Several tracks may then be followed :

- One first thing could be to warn the user about the double import (and actually remove it silently when compiling `model2`, as imports are transitive in GAML).
- Another is to go a bit deeper and verify that the dependency graph is not malfunctioning in those configurations
