### ISSUE TITLE
end_conversation in FIPA does not remove conversation

### ISSUE THREAD

**Issue by Aya-Badawy89** [gama-platform/gama#3271]
**Describe the bug**
The ended conversation is not removed from the list of conversations

**To Reproduce**
Test this dummy model
```
model codetest

global {
	init {
		create girl;
		create boy;
	}
}
species girl skills:[fipa] {
	reflex when: time=1 {
		do start_conversation to:[boy[0]] performative:'inform' protocol: 'no-protocol' contents:['hello'];
	}
}

species boy skills:[fipa] {
	
	reflex when: !empty(informs){
		do end_conversation message:informs[0] contents: ['hello'];
		write conversations;
	}
}
```
**Expected behavior**
The console should print an empty list. It prints the conversation as it is. I tried emptying the list manually or using the remove operator but it does not work

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GAMA version: version 1.8.2 with JDK

**Comment by AlexisDrogoul** [comment]
Hi, nothing in the FIPA protocol indicates that an ended conversation should be immediately discarded. So they are disposed of and removed from the lists not immediately but at the end of the current simulation cycle. Is it what you observe ?

**Comment by Aya-Badawy89** [comment]
Hello, Alexis. Thank you for your reply and happy new year.
I find in the documentation on Gama website:
"conversations (list): A list containing the current conversations of agent. **Ended conversations are automatically removed from this list."**
That's why I thought it should be empty.
I even tried now to let it print the list of conversations during the whole simulation, but it always has a conversation. It is never removed.

**Comment by AlexisDrogoul** [comment]
If you look at the example model called `FIPA No Protocol`, you'll see a functional example of `end_conversation`. My guess is that, in your example above, girls do not read messages from the boys, so the message corresponding to the end of the conversation is actually never read. 
If you add a reflex that browses through the messages in the mailbox, in the `girl` species, then you will see that the conversation is removed. 

I do not know, honestly, if it is an issue or not. Up to you to decide, so that we treat, for instance, `end_conversation` messages in a special way.

**Comment by AlexisDrogoul** [comment]
Sorry to come back late to this issue. The reason is that I do not know exactly what is expected now. Would you please so kind so as to summarise what could be needed in terms of new developments ?

**Comment by Aya-Badawy89** [comment]
I was suggesting to let the action (end conversation) remove the conversation from the list of conversations.
This will be in-line with the documentation which defines: 
"conversations (list): A list containing the current conversations of agent. Ended conversations are automatically removed from this list."

**Comment by AlexisDrogoul** [comment]
I understand and it is actually already the case, but in your special case, `end_conversation` could not do it because it was not read at all. What I was saying is that the FIPA protocol works but only if the agents read the messages. If they do not, I do not see concretely how to do -- unless we break a bit the protocol and consider `end_conversation` to be interpreted directly by the conversation ?

**Comment by Aya-Badawy89** [comment]
Mmm. I feel (end conversation) is not a type of message, not the same as (propose, inform, accept proposal...etc.). It looks more as an action. To the best of knowledge, I did not even find it as a locution in the official FIPA language. So, may be we can treat it differently. 
At the same time, I don't want to complicate things or confuse a code that is already functioning well. It is not a major issue and I know you're all about to release version 1.8.2 :) So, it's up to you we can for now just clarify in the documentation that (end conversation) should be read for the conversation to be removed to avoid misinterpretation, and leave the protocol as it is.

**Comment by AlexisDrogoul** [comment]
Ok perfect ! Thanks a lot for your understanding -- and yes we are hard at work, with @lesquoyb taking the lead on the upcoming release... I have committed a "fix" in the documentation of `end_conversation`, I close this issue now.
