### ISSUE TITLE
Batch experiments - value

### ISSUE THREAD

**Issue by umonze** [gama-platform/gama#3292]
Dear everyone,
herewith i would like to report a possible bug in the software GAMA 1.8.1. I'm currently attending a course at the University of Salzburg/Austria (UNIGIS professional). In one of our exercise we had to run a Monte Carlo simulation as a batch experiment. During a Q/A exchange with my professor we identified a possible bug in GAMA 1.8.1, which we thought worthwhile reporting. 

Describe the bug
I have a GAMA-model to simulate a MonteCarlo simulation.

```
model BatchExperiment

global  {
    int my_var <- 0;
    reflex add_1 {
        if flip (0.5) {
            my_var <- my_var + 1;
        }
    }
}

experiment MonteCarlo type: batch repeat: 10 until: cycle = 50 keep_seed: false {
    
    reflex    save_results {
        ask simulations  {
             save [self.name, my_var] to: "../results/bug.csv" type: "csv" rewrite:false;
        }
    }
} 
```
In GAMA's documentation on batch experiments (https://gama-platform.org/wiki/BatchExperiments) it explains the batch experiment facets. For the "repeat" facet it says: "Different random seeds are given to the pseudo-random number generator. This allows to get some statistical power from the experiments conducted. The default value is 1."

For the model above we would expect to get 10 different values that are statistically distributed around 25 (50% of 50).

However, the result is 10 times a value close to 25 for example ten times 28 or ten times 20 and so on.

Example:

```
self.name,my_var
Simulation 0,28
Simulation 1,28
Simulation 2,28
Simulation 3,28
Simulation 4,28
Simulation 5,28
Simulation 6,28
Simulation 7,28
Simulation 8,28
Simulation 9,28
Simulation 0,20
Simulation 1,20
Simulation 2,20
Simulation 3,20
Simulation 4,20
Simulation 5,20
Simulation 6,20
Simulation 7,20
Simulation 8,20
Simulation 9,20
```

We used GAMA version 1.8.1

Could this be a bug in GAMA or rather a mistake in the script? 

Let me know if you have any question or need anything else to reproduce the output. 

Many thanks in advance for your support. 

Best,

Ursula

**Comment by RoiArthurB** [comment]
Hello,

You had a really common mistake in batch experiments :upside_down_face: 
What you are writing is the value of `my_var` at the end of your batch exploration (i.e. the last simulation), what you want to look at is the one from your simulation which is `self.my_var` :smile: 

Here's your model modified : 

```
model BatchExperiment

global  {
    int my_var <- 0;
    reflex add_1 {
        if flip (0.5) {
            my_var <- my_var + 1;
        }
    }
}

experiment MonteCarlo type: batch repeat: 10 until: cycle = 50 keep_seed: false {
    
    reflex    save_results {
        ask simulations  {
             write("[Self] " + self.name + " my_var: " + self.my_var + " seed: " + self.seed);
             write("[Batch] my_var: " + my_var + " seed: " + seed);
             write("---");
        }
    }
} 
```

Here's the log from it (the first line is what you want, from each simulation with the keyword `self.`, and the second what you had) : 

```
[Self] Simulation 0 my_var: 23 seed: 0.16974990814201496
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 1 my_var: 23 seed: 0.9870946141288474
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 2 my_var: 25 seed: 0.21450453759371024
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 3 my_var: 26 seed: 0.6153736183441727
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 4 my_var: 24 seed: 0.3458486225313546
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 5 my_var: 30 seed: 0.3602111783974048
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 6 my_var: 27 seed: 0.9172682322406752
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 7 my_var: 27 seed: 0.46448596693642064
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 8 my_var: 19 seed: 0.6252242568544238
[Batch] my_var: 25 seed: 0.8558160617631659
---
[Self] Simulation 9 my_var: 25 seed: 0.8558160617631659
[Batch] my_var: 25 seed: 0.8558160617631659
```

**Comment by AlexisDrogoul** [comment]
I would like to add a comment to this: this is a common mistake, but only because the contexts in experiments can be a bit confusing; in the `ask simulations` statement, you are supposed to be in a "remote sequence", which mixes the context of each simulation, in turn, with the "outer context" (in your case that of the experiment). When ambiguities arise (for instance two variables having the same name in the local and outer contexts), priority is given to the "outer context" unless you use `self`(local context) or `myself` (outer context) to clarify which variable to use. The tricky part, here, is that this rule somehow conflicts with a facility in experiments, which lets you directly use the variable names of simulations in the experiment, effectively using the value of the last simulation created in this experiment (for instance, in your experiment, `my_var` and `simulation.my_var` would return the same value, as if `my_var` was defined in the experiment itself). 
The consequences of these two rules/facilities is that when you use `my_var` (w/o prefixing it with `self`) in your remote `ask` sequence, GAMA looks in the outer context first (the experiment), and finds it in here thanks to the facility, happily returning the value of the last simulation. If you use `self`, on the contrary, it will restrict its lookup to the local context, i.e. the current simulation to run the sequence.

**Comment by umonze** [comment]
Thanks for the valuable support :-)
