### ISSUE TITLE
The facet `index` of the `remove` statement does not work properly

### ISSUE THREAD

**Issue by minhduc0711** [gama-platform/gama#3294]
**Describe the bug**
The facet `index` of `remove` is behaving similarly to `item`, which I believe is not intended after looking at the [example snippets in the documentation](https://gama-platform.org/wiki/Statements#usages-65).

**To Reproduce**
```
list<int> ints <- [1, 2, 100];

remove index: 0 from: ints;
// => [1, 2, 100]

remove index: 100 from: ints;
// => [1, 2]
```

**Expected behavior**
Elements with associated with the indices should be removed instead.

**Desktop (please complete the following information):**
 - GAMA version: git
 - Java version: openjdk 17

**Comment by AlexisDrogoul** [comment]
Bug appeared because of the application of formatting/cleansing rules to Java code.... On `List`s (including `GamaList`) `remove(int)` and `remove(Integer)` are different methods ! The former removes the index, the latter the element. When applying the Save Action called "use unboxing", the `.intValue()` after the Integer value was systematically removed, producing this undesirable side effect. I have committed a fix. 

<img width="237" alt="Additional Save Actions 2022-01-27 14-44-49(1)" src="https://user-images.githubusercontent.com/579256/151314260-26a449fc-28ec-4807-885f-1c9c4ef14475.png">

**Comment by AlexisDrogoul** [comment]
Bug has been fixed as far as I can test and tell. Closing the issue.
