### ISSUE TITLE
Adding warnings when explicitly assigning 0 to the random generator seed

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3300]
**Is your request related to a problem? Please describe.**
Assigning 0 to the random generator seed means getting a random seed. It can be counter intuitive for a lot of people that might think that they are getting the same seed every time.

**Describe the improvement you'd like**
Showing a warning when explicitly assigning 0 could help to clarify if it was a deliberate choice or not.

**Describe alternatives you've considered**
Using another "special value" like -1 could be a little more intuitive. A warning seems to still be a good idea.

**Comment by AlexisDrogoul** [comment]
Thanks. I am not sure that a warning would really help, actually. Because there are many configurations where seed is assigned zero without the compiler being able to know. Like for instance: 

```
string a <- '0';
float seed <- float(a);
```

or any other combinations of constant/non-constant assignments. 
Instead, I have committed a small addition to the documentation which now displays: 

![Monosnap 2022-02-11 22-56-27](https://user-images.githubusercontent.com/579256/153625181-98cf06ce-776f-4d65-8eb9-53df672f24f6.png)

Would that work for you ?

**Comment by lesquoyb** [comment]
Yes I think it's important to have it at least documented.
I think that @ptaillandier had a few problems with debugging models that turned out to just have a seed set to zero somewhere, maybe he has other ideas about it.
Just a thought : can't we write a log or something when a simulation is started with a random seed ? I think it would solve those kind of problems

**Comment by AlexisDrogoul** [comment]
Difficult to do more than documenting on this issue. I'm closing it now.
