### ISSUE TITLE
Wrong out of memory message

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#3307]
**Describe the bug**
After running a memory intensive simulation, gama displays a lot of error messages every time I try to run a new experiment while the real memory usage seem to be low.

**To Reproduce**
1. Run a memory intensive simulation, in my case it was the experiment Meshes from `Grid DEM.gaml` from the models library
2. after running this experiment try to run any other simulation
3. 
![image](https://user-images.githubusercontent.com/6374469/155939789-f782270a-985e-48c2-a27e-d85e84e66add.png)

**Expected behavior**
The new simulation runs normally.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PC Model: lenovo legion 5, CPU: AMD ryzen 5600H, 16Go ram
 - GAMA version: 1.8.2 
 - Graphics cards / Display system: RTX 3060

**Comment by AlexisDrogoul** [comment]
I cant reproduce it on macOS. Is it the only model in which this is appearing ? The only explanation I can think of is that the display of meshes uses a lot of direct buffers, which are supposed to be using the so-called native, or off-heap, memory. Maybe Windows 11 manages it differently ?

**Comment by hqnghi88** [comment]
On my config, that simulation is really intensive , it use 12+GB memory (note that the task manager of windows may have bug in displaying memory used, sometime). So the message "out of memory" is normal as the default memory allocated for gama is only 4GB.
(i dont know why the last display is blank??)
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6105384/156402439-6f983c13-bb23-48a4-992d-770686a055d3.png">
The problem : that memory is not released (or a part of) when simulation killed, here is the memory after launch (7GB)
<img width="723" alt="image" src="https://user-images.githubusercontent.com/6105384/156403195-5cd2aef9-0f5d-4ceb-8f93-7923be17c5ff.png">

**Comment by AlexisDrogoul** [comment]
The last blank screen is a mistake I did when copying the camera settings. It has been corrected by the last commit. I am however surprised by the fact that I do not have the same issues on my own Windows 11 settings. 

Other thing: what GAMA monitors is the available heap memory, while the 12Gb++ you mention are clearly off-heap memory (otherwise you wouldn't be able to use it in your 4Gb limit).

**Comment by lesquoyb** [comment]
I also cannot reproduce it anymore, but at the time I submitted the issue I did reproduce the bug multiple times with new instances of gama. So I think there is some external factor to it. I also don't think it's specific to this model as I'm quite sure that I encounter this bug previously on another one, but unfortunatly I can't remember the name.

As for the heap memory, we can see in the right hand-corner of the first screenshot that there is only 979M used out of the 4096M allocated to gama

**Comment by hqnghi88** [comment]
It is better with the buffer disposing.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/6105384/156489784-c637228c-3efd-433c-892d-a77cf0cf3ed7.png">
The heap at right hand-corner is always low, so there was a real leak not related with that heap.

**Comment by AlexisDrogoul** [comment]
The thing I have implemented allows to de-reference the buffers used by the MeshDrawer (and probably the TextDrawer too). But it does not force the GC to kick-in and reclaim this memory. However, unmapping / deallocating direct NIO buffers does not seem so easy... (https://stackoverflow.com/questions/3496508/deallocating-direct-buffer-native-memory-in-java-for-jogl/26777380#26777380).

So the version I have posted where the references to the buffers are explicitly nullified, will maybe help to release them faster...
@lesquoyb : do you think that a pressure on your memory by other programs could explain what you experienced ? i.e. one scenario could be : you use a lot of memory outside GAMA (other programs, outside the heap of course), then GAMA creates several buffers (outside the heap), does not reclaim them because the heap memory is ok (so the GC does not kick in), and you try to create more and run out of "off-heap" memory, which triggers a "low memory" exception, which itself triggers the alerts you have been seeing (actually, low memory exceptions can be raised for both heap and off-heap memory...).

**Comment by hqnghi88** [comment]
I dont have anymore this issue. It seem be safe to close.
