### ISSUE TITLE
Lists of 50 agents (in the menu agents) after some agents have been killed

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama#3323]
**Is your request related to a problem? Please describe.**
Consider the case  where an initial set of  agents is created initially,  but some are  killed during the simulation.
Now when wanting to inspect one agent through the menu `Agents` , `Simulation 0`, `Population of agents`.
Here you have the agents (e.g. road) oganisedd by  set of 50 agents (0-> 49, 50-> 99 ...).
This  works perfectly when no agent has been killed.
But when some agents  are missing, in the group 0-> 49, GAMA still wants to display the 50 first agents, even if the last one is not  the agent with id  = 49.
The consequence is that you can have in  the set of 50-> 57, agents with number from 96 to 109.
Which is quite unintuitive.

<img width="681" alt="Screenshot 2022-03-13 at 16 08 37" src="https://user-images.githubusercontent.com/1555274/158066199-b5543387-867f-4bd5-82cf-e03b0df937d0.png">

**Comment by AlexisDrogoul** [comment]
Hi,

I do not really see it as a problem. On one hand you have the number of agents, by chunks of 50, on the other their names (which contain their index). Of course the two can get desynchronised and it is "unintuitive", because I guess you expected the indices to be listed, right ? But it would be the same if, for instance, you'd gave them some random names, or numbers. The only improvement we might bring would be to sort the agents alphabetically by their names and display this information in the submenu (i.e. "road3 to road94", ...).

**Comment by hqnghi88** [comment]
Dear Alexis,
Can we add the order before the name? 56.road107,  57. road109

**Comment by AlexisDrogoul** [comment]
@hqnghi88 I'm afraid it would add more confusion, no ? With two indexes ... 

@benoitgaudou would something like this be ok ? (I killed and created many agents, hence the gaps):

![image](https://user-images.githubusercontent.com/579256/158203485-da7f7abb-30fb-4b88-b5a7-9f251e918c2f.png)

**Comment by hqnghi88** [comment]
Dear Alexis,
2 index, may be, but the information i see is different. If we keep the old : 0 to 50 , 50 to 57, we know directly the total number of agent (58). 
Your new solution is good, but i wonder if we still divide the list by N or re-order by the name. I m afraid some case like: N=5 and it show From people0 to people50 because 45 agents have been killed between 0 - 50.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 the N you are talking about is something fixed that is defined in the Preferences. And, yes, your example is exactly what happens with the "fix".

**Comment by benoitgaudou** [comment]
Thanks, I think it is more intuitive to me like that.

**Comment by sriramab** [comment]
I wonder if this is such a big issue that warrants a preference and that too with 3 preferences. I doubt if majority of modelers ever kill their agents! 
My opinion is to have it in advanced preferences just not to clutter the standard preferences. 
And if it is advanced, then may be it can go into GAML like the `browse` statement in 'experiment'.
