### ISSUE TITLE
multithreaded simulation runs

### ISSUE THREAD

**Issue by pcaillou** [gama-platform/gama#738]
```
Hi there!

Is there any possibility to run simulations on more than one thread?
I'm looking for speedup options for simulations with a lot of (100000) agents.

It would be great to have multiple threads working on the reflexes for each step. As
the control flow is not (obviously) defined (i.e which agent's reflex is executed first),
threads would not introduce concurrency problems into the GAMA model. (I ca nimagine
that there might be interpreter problems).

Thanks & Cheers, Achim
```

Original issue reported on code.google.com by `Achim.Gaedke` on 2013-11-25 06:19:44

**Comment by AlexisDrogoul** [comment]
As a side note and reminder: the current version of GAMA supports multi-simulations experiments (but within a single thread). The solution for transforming this architecture into a multi-threaded run is not trivial, and probably involves using ThreadLocal values for all the outputs (for example, the displays maintain a state which happens to be shared among the simulations). But it is feasible: without outputs, it runs almost perfectly.

**Comment by AlexisDrogoul** [comment]
The basic proof of concept has been committed and works quite well with the displays, too — multi-simulations now run in a multi-threaded way, but they are synchronized on the steps (i.e. the steps of the simulations run in parallel, but the experiment waits, every step, for the termination of all these parallel steps). I have still to add:

- [ ] a preference to turn it off and on by default
- [ ] a preference to limit the number of threads used
- [ ] a facet in `experiment` to enable or disable this behavior (and maybe fix the max. number of threads, too)
- [ ] this behavior for batch experiments
- [ ] a check to turn it off for headless experiments

**Comment by AlexisDrogoul** [comment]
Batch experiments now use multi-threading partially (i.e. when running parallel repetitions of the simulations). Not sure if opening it more would be helpful. In any case, the speed gain is impressive when doing a large number of repetitions. I close this issue.

**Comment by AlexisDrogoul** [comment]
Recent developments support to run agents, within their species/grid, or as targets of a `ask` statement, in parallel. It is still experimental, but can be tested on the latest builds. 

There are 2 possibilities to test it:

- either to set the appropriate preferences (in "Performances > Concurrency"), which will apply to all models.
- or to do it on a model basis, by adding the selected `grid/species` definitions or `ask` statements the facet `parallel: true`. The value of this facet can also be set to an integer, which then represents the minimum number of agents under which the run will be sequential. So, for instance, `ask my_agents parallel: 1 { ... do something ... }` will make the agents run all in parallel. And `species aa parallel: 50 {...}` will step in parallel batches of 50 agents. Having this level of control is important because, for simple agents, the cost of creating parallel tasks and scheduling them among the threads can be higher than their execution time, therefore ruining the interest of running them in parallel.

A default value for this 'sequential threshold' can be set in the preferences too. 

Note that it is an experimental feature. Depending on the models, unexpected conflicts or errors can happen (esp. if the agents share common structures or manipulate each other). Also, although the parallel runs try to keep as much as the original sequence, there are no guarantees that the agents will be scheduled in the order defined by the modeler. 

That said, preliminary testings show vast improvements for models run on multi-core architectures (up to 3x faster in some cases). 

Enjoy !
